'use strict';
(()=>{let session={user:null,csrf:null,company:null},ready=false;const panel=document.createElement('section');panel.id='account';panel.className='module lesson';panel.innerHTML='<p class="eyebrow">SUA EMPRESA · SEU APRENDIZADO</p><h2 id="account-title">Conta e empresa</h2><p id="account-summary">Conectando ao servidor…</p><form id="account-form"><label id="account-company-label">Nome da empresa <input id="account-company" maxlength="80" autocomplete="organization"></label><label id="account-name-label">Seu nome <input id="account-name" maxlength="80" autocomplete="name"></label><label id="account-email-label">Email <input id="account-email" type="email" autocomplete="username" maxlength="254"></label><label>Senha <input id="account-password" type="password" autocomplete="current-password" maxlength="128" required></label><p>Para criar a conta, use pelo menos 12 caracteres na senha.</p><button class="button">Continuar</button></form><button id="account-logout" class="button secondary" hidden>Sair da conta</button><section id="company-admin" hidden><h3>Alunos da empresa</h3><form id="company-invite"><label>Email do aluno <input type="email" id="invite-email" required maxlength="254"></label><button class="button secondary">Criar convite</button></form><p>Copie o link e compartilhe com o aluno. O convite expira em 72 horas.</p><textarea id="invite-link" readonly rows="3" aria-label="Link do convite" hidden></textarea><button id="company-refresh" class="reset">Atualizar relatório</button><div id="company-report"></div></section><p id="account-status" role="status"></p><a href="#catalog" class="button secondary">Voltar ao curso →</a>';
 document.querySelector('#reset').before(panel);
 const $=s=>panel.querySelector(s),invite=()=>new URLSearchParams(location.hash.split('?')[1]||'').get('invite');
 async function request(route,body){const response=await fetch('/api/company/'+route+(body===undefined?'?language='+StudyLanguage.code:''),{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':session.csrf||''},body:body===undefined?undefined:JSON.stringify({...body,language:body.language||StudyLanguage.code}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível acessar o servidor.');return data;}
 const personalKeys=Object.values(StudyData.keys).filter(key=>![StudyData.keys.curriculum,StudyAssessment.key].includes(key));
 function savePersonal(){if(!session.user||localStorage.getItem('studyia.account-cache-user')!==session.user.id)return;localStorage.setItem('studyia.personal.'+session.user.id+(StudyLanguage.code!=='en'?'.'+StudyLanguage.code:''),JSON.stringify(Object.fromEntries(personalKeys.map(key=>[key,localStorage.getItem(key)]))));}
 function loadPersonal(id){let stored={};try{stored=JSON.parse(localStorage.getItem('studyia.personal.'+id+(StudyLanguage.code!=='en'?'.'+StudyLanguage.code:''))||'{}');}catch{}for(const key of personalKeys){if(typeof stored[key]==='string')localStorage.setItem(key,stored[key]);else localStorage.removeItem(key);}}
 function apply(state){localStorage.setItem(StudyData.keys.curriculum,JSON.stringify(state.curriculum));StudyJourney.hydrate(state.journey);document.dispatchEvent(new Event('studyia:server-state'));return state;}
 function render(){const user=session.user;const required=Boolean(session.available&&session.company&&!user);document.body.classList.toggle('login-required',required);if(required&&!location.hash.startsWith('#account'))location.hash='account';document.dispatchEvent(new Event('studyia:account'));$('#account-email').type=session.development?'text':'email';$('#account-email').placeholder=session.development?'admin ou email':'';$('#account-title').textContent=session.company||'Configure sua empresa';$('#account-summary').textContent=user?`${user.name} · ${user.role==='admin'?'Administrador':'Aluno'}. Seu curso é salvo no servidor.`:session.setupRequired?'Cadastre a empresa e sua primeira conta de administrador.':invite()?'Você recebeu um convite para esta empresa. Defina seu nome e senha.':'Entre com a conta criada pelo convite da empresa. A prática sem conta é uma demonstração local.';$('#account-form').hidden=Boolean(user);$('#account-company-label').hidden=!session.setupRequired;$('#account-company').required=Boolean(session.setupRequired);$('#account-name-label').hidden=!session.setupRequired&&!invite();$('#account-name').required=Boolean(session.setupRequired||invite());$('#account-email-label').hidden=Boolean(invite());$('#account-email').required=!invite();$('#account-logout').hidden=!user;$('#company-admin').hidden=user?.role!=='admin';$('#account-password').minLength=session.setupRequired||invite()?12:1;document.querySelector('#backup-import')?.setAttribute('data-account-mode',user?'server':'local');document.body.classList.toggle('signed-in',Boolean(user));document.querySelector('footer').textContent=user?'StudyIA · Curso da empresa · Progresso salvo no servidor':'StudyIA · Demonstração · Progresso salvo neste navegador';}
 async function report(){if(session.user?.role!=='admin')return;const data=await request('report');const root=$('#company-report');root.replaceChildren();for(const user of data.users){const row=document.createElement('article');row.className='connection-card';const title=document.createElement('strong');title.textContent=user.name;const text=document.createElement('p');text.textContent=`${user.email} · ${user.pending?'Diagnóstico '+user.pending:user.level} · ${user.completedLessons} aulas · ${user.approvedBlocks} blocos aprovados`;row.append(title,text);root.append(row);}}
 async function restoreGuest(){localStorage.removeItem('studyia.account-cache-user');const raw=sessionStorage.getItem('studyia.guest-cache');let data={};try{data=JSON.parse(raw||'{}');}catch{}for(const key of Object.values(StudyData.keys)){if(Object.hasOwn(data,key)&&data[key]!==null)localStorage.setItem(key,data[key]);else localStorage.removeItem(key);}sessionStorage.removeItem('studyia.guest-cache');StudyJourney.hydrate(StudyAssessment.validate(JSON.parse(localStorage.getItem(StudyAssessment.key)||JSON.stringify(StudyAssessment.defaults()))));document.dispatchEvent(new Event('studyia:server-state'));}
 async function enter(data){ready=false;document.body.classList.add('account-loading');if(!session.user&&!sessionStorage.getItem('studyia.guest-cache'))sessionStorage.setItem('studyia.guest-cache',JSON.stringify(Object.fromEntries(Object.values(StudyData.keys).map(key=>[key,localStorage.getItem(key)]))));session=data;loadPersonal(data.user.id);localStorage.setItem('studyia.account-cache-user',data.user.id);apply(await request('learning'));document.dispatchEvent(new Event('studyia:journey'));render();await report();}
 $('#account-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const mode=session.setupRequired?'setup':invite()?'accept':'login';await enter(await request(mode,{company:$('#account-company').value,name:$('#account-name').value,email:$('#account-email').value,password:$('#account-password').value,token:invite()}));$('#account-password').value='';location.hash=session.user?.role==='admin'?'account':'home';location.reload();}catch(error){ready=true;document.body.classList.remove('account-loading');if(session.user){document.body.classList.add('account-unavailable');location.hash='account';render();}$('#account-status').textContent=error.message;}finally{button.disabled=false;}});
 async function logout(){if(!session.user||!ready)return false;document.querySelectorAll('#account-logout,#header-logout,.tour-exit').forEach(b=>b.disabled=true);try{savePersonal();ready=false;document.body.classList.add('account-loading');await request('logout',{});session.user=null;await restoreGuest();location.hash='account';location.reload();return true;}catch(error){ready=true;document.body.classList.remove('account-loading');location.hash='account';$('#account-status').textContent=error.message;return false;}finally{document.querySelectorAll('#account-logout,#header-logout,.tour-exit').forEach(b=>b.disabled=false);}}
 $('#account-logout').addEventListener('click',logout);
 $('#company-invite').addEventListener('submit',async event=>{event.preventDefault();try{const data=await request('invite',{email:$('#invite-email').value});$('#invite-link').hidden=false;$('#invite-link').value=location.origin+'/#account?invite='+encodeURIComponent(data.token);$('#invite-link').select();$('#account-status').textContent='Convite criado. Copie o link para compartilhar.';}catch(error){$('#account-status').textContent=error.message;}});$('#company-refresh').addEventListener('click',()=>report().catch(error=>$('#account-status').textContent=error.message));
 globalThis.StudyAccount={user:()=>session.user?{...session.user}:null,signedIn:()=>Boolean(session.user),logout,request,apply,csrf:()=>session.csrf||'',ready:()=>ready};
 window.addEventListener('hashchange',render);
 window.addEventListener('pagehide',savePersonal);document.addEventListener('studyia:progress',()=>{if(ready)savePersonal();});
 window.addEventListener('storage',event=>{if(event.key==='studyia.account-cache-user'&&ready){document.body.classList.add('account-loading');location.reload();}});
 window.addEventListener('focus',async()=>{if(!ready||!session.available)return;try{const current=await request('session');if((current.user?.id||null)!==(session.user?.id||null)){document.body.classList.add('account-loading');location.reload();}else if(current.user){session.csrf=current.csrf;}}catch{}});
 window.addEventListener('load',async()=>{try{if(location.protocol==='file:'){session.setupRequired=false;$('#account-form').hidden=true;$('#account-summary').textContent='Abra pelo servidor para usar contas empresariais.';return;}const data=await request('session');if(data.available===false){if(localStorage.getItem('studyia.account-cache-user'))throw Error('O banco da sua conta não está disponível. Os dados locais não substituem o servidor.');session=data;render();$('#account-form').hidden=true;$('#account-summary').textContent='Contas preparadas para PostgreSQL. Configure a conexão e execute as migrações para ativar. A demonstração local continua disponível.';return;}if(data.user){const previousUser=localStorage.getItem('studyia.account-cache-user');session=data;if(data.language!==StudyLanguage.code){localStorage.setItem('studyia.language',data.language||'en');location.reload();return;}if(previousUser!==data.user.id)loadPersonal(data.user.id);localStorage.setItem('studyia.account-cache-user',data.user.id);apply(await request('learning'));if(previousUser!==data.user.id){location.reload();return;}document.dispatchEvent(new Event('studyia:journey'));}else{if(sessionStorage.getItem('studyia.guest-cache')||localStorage.getItem('studyia.account-cache-user'))await restoreGuest();session=data;}render();await report();const link=document.createElement('a');link.href='#account';link.className='button secondary';link.textContent=session.user?'Minha conta e empresa':'Entrar · configurar empresa';document.querySelector('#home .hero').append(link);if(invite())location.hash='account?invite='+encodeURIComponent(invite());}catch(error){document.body.classList.add('account-unavailable');location.hash='account';$('#account-form').hidden=true;$('#account-summary').textContent='Não foi possível sincronizar a conta. Recarregue quando o servidor estiver disponível.';$('#account-status').textContent=error.message;}finally{ready=true;document.body.classList.remove('account-loading');}});
})();
