'use strict';
(()=>{
 const panel=document.createElement('section');panel.id='ai-panel';panel.className='teacher-panel';
 panel.innerHTML='<p class="eyebrow">SEU PROFESSOR IA</p><h3>Ouça, responda e pratique.</h3><p id="ai-goal"></p><p class="muted">O texto enviado e o contexto recente são processados pela OpenAI. As respostas podem conter erros. O áudio de leitura usa as vozes do navegador.</p><div class="teacher-controls"><label for="ai-mode">Prática <select id="ai-mode"><option value="conversation">Conversação</option><option value="listening">Listening</option></select></label><label for="ai-topic">Tema <select id="ai-topic"><option value="introductions">Apresentação pessoal</option><option value="numbers">Números e horários</option><option value="cafe">Na cafeteria</option><option value="vocabulary">Vocabulário</option><option value="general">Prática livre</option></select></label><label for="ai-voice-language">Idioma da leitura <select id="ai-voice-language"><option value="en-US">Inglês</option><option value="pt-BR">Português</option></select></label><label for="ai-rate">Velocidade <select id="ai-rate"><option value="0.75">Devagar</option><option value="1" selected>Normal</option></select></label></div><p id="ai-status" role="status">Verificando disponibilidade…</p><div id="ai-suggestions" class="word-bank" aria-label="Sugestões de prática"></div><button id="ai-local-example" class="button secondary" hidden>Ouvir exemplo da aula</button><div id="ai-log" role="log" aria-live="polite"></div><form id="ai-form"><label for="ai-input">Sua resposta em inglês</label><textarea id="ai-input" maxlength="1000" rows="3" required disabled placeholder="Escreva ou use o microfone. Revise antes de enviar."></textarea><div class="teacher-actions"><button class="button" disabled>Enviar ao professor</button><button id="ai-mic" class="button secondary" type="button">Responder por voz</button><button id="ai-mic-stop" class="button secondary" type="button" hidden>Parar microfone</button></div></form><p id="ai-mic-status" role="status"></p><p class="muted">A transcrição depende do navegador e pode usar o serviço de voz dele. Só o texto revisado é enviado ao professor ao clicar em Enviar. Esta prática não atribui nota de pronúncia.</p><button id="ai-stop-speech" class="reset">Parar áudio</button><button id="ai-clear" class="reset">Recomeçar esta prática</button>';
 document.querySelector('#chat-form').closest('section').append(panel);
 const $=s=>panel.querySelector(s),status=$('#ai-status'),input=$('#ai-input'),send=$('#ai-form button'),log=$('#ai-log'),topic=$('#ai-topic'),mode=$('#ai-mode');
 let activeLesson=null,level='A1',available=false,busy=false,history=[],controller=null,revision=0,recognition=null,voiceTimer=null;
 let homeHost=null;
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 const starters={introductions:'Can we practice introductions?',numbers:'Can we practice numbers and time?',cafe:'Can we practice ordering at a cafe?',vocabulary:'Help me use new words in a conversation.',general:'Start a conversation with me.'};
 function stopVoice(){clearTimeout(voiceTimer);if(recognition){const old=recognition;recognition=null;old.onresult=null;old.onerror=null;old.onend=null;old.abort();}$('#ai-mic-stop').hidden=true;controls();}
 function controls(){input.disabled=!available||busy||!!recognition;send.disabled=!available||busy||!!recognition;topic.disabled=busy||history.length>0||!!activeLesson;mode.disabled=busy||!!recognition;$('#ai-mic').disabled=!Recognition||!available||busy||!!recognition;$('#ai-clear').disabled=busy;panel.querySelectorAll('#ai-suggestions button').forEach(b=>b.disabled=!available||busy);$('#ai-voice-language').disabled=mode.value==='listening';}
 function read(text,lang=(globalThis.StudyLanguage?.speech||'en-US')){
  pauseScene();stopVoice();if(!window.speechSynthesis){status.textContent='Leitura em áudio indisponível neste navegador. Revele o texto para continuar.';return;}
  const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=Number($('#ai-rate').value);const voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase()===lang.toLowerCase());if(voice)u.voice=voice;
  u.onstart=()=>status.textContent='Reproduzindo áudio do professor…';u.onend=()=>status.textContent='Sua vez. Responda ao que ouviu.';u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error))status.textContent='Não foi possível reproduzir. Revele o texto ou tente outra voz no navegador.';};speechSynthesis.speak(u);
 }
 function suggestions(){
  $('#ai-goal').textContent=activeLesson?`${activeLesson.level} · Aula ${activeLesson.number}: ${activeLesson.title}`:`${level} · ${topic.selectedOptions[0].textContent}`;
  const container=$('#ai-suggestions');container.replaceChildren();
  const prompt=mode.value==='listening'?'Start a short listening practice. I will listen first and then answer.':activeLesson?activeLesson.conversation.prompt:starters[topic.value];
  const b=document.createElement('button');b.className='button secondary';b.textContent=mode.value==='listening'?'Preparar listening com IA':'Iniciar conversa com IA';b.addEventListener('click',()=>{input.value=prompt;$('#ai-form').requestSubmit();});container.append(b);
  $('#ai-local-example').hidden=!activeLesson;controls();
 }
 function reset(){revision++;controller?.abort();controller=null;busy=false;stopVoice();pauseScene();history=[];log.replaceChildren();input.value='';$('#ai-mic-status').textContent=Recognition?'':'Transcrição de voz indisponível neste navegador. Você pode responder por texto.';suggestions();status.textContent=available?'Escolha uma prática ou envie sua primeira mensagem.':'Professor ainda não configurado. Os exemplos de áudio da aula continuam disponíveis.';}
 function message(text,role){
  const article=document.createElement('article');article.className=role==='user'?'chat-user':'chat-tutor';const p=document.createElement('p');p.textContent=text;
  const name=document.createElement('strong');name.textContent=role==='user'?'Você':'Professor IA';article.append(name);
  if(role==='assistant'){
   const listen=document.createElement('button');listen.className='listen';listen.textContent='Ouvir resposta';listen.addEventListener('click',()=>read(text,mode.value==='listening'?(globalThis.StudyLanguage?.speech||'en-US'):$('#ai-voice-language').value));article.append(listen);
   if(mode.value==='listening'){p.hidden=true;const reveal=document.createElement('button');reveal.className='listen';reveal.textContent='Revelar transcrição';reveal.setAttribute('aria-expanded','false');reveal.addEventListener('click',()=>{p.hidden=!p.hidden;reveal.setAttribute('aria-expanded',String(!p.hidden));reveal.textContent=p.hidden?'Revelar transcrição':'Ocultar transcrição';});article.append(reveal);}
  }
  article.append(p);log.append(article);log.scrollTop=log.scrollHeight;
 }
 function connectionStatus(){const el=document.querySelector('#ai-connection');if(el)el.textContent=available?'Professor configurado. A conexão real é verificada ao enviar.':'Professor indisponível. Continue com os exemplos e a prática guiada.';}
 async function init(){try{const response=await fetch('/api/status',{signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error();available=(await response.json()).configured===true;}catch{available=false;}status.textContent=available?'Escolha listening ou conversação para começar.':'Professor ainda não configurado. Os exemplos de áudio da aula continuam disponíveis.';controls();connectionStatus();}
 $('#ai-form').addEventListener('submit',async e=>{
  e.preventDefault();const text=input.value.trim();if(!text||busy||!available||recognition)return;
  busy=true;controls();status.textContent='O professor está preparando sua prática…';controller=new AbortController();const current=controller,version=revision;const timeout=setTimeout(()=>current.abort(),50000);
  try{const messages=[...history.slice(-18),{role:'user',content:text}];const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':globalThis.StudyAccount?.csrf()||''},body:JSON.stringify({language:StudyLanguage.code,messages,topic:topic.value,level,practice:mode.value,...(activeLesson?{lessonId:activeLesson.id}:{})}),signal:current.signal});const data=await response.json();if(version!==revision||current.signal.aborted)return;if(!response.ok)throw Error(data.error||'Não foi possível obter uma resposta.');if(typeof data.reply!=='string'||!data.reply.trim())throw Error('Resposta inválida. Tente novamente.');history=[...messages,{role:'assistant',content:data.reply}];message(text,'user');message(data.reply,'assistant');input.value='';status.textContent=mode.value==='listening'?'Ouça a resposta antes de revelar o texto. Depois responda ao professor.':'Sua vez. Escreva ou dite sua resposta.';document.dispatchEvent(new CustomEvent('studyia:activity',{detail:{token:'ai-'+crypto.randomUUID()}}));}
  catch(error){if(version===revision)status.textContent=current.signal.aborted?'Solicitação interrompida. Sua mensagem permanece no campo.':error.message;}
  finally{clearTimeout(timeout);if(version===revision){busy=false;controller=null;controls();}}
 });
 $('#ai-mic').addEventListener('click',()=>{
  if(!Recognition||busy||recognition)return;pauseScene();const r=new Recognition();recognition=r;r.lang=(globalThis.StudyLanguage?.speech||'en-US');r.continuous=false;r.interimResults=false;r.maxAlternatives=1;const initial=input.value;
  $('#ai-mic-status').textContent='Ouvindo sua resposta em inglês…';$('#ai-mic-stop').hidden=false;controls();
  r.onresult=e=>{if(recognition!==r)return;const spoken=Array.from(e.results).map(result=>result[0].transcript).join(' ');input.value=(initial+' '+spoken).trim().slice(0,1000);$('#ai-mic-status').textContent='Transcrição pronta. Revise o texto e clique em Enviar ao professor.';};
  r.onerror=e=>{if(recognition===r)$('#ai-mic-status').textContent=e.error==='not-allowed'?'Microfone não autorizado. Você pode responder por texto.':'Não foi possível transcrever. Tente novamente ou responda por texto.';};
  r.onend=()=>{if(recognition!==r)return;recognition=null;clearTimeout(voiceTimer);$('#ai-mic-stop').hidden=true;controls();if($('#ai-mic-status').textContent.startsWith('Ouvindo'))$('#ai-mic-status').textContent='Nenhuma fala transcrita. Tente novamente ou digite sua resposta.';};
  try{r.start();voiceTimer=setTimeout(()=>{if(recognition===r)r.stop();},30000);}catch{stopVoice();$('#ai-mic-status').textContent='Microfone indisponível. Continue por texto.';}
 });
 $('#ai-mic-stop').addEventListener('click',()=>recognition?.stop());$('#ai-stop-speech').addEventListener('click',pauseScene);$('#ai-local-example').addEventListener('click',()=>{if(activeLesson)read(activeLesson.example.en);});$('#ai-clear').addEventListener('click',reset);mode.addEventListener('change',reset);topic.addEventListener('change',reset);
 if(!Recognition)$('#ai-mic-status').textContent='Transcrição de voz indisponível neste navegador. Você pode responder por texto.';
 document.addEventListener('studyia:teacher',e=>{const lesson=e.detail?.id?StudyCurriculum.get(e.detail.id):null,same=lesson&&activeLesson?.id===lesson.id;activeLesson=lesson;level=lesson?.level||StudyAssessment.currentLevel(StudyJourney.get())||'A1';if(e.detail?.topic)topic.value=e.detail.topic;if(e.detail?.mode)mode.value=e.detail.mode==='listening'?'listening':'conversation';else if(!same)mode.value='conversation';if(e.detail?.host)document.querySelector(e.detail.host)?.append(panel);if(!same||e.detail?.mode)reset();else{suggestions();controls();}});
 document.addEventListener('studyia:lesson',e=>{activeLesson=StudyCurriculum.get(e.detail?.id)||null;level=activeLesson?.level||'A1';reset();});
 document.addEventListener('studyia:teacher-pause',()=>{revision++;controller?.abort();controller=null;busy=false;stopVoice();pauseScene();controls();});
 document.addEventListener('studyia:navigate',()=>{revision++;controller?.abort();controller=null;busy=false;stopVoice();pauseScene();controls();if(homeHost&&!location.hash.startsWith('#learning'))homeHost.append(panel);});
 document.addEventListener('studyia:server-state',()=>{reset();level=StudyAssessment.currentLevel(StudyJourney.get())||'A1';suggestions();});
 document.addEventListener('DOMContentLoaded',()=>{
  homeHost=panel.parentElement;
  const settings=document.querySelector('#settings'),box=document.createElement('article');box.className='connection-card';box.innerHTML='<h3>Professor IA</h3><p id="ai-connection" role="status"></p><button id="ai-check" class="button secondary">Verificar disponibilidade</button>';settings.append(box);$('#ai-goal').textContent='';box.querySelector('#ai-check').addEventListener('click',init);connectionStatus();suggestions();
  for(const [id,context]of [['lesson','introductions'],['numbers','numbers'],['cafe','cafe'],['vocabulary','vocabulary'],['studio','general'],['units','general']]){
   const module=document.getElementById(id);if(!module)continue;const entry=document.createElement('div');entry.className='teacher-entry';const title=document.createElement('strong');title.textContent='Pratique este conteúdo com o professor IA';entry.append(title);
   for(const [practice,label]of [['conversation','Conversação com IA'],['listening','Listening com IA']]){const button=document.createElement('button');button.className='button secondary';button.textContent=label;button.addEventListener('click',()=>{location.hash='#conversation';setTimeout(()=>{homeHost.append(panel);document.querySelectorAll('#conversation > .subnav button')[2].click();document.dispatchEvent(new CustomEvent('studyia:teacher',{detail:{topic:context,mode:practice}}));panel.scrollIntoView({block:'start'});},0);});entry.append(button);}module.querySelector('h2').after(entry);
  }
 });suggestions();init();
})();
