'use strict';
(function(root){
 function create(C,language='en'){
 const passMark=80,key='studyia.journey.v1'+(language!=='en'?'.'+language:'');
 function defaults(){return{declared:'A1',entry:'A1',pending:null,results:{},draft:null};}
 function exam(id){const match=/^(placement|block)-(A1|A2|B1|B2|C1|C2)(?:-(\d{2}))?$/.exec(id||'');if(!match)return null;const [,kind,level,b]=match;const block=kind==='placement'?1:Number(b);if(kind==='placement'&&b||kind==='block'&&(!b||block<1||block>15))return null;const lessons=C.lessons.filter(l=>l.level===level).slice((block-1)*10,block*10);if(lessons.length!==10)return null;const questions=lessons.map((l,index)=>{const base={id:index,lessonId:l.id};if(index<3){const q=l.questions[0];return{...base,type:'choice',prompt:q.prompt,options:q.options,answer:q.answer};}if(index<6){const q=l.questions[1];return{...base,type:'listening',prompt:'Ouça a frase e escolha o significado.',audio:l.example.en,options:q.options,answer:q.answer};}if(index<8)return{...base,type:'writing',prompt:'Escreva em '+({en:'inglês',es:'espanhol',fr:'francês',it:'italiano',de:'alemão',ja:'japonês',ko:'coreano',zh:'mandarim'}[language])+' a frase estudada: '+l.example.pt,reference:l.example.en};if(index===9&&language==='en'){const [minWords,maxWords]=({A1:[25,60],A2:[40,90],B1:[60,120],B2:[80,150],C1:[100,180],C2:[120,220]})[level];const topics=[...new Set(lessons.map(x=>x.topic))];const vocabulary=[...new Set(lessons.flatMap(x=>x.vocabulary.map(v=>v.en)))].slice(0,8);const task=({A1:'Apresente uma pessoa e descreva uma situação simples do dia a dia.',A2:'Conte uma experiência cotidiana, explicando o que aconteceu e seus planos.',B1:'Descreva uma situação e explique suas escolhas com razões e exemplos.',B2:'Discuta uma situação, comparando alternativas e justificando sua opinião.',C1:'Analise uma situação, considerando argumentos, limites e consequências.',C2:'Elabore uma análise com nuances e adapte o tom a um leitor específico.'})[level];return{...base,type:'essay',level,minWords,maxWords,vocabulary,prompt:task+' Escreva em inglês entre '+minWords+' e '+maxWords+' palavras, aplicando o conteúdo deste bloco: '+topics.join(', ')+'. Use pelo menos três expressões estudadas (sugestões: '+vocabulary.join(', ')+'). Sua redação será enviada à OpenAI para correção; cada critério vale 25 pontos: tema, vocabulário, gramática e coerência. A questão é considerada correta a partir de 80 pontos, com pelo menos 15 em tema.'};}const q=l.questions[1];return{...base,type:'choice',prompt:'Leia a frase e escolha o significado: '+l.example.en,options:q.options,answer:q.answer};});return{id,kind,level,block,lessons:lessons.map(l=>l.id),questions};}
 function validate(value){if(!value||!C.levels.includes(value.declared)||value.entry!==null&&!C.levels.includes(value.entry)||value.pending!==null&&!C.levels.includes(value.pending)||!value.results||typeof value.results!=='object'||Array.isArray(value.results)||Object.keys(value.results).length>96)throw Error('Jornada inválida.');const results={};for(const[id,r]of Object.entries(value.results)){if(!exam(id)||!r||!Number.isInteger(r.score)||r.score<0||r.score>100||!Number.isInteger(r.attempts)||r.attempts<1||r.attempts>100000||typeof r.date!=='string'||!Number.isFinite(Date.parse(r.date)))throw Error('Resultado inválido.');results[id]={score:r.score,attempts:r.attempts,date:r.date};}let draft=null;if(value.draft!==null){const d=value.draft;if(!d||!exam(d.id)||!Array.isArray(d.marks)||d.marks.length!==10||d.marks.some(n=>n!==null&&n!==0&&n!==100))throw Error('Prova em andamento inválida.');draft={id:d.id,marks:[...d.marks]};}if((value.pending!==null)!==(value.entry===null)||value.pending==='A1')throw Error('Diagnóstico inválido.');return{declared:value.declared,entry:value.entry,pending:value.pending,results,draft};}
 function choose(state,level){if(!C.levels.includes(level))throw Error('Nível inválido.');return{...state,declared:level,entry:level==='A1'?'A1':null,pending:level==='A1'?null:level,draft:null};}
 function passed(state,level,block){return(state.results[`block-${level}-${String(block).padStart(2,'0')}`]?.score??-1)>=passMark;}
 function currentLevel(state){if(state.pending||!state.entry)return null;let index=C.levels.indexOf(state.entry);while(index<C.levels.length-1&&Array.from({length:15},(_,i)=>passed(state,C.levels[index],i+1)).every(Boolean))index++;return C.levels[index];}
 function accessLesson(id,state,progress){const l=C.get(id);if(!l)return{allowed:false,reason:'Aula não encontrada.'};if(state.pending)return{allowed:false,reason:'Conclua o diagnóstico inicial para definir seu nível de entrada.'};if(C.levels.indexOf(l.level)>C.levels.indexOf(currentLevel(state)))return{allowed:false,reason:'Conclua as provas do seu nível atual para avançar.'};for(let n=1;n<l.number;n++){const prev=`${l.level}-${String(n).padStart(3,'0')}`;if(progress[prev]?.length!==3)return{allowed:false,reason:`Conclua a aula ${prev} antes de continuar.`};if(n%10===0&&!passed(state,l.level,n/10))return{allowed:false,reason:`Aprove a prova do bloco ${n/10} de ${l.level} para liberar a próxima aula.`,examId:`block-${l.level}-${String(n/10).padStart(2,'0')}`};}return{allowed:true};}
 function accessExam(id,state,progress){const e=exam(id);if(!e)return false;if(e.kind==='placement')return state.pending===e.level;if(state.pending||C.levels.indexOf(e.level)>C.levels.indexOf(currentLevel(state)))return false;return e.lessons.every(id=>progress[id]?.length===3&&accessLesson(id,state,progress).allowed);}
 const normalise=text=>String(text).normalize('NFKC').toLowerCase().replace(/[’‘]/g,"'").replace(/\bi'm\b/g,'i am').replace(/\bwe're\b/g,'we are').replace(/\bthey're\b/g,'they are').replace(/\byou're\b/g,'you are').replace(/\bcan't\b/g,'cannot').replace(/\bwon't\b/g,'will not').replace(/\bdon't\b/g,'do not').replace(/\bdoesn't\b/g,'does not').replace(/\bdidn't\b/g,'did not').replace(/[^\p{L}\p{M}\p{N}\s'-]/gu,'').replace(/\s+/g,['ja','zh'].includes(language)?'':' ').trim();
 function grade(question,response){if(question.type==='essay')throw Error('Redação requer correção no servidor.');if(question.type==='pronunciation')throw Error('Pronúncia requer análise de áudio.');if(question.type==='writing')return normalise(response)===normalise(question.reference)?100:0;return response!==null&&String(response).trim()!==''&&Number(response)===question.answer?100:0;}
 function finish(state,id,marks){if(!exam(id)||marks.length!==10||marks.some(n=>n!==0&&n!==100))throw Error('Responda às dez questões.');const score=marks.reduce((sum,n)=>sum+n,0)/10;const old=state.results[id];const e=exam(id);let next={...state,results:{...state.results,[id]:{score:e.kind==='block'?Math.max(score,old?.score??0):score,attempts:(old?.attempts??0)+1,date:new Date().toISOString()}},draft:null};if(e.kind==='placement'){if(score>=passMark)next={...next,entry:e.level,pending:null};else{const lower=C.levels[C.levels.indexOf(e.level)-1]||'A1';next={...next,entry:lower==='A1'?'A1':null,pending:lower==='A1'?null:lower};}}return{state:next,score,passed:score>=passMark};}
 function performance(state,level){return Math.round(Array.from({length:15},(_,i)=>state.results[`block-${level}-${String(i+1).padStart(2,'0')}`]?.score||0).reduce((a,b)=>a+b,0)/15);}
 return {key,passMark,defaults,validate,exam,choose,passed,currentLevel,accessLesson,accessExam,grade,finish,performance};}
 const api=create(typeof module!=='undefined'?require('./curriculum.js'):root.StudyCurriculum,root.StudyLanguage?.code||'en');api.create=create;root.StudyAssessment=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
