'use strict';
(() => {
 const cafe=[
  {question:'Você quer pedir um café com educação. Qual frase usar?',options:['I would like a coffee, please.','My name is coffee.','What time is coffee?'],correct:0,explanation:'I would like a coffee, please. — Eu gostaria de um café, por favor.'},
  {question:'O atendente pergunta “Anything else?”. Como dizer “Não, obrigado”?',options:['Hello!','No, thank you.','I am nine.'],correct:1,explanation:'No, thank you. — Não, obrigado. “Anything else?” significa “Mais alguma coisa?”.'},
  {question:'Como perguntar quanto custa?',options:['Nice to meet you.','What is your name?','How much is it?'],correct:2,explanation:'How much is it? — Quanto custa?'}
 ];
 const listening=[
  {question:'Ouça a frase e escolha o significado.',phrase:'What is your name?',options:['Qual é o seu nome?','São três horas.','Quanto custa?'],correct:0,explanation:'What is your name? — Qual é o seu nome?'},
  {question:'Que horário você ouviu?',phrase:"It's nine o'clock.",options:['Três horas','Nove horas','Doze horas'],correct:1,explanation:'It’s nine o’clock. — São nove horas.'},
  {question:'Qual pedido você ouviu?',phrase:'I would like a coffee, please.',options:['Um chá','O nome da pessoa','Um café'],correct:2,explanation:'I would like a coffee, please. — Eu gostaria de um café, por favor.'}
 ];
 window.StudyCourse={cafe,listening};
 function quiz(root,unit,questions){
  root.innerHTML='<p class="eyebrow quiz-counter"></p><h3 class="quiz-question"></h3><button class="button secondary quiz-listen" hidden>🔊 Ouvir desafio</button><button class="reset quiz-transcript" hidden>Mostrar transcrição</button><p class="quiz-text" role="status"></p><form class="quiz-form"><fieldset class="quiz-options"></fieldset><button class="button">Verificar resposta</button></form><p class="quiz-feedback" role="status"></p><button class="button secondary quiz-next" hidden>Continuar →</button><p class="quiz-progress muted"></p><button class="reset quiz-reset">Reiniciar esta prática</button><p class="quiz-storage" role="status"></p>';
  let done=[];const key=StudyData.keys[unit];try{const saved=localStorage.getItem(key);if(saved)done=StudyData.lesson(JSON.parse(saved),questions.length);}catch{root.querySelector('.quiz-storage').textContent='Não foi possível recuperar esta prática. Você pode continuar.';}
  let current=questions.findIndex((_,i)=>!done.includes(i));
  function progress(){root.querySelector('.quiz-progress').textContent=`${done.length} de ${questions.length} exercícios concluídos`;document.dispatchEvent(new CustomEvent('studyia:progress',{detail:{unit,count:done.length,total:questions.length}}));}
  function save(){try{localStorage.setItem(key,JSON.stringify(done));}catch{root.querySelector('.quiz-storage').textContent='Não foi possível salvar. O progresso fica nesta sessão.';}}
  function render(){const complete=current<0;root.querySelector('.quiz-counter').textContent=complete?'PRÁTICA CONCLUÍDA':`EXERCÍCIO ${current+1} DE ${questions.length}`;root.querySelector('.quiz-question').textContent=complete?'Muito bem! Continue praticando.':questions[current].question;root.querySelector('.quiz-form').hidden=complete;root.querySelector('.quiz-next').hidden=true;root.querySelector('.quiz-feedback').textContent='';root.querySelector('.quiz-text').textContent='';root.querySelector('.quiz-listen').hidden=complete||!questions[current].phrase;root.querySelector('.quiz-transcript').hidden=complete||!questions[current].phrase;root.querySelector('.quiz-form button').disabled=false;const options=root.querySelector('.quiz-options');options.replaceChildren();const legend=document.createElement('legend');legend.className='sr-only';legend.textContent='Escolha uma resposta';options.append(legend);if(!complete)questions[current].options.forEach((text,i)=>{const label=document.createElement('label');const radio=document.createElement('input');radio.type='radio';radio.name='answer';radio.value=i;radio.required=true;label.append(radio,document.createTextNode(text));options.append(label);});progress();}
  root.querySelector('.quiz-form').addEventListener('submit',event=>{event.preventDefault();if(current<0||done.includes(current))return;const answer=new FormData(event.currentTarget).get('answer');if(answer===null)return;const correct=Number(answer)===questions[current].correct;document.dispatchEvent(new CustomEvent('studyia:attempt',{detail:{unit,index:current,correct}}));root.querySelector('.quiz-feedback').textContent=correct?`Correto! ${questions[current].explanation}`:'Tente novamente. Revise os exemplos ou ouça mais uma vez.';if(correct){done.push(current);save();progress();root.querySelectorAll('.quiz-options input').forEach(input=>input.disabled=true);root.querySelector('.quiz-form button').disabled=true;root.querySelector('.quiz-next').hidden=false;}});
  root.querySelector('.quiz-next').addEventListener('click',()=>{pauseScene();current=questions.findIndex((_,i)=>!done.includes(i));render();root.querySelector('.quiz-question').tabIndex=-1;root.querySelector('.quiz-question').focus();});
  root.querySelector('.quiz-listen').addEventListener('click',()=>{if(current>=0){pauseScene();speak(questions[current].phrase);}});
  root.querySelector('.quiz-transcript').addEventListener('click',()=>{if(current>=0)root.querySelector('.quiz-text').textContent=questions[current].phrase+' — Transcrição consultada. Esta prática não gera uma nota de compreensão auditiva.';});
  root.querySelector('.quiz-reset').addEventListener('click',()=>{if(!confirm('Reiniciar os exercícios desta prática?'))return;pauseScene();done=[];current=0;save();render();});render();
 }
 const unit=document.createElement('section');unit.id='cafe';unit.className='module lesson';unit.innerHTML='<a href="#units" class="reset">← Voltar à trilha</a><p class="eyebrow">UNIDADE 03 / NA CAFETERIA</p><h2>A coffee, please.</h2><p>Aprenda a fazer um pedido, responder ao atendente e perguntar o preço.</p><nav class="subnav" aria-label="Atividades da cafeteria"><button aria-pressed="true">Aprender</button><button aria-pressed="false">Exercitar</button></nav><div id="cafe-learn"><div class="examples"></div></div><div id="cafe-practice" hidden></div>';
 document.querySelector('#reset').before(unit);
 cafe.forEach(item=>{const article=document.createElement('article');const text=document.createElement('strong');text.textContent=item.options[item.correct];const translation=document.createElement('span');translation.textContent=item.explanation;const button=document.createElement('button');button.className='listen';button.textContent='🔊 Ouvir';button.setAttribute('aria-label',`Ouvir ${text.textContent}`);button.addEventListener('click',()=>{pauseScene();speak(text.textContent);});article.append(text,translation,button);unit.querySelector('.examples').append(article);});
 unit.querySelectorAll('.subnav button').forEach((button,index)=>button.addEventListener('click',()=>{pauseScene();unit.querySelector('#cafe-learn').hidden=index!==0;unit.querySelector('#cafe-practice').hidden=index!==1;unit.querySelectorAll('.subnav button').forEach((tab,i)=>tab.setAttribute('aria-pressed',String(i===index)));}));
 quiz(unit.querySelector('#cafe-practice'),'cafe',cafe);
 const listeningPanel=document.createElement('article');listeningPanel.id='listening-panel';listeningPanel.innerHTML='<h3>Ouça e descubra</h3><p>Escute cada frase e escolha o significado. A voz é sintetizada pelo navegador. Você pode usar a transcrição se o áudio estiver indisponível.</p><div id="listening-quiz"></div>';document.querySelector('.media-lab').append(listeningPanel);quiz(listeningPanel.querySelector('#listening-quiz'),'listening',listening);
})();
