'use strict';
(function(root){
// 25 topics, six separately authored examples per topic.
const blocks=[
['Sentidos implícitos',`
read between the lines|ler nas entrelinhas|To read between the lines, we must consider what the speaker avoids saying as well as what is stated.|Para ler nas entrelinhas, precisamos considerar o que o interlocutor evita dizer e o que é declarado.
by implication|por implicação|The praise singles out one department and, by implication, questions the performance of the others.|O elogio destaca um departamento e, por implicação, questiona o desempenho dos demais.
leave unsaid|deixar sem dizer|What we leave unsaid can be understood as tact, hesitation or disagreement, depending on the context.|O que deixamos sem dizer pode ser entendido como tato, hesitação ou discordância, dependendo do contexto.
presuppose|pressupor|The question appears neutral but presupposes that the decision was a mistake.|A pergunta parece neutra, mas pressupõe que a decisão foi um erro.
implied criticism|crítica implícita|The remark contains an implied criticism that a literal translation would fail to convey.|O comentário contém uma crítica implícita que uma tradução literal não conseguiria transmitir.
plausible deniability|possibilidade plausível de negar uma intenção|The deliberately vague wording gives the speaker plausible deniability without making the implication disappear.|A formulação deliberadamente vaga permite ao interlocutor negar de modo plausível sua intenção, sem fazer a implicação desaparecer.`],
['Ironia e atenuação',`
deadpan|impassível ao fazer humor|Her deadpan delivery made it unclear, at first, whether she was joking.|A maneira impassível como ela falou tornou inicialmente pouco claro se estava brincando.
tongue-in-cheek|dito em tom de brincadeira irônica|The tongue-in-cheek compliment works only if the audience recognises the shared reference.|O elogio em tom de brincadeira irônica só funciona se o público reconhecer a referência compartilhada.
understatement|atenuação deliberada|Calling the complete collapse a minor setback is an understatement that may signal either humour or evasion.|Chamar o colapso completo de pequeno contratempo é uma atenuação que pode indicar humor ou evasão.
ironic distance|distanciamento irônico|The quotation marks create ironic distance between the narrator and the supposedly reassuring phrase.|As aspas criam um distanciamento irônico entre o narrador e a frase supostamente tranquilizadora.
double-edged|de efeito ambivalente|The compliment is double-edged: it praises the result while questioning the methods used to achieve it.|O elogio tem um efeito ambivalente: elogia o resultado e questiona os métodos usados para alcançá-lo.
take at face value|aceitar literalmente / sem questionar|It would be unwise to take at face value a remark whose tone contradicts its literal meaning.|Seria pouco prudente aceitar literalmente um comentário cujo tom contradiz seu significado literal.`],
['Linguagem figurada',`
move the goalposts|mudar os critérios durante o processo|If we move the goalposts after every review, no participant can know what counts as success.|Se mudarmos os critérios depois de cada revisão, nenhum participante poderá saber o que conta como sucesso.
a double-edged sword|algo com efeitos benéficos e prejudiciais|Complete visibility can be a double-edged sword, encouraging accountability while discouraging experimentation.|A visibilidade completa pode ter efeitos benéficos e prejudiciais, incentivando a prestação de contas e desestimulando a experimentação.
the elephant in the room|problema evidente que ninguém aborda|The elephant in the room is not the timetable but the unresolved disagreement about the project's purpose.|O problema evidente que ninguém aborda não é o cronograma, mas a divergência não resolvida sobre a finalidade do projeto.
paper over the cracks|disfarçar problemas sem resolvê-los|A polished announcement may paper over the cracks without addressing the underlying conflict.|Um anúncio bem elaborado pode disfarçar os problemas sem abordar o conflito subjacente.
thread the needle|conciliar exigências difíceis de compatibilizar|The negotiator must thread the needle between reassuring the partners and avoiding an unrealistic promise.|O negociador precisa conciliar a tranquilização dos parceiros com a necessidade de evitar uma promessa irrealista.
a false dawn|sinal de melhora que não se confirma|The initial agreement proved to be a false dawn when its central terms were interpreted differently.|O acordo inicial se mostrou um sinal enganoso de melhora quando suas condições centrais foram interpretadas de maneiras diferentes.`],
['Arquitetura argumentativa',`
steelman|apresentar a versão mais forte de um argumento|Before rejecting the proposal, we should steelman the case made by its most thoughtful supporters.|Antes de rejeitar a proposta, deveríamos apresentar a versão mais forte da defesa feita por seus apoiadores mais cuidadosos.
beg the question|pressupor como verdadeira a conclusão a demonstrar|To define a successful policy as one that follows this method is to beg the question we are trying to answer.|Definir uma política bem-sucedida como aquela que segue este método é pressupor a conclusão que estamos tentando demonstrar.
false dichotomy|falsa dicotomia|The speech creates a false dichotomy by presenting caution and ambition as mutually exclusive.|O discurso cria uma falsa dicotomia ao apresentar cautela e ambição como mutuamente exclusivas.
burden of proof|ônus da prova|The burden of proof lies with the claim being advanced, not with every conceivable objection to it.|O ônus da prova recai sobre a afirmação apresentada, e não sobre toda objeção imaginável a ela.
non sequitur|conclusão que não decorre das premissas|The final recommendation is a non sequitur because the preceding evidence concerns a different question.|A recomendação final é uma conclusão que não decorre das premissas porque as evidências anteriores tratam de outra questão.
charitable interpretation|interpretação que busca a leitura razoável mais favorável|A charitable interpretation reconstructs a coherent argument without pretending that its weaknesses do not exist.|Uma interpretação favorável reconstrói um argumento coerente sem fingir que suas fraquezas não existem.`],
['Escala e proporcionalidade',`
commensurate with|proporcional a|The response should be commensurate with the demonstrated risk, not merely with the intensity of the public reaction.|A resposta deveria ser proporcional ao risco demonstrado, e não apenas à intensidade da reação pública.
out of all proportion|completamente desproporcional|The attention given to the minor error was out of all proportion to its practical consequences.|A atenção dada ao pequeno erro foi completamente desproporcional às suas consequências práticas.
a matter of degree|uma questão de grau|The distinction is a matter of degree rather than a clean division between two categories.|A distinção é uma questão de grau, e não uma separação nítida entre duas categorias.
not insignificant|não desprezível|The effect is not insignificant, although describing it as transformative would overstate the case.|O efeito não é desprezível, embora descrevê-lo como transformador fosse exagerar sua importância.
vanishingly small|extremamente pequeno|The remaining difference is vanishingly small compared with the uncertainty in the estimate.|A diferença restante é extremamente pequena em comparação com a incerteza da estimativa.
disproportionately large|desproporcionalmente grande|A disproportionately large share of the discussion concerns the most visible rather than the most consequential problem.|Uma parcela desproporcionalmente grande da discussão trata do problema mais visível, e não do mais relevante em suas consequências.`],
['Precisão de estilo',`
judicious|criterioso|A judicious choice of detail can make a complex account accessible without making it simplistic.|Uma escolha criteriosa de detalhes pode tornar um relato complexo acessível sem torná-lo simplista.
economy of expression|concisão expressiva|Economy of expression requires removing redundancy while preserving the distinctions that carry the argument.|A concisão expressiva exige eliminar redundâncias e preservar as distinções que sustentam o argumento.
unwieldy|difícil de manejar / pouco ágil|The sentence becomes unwieldy because each qualification introduces another qualification.|A frase se torna pouco ágil porque cada ressalva introduz outra ressalva.
unambiguous|inequívoco|The instruction must be unambiguous about responsibility even if it leaves room for professional judgement.|A instrução precisa ser inequívoca quanto à responsabilidade, mesmo que deixe espaço para julgamento profissional.
apt|especialmente adequado|The metaphor is apt only if it illuminates the relationship rather than concealing its complexity.|A metáfora é adequada somente se esclarecer a relação em vez de ocultar sua complexidade.
laboured|forçado / elaborado em excesso|The comparison feels laboured because its explanation requires more effort than the original idea.|A comparação soa forçada porque sua explicação exige mais esforço do que a ideia original.`],
['Diplomacia institucional',`
without prejudice to|sem prejudicar / sem comprometer|We can discuss a temporary arrangement without prejudice to the broader question of responsibility.|Podemos discutir um acordo temporário sem comprometer a questão mais ampla da responsabilidade.
in good faith|de boa-fé|An agreement reached in good faith can still fail if its terms remain open to incompatible interpretations.|Um acordo alcançado de boa-fé ainda pode falhar se suas condições continuarem sujeitas a interpretações incompatíveis.
save face|preservar a imagem / evitar humilhação|The revised wording allows both sides to save face without concealing the substance of the disagreement.|A formulação revista permite aos dois lados preservar a imagem sem ocultar a substância da divergência.
constructive ambiguity|ambiguidade deliberada para permitir entendimento inicial|Constructive ambiguity may enable an initial agreement, but it can also defer the conflict rather than resolve it.|A ambiguidade deliberada pode permitir um acordo inicial, mas também pode adiar o conflito em vez de resolvê-lo.
expressly|de maneira explícita|The statement expressly recognises the objection while leaving the proposed remedy undecided.|A declaração reconhece explicitamente a objeção e deixa a solução proposta sem definição.
fall within the remit|estar dentro da esfera de atribuições|The question does not fall within the remit of this committee, although its consequences affect our work.|A questão não está dentro das atribuições deste comitê, embora suas consequências afetem nosso trabalho.`],
['Edição e condensação',`
distil|condensar o essencial|We need to distil the discussion into a summary that preserves both the agreement and the unresolved tensions.|Nós precisamos condensar o essencial da discussão em um resumo que preserve o acordo e as tensões não resolvidas.
redundancy|redundância|Removing redundancy should not mean deleting a qualification that changes the meaning of the claim.|Eliminar redundâncias não deveria significar apagar uma ressalva que muda o significado da afirmação.
retain the thrust|preservar a ideia central|The shorter version must retain the thrust of the argument without copying its entire structure.|A versão mais curta precisa preservar a ideia central do argumento sem copiar toda a sua estrutura.
mischaracterise|representar de forma inadequada|A summary can mischaracterise a position by omitting the conditions under which it is defended.|Um resumo pode representar inadequadamente uma posição ao omitir as condições em que ela é defendida.
salient|mais relevante / que se destaca|The most salient point for this audience is not necessarily the first point in the original report.|O ponto mais relevante para este público não é necessariamente o primeiro ponto do relatório original.
editorial judgement|julgamento editorial|Editorial judgement involves deciding what can be omitted without distorting the account.|O julgamento editorial envolve decidir o que pode ser omitido sem distorcer o relato.`],
['Limites de interpretação',`
underdetermined|não determinado de modo único pelas evidências|The explanation remains underdetermined because several accounts fit the same observations.|A explicação continua sem ser determinada de modo único porque vários relatos se ajustam às mesmas observações.
epistemic|relativo ao conhecimento e sua justificação|The disagreement is epistemic: it concerns what the evidence permits us to claim.|A divergência é relativa ao conhecimento: trata do que as evidências nos permitem afirmar.
defensible|defensável|A defensible interpretation need not be the only interpretation consistent with the text.|Uma interpretação defensável não precisa ser a única compatível com o texto.
indeterminate|indeterminado|The outcome remains indeterminate until the competing conditions have been specified.|O resultado continua indeterminado até que as condições concorrentes sejam especificadas.
tentatively inferred|inferido de forma provisória|The intention can be tentatively inferred, but it should not be presented as an established fact.|A intenção pode ser inferida de forma provisória, mas não deveria ser apresentada como um fato estabelecido.
warranted certainty|grau de certeza justificado|The wording should reflect the warranted certainty rather than the confidence of the speaker.|A formulação deveria refletir o grau de certeza justificado, e não a confiança do interlocutor.`],
['Causalidade e raciocínio',`
causal attribution|atribuição causal|Causal attribution becomes difficult when several changes occur at the same time.|A atribuição causal se torna difícil quando várias mudanças ocorrem ao mesmo tempo.
confounding factor|fator que confunde a interpretação de uma relação|A confounding factor may account for an apparent relationship between the two variables.|Um fator de confusão pode explicar uma relação aparente entre as duas variáveis.
counterfactual|contrafactual|The counterfactual asks what would have happened had the intervention not taken place.|O contrafactual pergunta o que teria acontecido se a intervenção não tivesse ocorrido.
necessary but not sufficient|necessário, mas não suficiente|Clear instructions are necessary but not sufficient when users also lack time and support.|Instruções claras são necessárias, mas não suficientes quando os usuários também não têm tempo e apoio.
causal chain|cadeia causal|The proposed causal chain contains a step that has not yet been independently examined.|A cadeia causal proposta contém uma etapa que ainda não foi examinada de forma independente.
explanatory power|poder explicativo|The account gains explanatory power if it can address the exceptions as well as the typical cases.|O relato ganha poder explicativo se conseguir abordar as exceções e os casos típicos.`],
['Responsabilidade e dilemas',`
culpability|culpabilidade|Culpability cannot be assessed solely by looking at the outcome while ignoring what could reasonably have been known.|A culpabilidade não pode ser avaliada apenas pelo resultado, ignorando o que razoavelmente poderia ter sido conhecido.
moral hazard|incentivo a assumir riscos cujos custos recaem sobre outros|The arrangement may create a moral hazard if one party gains from risks whose costs are borne elsewhere.|O acordo pode incentivar riscos indevidos se uma parte se beneficiar de riscos cujos custos recaem sobre outros.
due diligence|verificação cuidadosa antes de uma decisão|Due diligence should be more than a list of checks performed without considering their relevance.|Uma verificação cuidadosa deveria ser mais do que uma lista de conferências realizadas sem considerar sua pertinência.
competing obligations|obrigações concorrentes|Competing obligations may leave no option entirely free from justified criticism.|Obrigações concorrentes podem fazer com que nenhuma opção fique inteiramente livre de críticas justificadas.
foreseeability|possibilidade de previsão razoável|Foreseeability concerns what could reasonably have been anticipated, not everything that later became obvious.|A previsibilidade diz respeito ao que razoavelmente poderia ter sido antecipado, e não a tudo que depois se tornou óbvio.
ex post|depois do acontecimento|An ex post judgement may underestimate how uncertain the decision appeared at the time.|Um julgamento posterior pode subestimar o quanto a decisão parecia incerta na época.`],
['Políticas e efeitos sistêmicos',`
path dependence|dependência da trajetória anterior|Path dependence can make a theoretically attractive alternative difficult to adopt in practice.|A dependência da trajetória anterior pode tornar difícil adotar na prática uma alternativa teoricamente atraente.
perverse incentive|incentivo que produz comportamento contrário ao objetivo|The target creates a perverse incentive if staff improve the reported number by weakening the service.|A meta cria um incentivo perverso se os funcionários melhorarem o número divulgado enfraquecendo o serviço.
second-order effect|efeito indireto decorrente de um efeito inicial|A second-order effect may emerge when people adapt their behaviour to the new rule.|Um efeito indireto pode surgir quando as pessoas adaptam seu comportamento à regra nova.
systemic|sistêmico|A systemic problem is unlikely to disappear if the response focuses exclusively on individual mistakes.|Um problema sistêmico dificilmente desaparecerá se a resposta se concentrar exclusivamente em erros individuais.
feedback loop|ciclo de retroalimentação|The feedback loop reinforces the pattern because each response makes the next response more likely.|O ciclo de retroalimentação reforça o padrão porque cada resposta torna a próxima mais provável.
policy coherence|coerência entre políticas|Policy coherence requires examining how one measure may undermine the aims of another.|A coerência entre políticas exige examinar como uma medida pode prejudicar os objetivos de outra.`],
['Narrativas e enquadramento',`
framing|enquadramento|The framing of the question determines which experiences appear relevant before the discussion begins.|O enquadramento da pergunta determina quais experiências parecem relevantes antes que a discussão comece.
hegemonic|dominante a ponto de parecer natural|A hegemonic narrative may appear neutral precisely because its assumptions have become familiar.|Uma narrativa dominante pode parecer neutra justamente porque seus pressupostos se tornaram familiares.
counter-narrative|narrativa que questiona uma narrativa dominante|The counter-narrative challenges the accepted sequence without claiming that every earlier detail was false.|A narrativa alternativa questiona a sequência aceita sem afirmar que todo detalhe anterior era falso.
selective emphasis|ênfase seletiva|Selective emphasis can produce a misleading impression even when none of the statements is individually false.|Uma ênfase seletiva pode produzir uma impressão enganosa mesmo quando nenhuma afirmação é individualmente falsa.
discursive|relativo à construção pelo discurso|The disagreement concerns discursive choices as much as the underlying sequence of events.|A divergência diz respeito às escolhas discursivas tanto quanto à sequência subjacente de acontecimentos.
foreground|colocar em primeiro plano|The account foregrounds individual courage while leaving the institutional constraints in the background.|O relato coloca a coragem individual em primeiro plano e deixa as restrições institucionais em segundo plano.`],
['Identidade e alteridade',`
essentialise|tratar um grupo como se tivesse uma essência fixa|To essentialise a community is to treat its internal differences as incidental rather than meaningful.|Tratar uma comunidade como se tivesse uma essência fixa é considerar suas diferenças internas secundárias, e não significativas.
othering|construção de um grupo como estranho ou inferior|Othering can occur through apparently casual contrasts between normal people and everyone else.|A construção de um grupo como estranho pode ocorrer por contrastes aparentemente casuais entre pessoas consideradas normais e todos os demais.
intersection|intersecção|The intersection of several experiences may complicate an explanation based on a single category.|A intersecção de várias experiências pode complicar uma explicação baseada em uma única categoria.
fluidity|fluidez|The fluidity of identity does not mean that every attachment is temporary or superficial.|A fluidez da identidade não significa que todo vínculo seja temporário ou superficial.
homogenise|homogeneizar|A broad label can homogenise experiences that differ in important respects.|Um rótulo amplo pode homogeneizar experiências que diferem em aspectos importantes.
self-definition|autodefinição|Respecting self-definition does not require assuming that a person's account is simple or unchanging.|Respeitar a autodefinição não exige supor que o relato de uma pessoa seja simples ou imutável.`],
['Voz e perspectiva literária',`
free indirect discourse|discurso indireto livre|Free indirect discourse can blur the boundary between the narrator's language and a character's thoughts.|O discurso indireto livre pode tornar menos nítida a fronteira entre a linguagem do narrador e os pensamentos de um personagem.
focalisation|focalização / perspectiva pela qual a narrativa é percebida|The focalisation limits what the reader can know without making the account factually unreliable.|A focalização limita o que o leitor pode saber sem tornar o relato factualmente não confiável.
polyphonic|com várias vozes relativamente autônomas|A polyphonic novel allows competing voices to remain distinct rather than resolving them into a single authoritative view.|Um romance polifônico permite que vozes concorrentes permaneçam distintas em vez de reduzi-las a uma única visão autoritativa.
reticence|reserva / relutância em dizer|The narrator's reticence invites interpretation without supplying a definitive explanation for the silence.|A reserva do narrador convida à interpretação sem fornecer uma explicação definitiva para o silêncio.
unresolved tension|tensão não resolvida|The unresolved tension gives the ending its force rather than making it merely incomplete.|A tensão não resolvida dá força ao final em vez de torná-lo apenas incompleto.
authorial stance|posição do autor sugerida pela obra|The authorial stance should not be equated automatically with the opinions expressed by the protagonist.|A posição autoral não deveria ser automaticamente equiparada às opiniões expressas pelo protagonista.`],
['Arte e julgamento crítico',`
evocative|evocativo|The image is evocative because it suggests a history that the work never states explicitly.|A imagem é evocativa porque sugere uma história que a obra nunca declara explicitamente.
derivative|pouco original / derivado de modelos anteriores|Calling the work derivative requires explaining which conventions it repeats and why that repetition matters.|Chamar a obra de pouco original exige explicar quais convenções ela repete e por que essa repetição importa.
subversive|que questiona convenções ou relações estabelecidas|The apparently conventional ending becomes subversive when read against the expectations established earlier.|O final aparentemente convencional se torna subversivo quando lido em contraste com as expectativas estabelecidas antes.
aesthetic coherence|coerência estética|Aesthetic coherence can emerge from deliberate contrasts rather than from a uniform style.|A coerência estética pode surgir de contrastes deliberados, e não de um estilo uniforme.
resonance|ressonância / efeito associativo duradouro|The scene's resonance depends partly on memories that different viewers bring to it.|A ressonância da cena depende em parte das memórias que diferentes espectadores trazem a ela.
interpretive latitude|margem para interpretações|The work allows interpretive latitude without making every reading equally persuasive.|A obra permite uma margem de interpretação sem tornar toda leitura igualmente convincente.`],
['Variação e norma linguística',`
prescriptive|prescritivo|A prescriptive rule states how language should be used within a particular norm.|Uma regra prescritiva estabelece como a língua deveria ser usada dentro de determinada norma.
descriptive|descritivo|A descriptive account examines how speakers actually use a form rather than judging it against one preferred standard.|Um relato descritivo examina como os falantes realmente usam uma forma em vez de julgá-la por um único padrão preferido.
pragmatic competence|competência pragmática|Pragmatic competence involves understanding why a grammatically correct remark may still be inappropriate in context.|A competência pragmática envolve entender por que um comentário gramaticalmente correto ainda pode ser inadequado no contexto.
sociolinguistic|sociolinguístico|The choice is sociolinguistic as well as grammatical because it signals a relationship between speakers.|A escolha é sociolinguística e gramatical porque indica uma relação entre interlocutores.
marked|marcado / percebido como uma escolha não neutra|The formal expression becomes marked when it appears in an otherwise casual exchange.|A expressão formal se torna uma escolha marcada quando aparece em uma conversa de resto casual.
idiomaticity|naturalidade idiomática|Idiomaticity concerns the natural combination of words, not simply the absence of grammatical errors.|A naturalidade idiomática diz respeito à combinação natural de palavras, e não apenas à ausência de erros gramaticais.`],
['Tradução de nuances',`
semantic range|amplitude de sentidos|The semantic range of the word is broader than any single equivalent in the other language.|A amplitude de sentidos da palavra é maior do que a de qualquer equivalente isolado no outro idioma.
pragmatic equivalence|equivalência do efeito comunicativo|Pragmatic equivalence may require changing the structure to preserve the intended degree of politeness.|Preservar o efeito comunicativo pode exigir mudar a estrutura para manter o grau de cortesia pretendido.
untranslatable|sem equivalente direto de tradução|Calling an expression untranslatable usually means that its effects cannot be captured by a single direct equivalent.|Chamar uma expressão de intraduzível geralmente significa que seus efeitos não podem ser captados por um único equivalente direto.
compensate for|compensar|A translator may compensate for a lost wordplay by introducing an effect elsewhere in the passage.|Um tradutor pode compensar um jogo de palavras perdido introduzindo um efeito em outro ponto do trecho.
culturally embedded|inserido em um contexto cultural específico|A culturally embedded reference may require explanation, but the explanation can alter the pace of the exchange.|Uma referência culturalmente situada pode exigir explicação, mas a explicação pode alterar o ritmo da conversa.
preserve the ambiguity|preservar a ambiguidade|When uncertainty is intentional, the translation should preserve the ambiguity rather than choose an unsupported interpretation.|Quando a incerteza é intencional, a tradução deveria preservar a ambiguidade em vez de escolher uma interpretação sem fundamento.`],
['Negociação em impasses',`
entrenched interests|interesses firmemente estabelecidos|Entrenched interests can obstruct an agreement even when the practical options are well understood.|Interesses firmemente estabelecidos podem impedir um acordo mesmo quando as opções práticas são bem compreendidas.
credible commitment|compromisso crível|A credible commitment requires conditions that make follow-through more than a matter of goodwill.|Um compromisso crível exige condições que tornem seu cumprimento mais do que uma questão de boa vontade.
asymmetric information|informação assimétrica|Asymmetric information can make an apparently balanced offer seem risky to one of the parties.|A informação assimétrica pode fazer uma oferta aparentemente equilibrada parecer arriscada para uma das partes.
face-saving measure|medida que evita humilhação pública|A face-saving measure may make a concession possible without altering the substance of the agreement.|Uma medida que evita humilhação pública pode tornar possível uma concessão sem alterar a substância do acordo.
intractable|difícil de resolver|The dispute appears intractable because each side treats its preferred procedure as a matter of principle.|A disputa parece difícil de resolver porque cada lado trata seu procedimento preferido como uma questão de princípio.
break the deadlock|romper o impasse|A narrower provisional question may help break the deadlock without pretending the wider dispute has disappeared.|Uma questão provisória mais restrita pode ajudar a romper o impasse sem fingir que a disputa mais ampla desapareceu.`],
['Conflitos organizacionais',`
institutional inertia|inércia institucional|Institutional inertia can preserve a familiar process long after its original justification has weakened.|A inércia institucional pode preservar um processo familiar muito depois de sua justificativa original enfraquecer.
tacit knowledge|conhecimento tácito|Tacit knowledge may be lost when a transition records formal procedures but ignores everyday judgement.|O conhecimento tácito pode se perder quando uma transição registra procedimentos formais e ignora o julgamento cotidiano.
misaligned incentives|incentivos desalinhados|Misaligned incentives can lead conscientious teams to pursue goals that undermine one another.|Incentivos desalinhados podem levar equipes cuidadosas a buscar objetivos que se prejudicam mutuamente.
diffuse responsibility|responsabilidade dispersa|Diffuse responsibility makes it difficult to identify who should act when a problem crosses departmental boundaries.|A responsabilidade dispersa dificulta identificar quem deveria agir quando um problema atravessa fronteiras entre departamentos.
organisational silos|isolamento entre áreas de uma organização|Organisational silos can prevent relevant knowledge from reaching the people who need it.|O isolamento entre áreas pode impedir que conhecimentos relevantes cheguem às pessoas que precisam deles.
surface agreement|concordância apenas aparente|The surface agreement concealed incompatible assumptions about what implementation would involve.|A concordância aparente ocultava pressupostos incompatíveis sobre o que a implementação envolveria.`],
['Incerteza e decisão refinada',`
irreducible uncertainty|incerteza que não pode ser eliminada|Irreducible uncertainty may remain even after the available evidence has been examined carefully.|Uma incerteza que não pode ser eliminada pode permanecer mesmo após um exame cuidadoso das evidências disponíveis.
calibrate|calibrar / ajustar com precisão|We should calibrate the strength of the recommendation to the quality of the evidence.|Nós deveríamos ajustar a força da recomendação à qualidade das evidências.
contingency|eventualidade / condição possível|The plan must acknowledge a contingency that would fundamentally change the proposed course of action.|O plano precisa reconhecer uma eventualidade que mudaria fundamentalmente a ação proposta.
robustness|solidez diante de mudanças nas condições|Robustness matters when a decision must remain useful across several plausible scenarios.|A solidez importa quando uma decisão precisa continuar útil em vários cenários plausíveis.
precise qualification|ressalva formulada com precisão|A precise qualification narrows the claim without emptying it of useful content.|Uma ressalva precisa restringe a afirmação sem retirar dela seu conteúdo útil.
suspend judgement|suspender o julgamento|We may need to suspend judgement on the cause while still taking a reversible practical step.|Podemos precisar suspender o julgamento sobre a causa e ainda assim tomar uma medida prática reversível.`],
['Oratória e resposta espontânea',`
extemporaneous|improvisado / sem texto preparado|An extemporaneous answer can remain well structured if the speaker distinguishes the question from its hidden assumptions.|Uma resposta improvisada pode continuar bem estruturada se o interlocutor distinguir a pergunta de seus pressupostos ocultos.
recast|reformular|I would recast the question so that the practical concern is not confused with an accusation about motives.|Eu reformularia a pergunta para que a preocupação prática não se confunda com uma acusação sobre motivos.
concede the point|conceder que um ponto é válido|I can concede the point about cost without accepting the broader conclusion about feasibility.|Eu posso conceder que o ponto sobre o custo é válido sem aceitar a conclusão mais ampla sobre a viabilidade.
hold the floor|manter a palavra|The speaker should be able to hold the floor long enough to clarify the distinction without monopolising the discussion.|O interlocutor deveria conseguir manter a palavra pelo tempo necessário para esclarecer a distinção sem monopolizar a discussão.
sidestep|esquivar-se de / contornar|To sidestep the objection would make the answer smoother but less convincing.|Esquivar-se da objeção tornaria a resposta mais fluida, mas menos convincente.
succinctly|de forma sucinta|The challenge is to respond succinctly without reducing a conditional answer to a misleading yes or no.|O desafio é responder de forma sucinta sem reduzir uma resposta condicional a um sim ou não enganoso.`],
['Crítica de ideias',`
specious|aparentemente convincente, mas falho|The argument is specious because its attractive wording disguises an unsupported inference.|O argumento parece convincente, mas é falho porque sua formulação atraente disfarça uma inferência sem fundamento.
untenable|insustentável|The position becomes untenable if its central assumption is contradicted by the evidence it relies on.|A posição se torna insustentável se seu pressuposto central for contradito pelas evidências em que se apoia.
reductive|reducionista|The account is reductive when it treats a complex disagreement as nothing more than personal resistance.|O relato é reducionista quando trata uma divergência complexa como mera resistência pessoal.
internally consistent|internamente coerente|An internally consistent account can still be mistaken about the world it describes.|Um relato internamente coerente ainda pode estar errado sobre o mundo que descreve.
ad hoc|criado apenas para resolver um caso específico|An ad hoc explanation may rescue one example while weakening the general account.|Uma explicação feita apenas para um caso pode salvar um exemplo e enfraquecer o relato geral.
discriminating|capaz de distinguir com critério|A discriminating critique separates a genuine limitation from an objection that applies equally to every alternative.|Uma crítica criteriosa distingue uma limitação real de uma objeção que se aplica igualmente a todas as alternativas.`],
['Síntese de alta precisão',`
interweave|entrelaçar|The conclusion should interweave the perspectives without making them appear more compatible than they are.|A conclusão deveria entrelaçar as perspectivas sem fazê-las parecer mais compatíveis do que são.
irreconcilable|inconciliável|Some assumptions remain irreconcilable, even though the proposals share several practical aims.|Alguns pressupostos continuam inconciliáveis, embora as propostas compartilhem vários objetivos práticos.
overarching|abrangente / que engloba os demais|The overarching question concerns what kind of agreement would count as legitimate.|A questão abrangente diz respeito a que tipo de acordo seria considerado legítimo.
reconcile without conflating|conciliar sem confundir conceitos distintos|We should reconcile without conflating the concern about fairness and the concern about predictability.|Nós deveríamos conciliar sem confundir a preocupação com justiça e a preocupação com previsibilidade.
distinguishing feature|característica distintiva|The distinguishing feature is not the stated goal but the mechanism proposed to achieve it.|A característica distintiva não é o objetivo declarado, mas o mecanismo proposto para alcançá-lo.
qualified synthesis|síntese com ressalvas|A qualified synthesis can identify shared conclusions while preserving uncertainty about the explanation.|Uma síntese com ressalvas pode identificar conclusões compartilhadas e preservar a incerteza sobre a explicação.`],
['Mediação entre públicos',`
audience-sensitive|sensível às características do público|An audience-sensitive explanation changes its level of detail without changing the warranted claim.|Uma explicação sensível ao público muda seu nível de detalhe sem mudar a afirmação justificada.
register flexibility|flexibilidade de registro|Register flexibility involves preserving precision while moving between an expert discussion and an everyday explanation.|A flexibilidade de registro envolve preservar a precisão ao passar de uma discussão especializada a uma explicação cotidiana.
make explicit|tornar explícito|We need to make explicit an assumption that specialists might recognise but a general audience would not.|Nós precisamos tornar explícito um pressuposto que especialistas talvez reconheçam, mas um público geral não.
without condescension|sem condescendência|The explanation should be accessible without condescension or an exaggerated claim of simplicity.|A explicação deveria ser acessível sem condescendência nem uma alegação exagerada de simplicidade.
preserve the caveat|preservar a ressalva|Even the shortest version must preserve the caveat that changes how the result should be understood.|Mesmo a versão mais curta precisa preservar a ressalva que muda a forma de entender o resultado.
reformulate on the fly|reformular durante a própria conversa|A skilled speaker can reformulate on the fly when a listener's question reveals a different frame of reference.|Um interlocutor habilidoso consegue reformular durante a conversa quando a pergunta de um ouvinte revela um referencial diferente.`]
];
const topics=blocks.map(([topic,text])=>[topic,text.trim().split('\n').map(row=>row.split('|'))]);
root.StudyC2=topics;if(typeof module!=='undefined')module.exports=topics;
})(globalThis);
