'use strict';
(function(root){const Spanish=typeof module!=='undefined'?require('./curriculum-es.js'):root.StudySpanish;
 const data={fr:[
 [['nom','Je m’appelle Ana.'],['bonjour','Bonjour, je suis Leo.'],['Brésil','Je viens du Brésil.'],['français','Je parle français.'],['ami','Voici mon ami.'],['rencontrer','Ravi de te rencontrer.']],
 [['âge','J’ai vingt ans.'],['téléphone','Voici mon téléphone.'],['courriel','Quelle est ton adresse de courriel ?'],['adresse','Voici mon adresse.'],['nom de famille','Mon nom de famille est Silva.'],['nationalité','Je suis de nationalité brésilienne.']],
 [['mère','Voici ma mère.'],['père','Mon père est ici.'],['sœur','J’ai une sœur.'],['frère','Mon frère a dix ans.'],['parents','Mes parents habitent ici.'],['famille','J’aime ma famille.']],
 [['maison','Voici ma maison.'],['chambre','Ma chambre est petite.'],['cuisine','La cuisine est propre.'],['porte','La porte est ouverte.'],['fenêtre','Ferme la fenêtre, s’il te plaît.'],['lit','Le lit est neuf.']],
 [['matin','J’étudie le matin.'],['petit déjeuner','Je prends mon petit déjeuner à sept heures.'],['travail','Je travaille tous les jours.'],['déjeuner','Je déjeune à midi.'],['nuit','Je lis la nuit.'],['dormir','Je veux dormir.']],
 [['café','Je voudrais un café.'],['thé','Un thé, s’il vous plaît.'],['lait','Un café au lait, s’il vous plaît.'],['sucre','Sans sucre, s’il vous plaît.'],['tasse','Une tasse, s’il vous plaît.'],['addition','L’addition, s’il vous plaît.']],
 [['pain','Je mange du pain.'],['riz','J’aime le riz.'],['eau','Je bois de l’eau.'],['pomme','Cette pomme est rouge.'],['poulet','Je voudrais du poulet.'],['légumes','Je mange des légumes.']],
 [['prix','Quel est le prix ?'],['acheter','Je veux acheter ceci.'],['espèces','Je paie en espèces.'],['carte','Puis-je payer par carte ?'],['sac','J’ai besoin d’un sac.'],['monnaie','Voici ta monnaie.']],
 [['rue','Cette rue est longue.'],['banque','Où est la banque ?'],['parc','Le parc est proche.'],['gauche','Tourne à gauche.'],['droite','Tourne à droite.'],['gare','La gare est là-bas.']],
 [['billet','J’ai besoin d’un billet.'],['passeport','Voici mon passeport.'],['aéroport','L’aéroport est grand.'],['vol','Mon vol part à six heures.'],['bagages','Voici mes bagages.'],['carte','J’ai une carte.']],
 [['réservation','J’ai une réservation.'],['clé','Voici la clé.'],['nuits','Je voudrais réserver deux nuits.'],['salle de bains','Où est la salle de bains ?'],['étage','Ma chambre est à cet étage.'],['serviette','J’ai besoin d’une serviette.']],
 [['bus','Je prends le bus.'],['train','Le train est ici.'],['taxi','J’ai besoin d’un taxi.'],['voiture','Voici ma voiture.'],['vélo','Je vais à vélo.'],['arrêt','Où est l’arrêt ?']],
 [['soleil','Il y a du soleil aujourd’hui.'],['pluie','J’aime la pluie.'],['froid','Il fait froid ici.'],['chaleur','Il fait chaud aujourd’hui.'],['vent','Le vent est fort.'],['temps','Il fait beau.']],
 [['chemise','Cette chemise est bleue.'],['chaussures','Mes chaussures sont neuves.'],['taille','Quelle est la taille ?'],['manteau','J’ai besoin d’un manteau.'],['robe','Cette robe est rouge.'],['chapeau','J’aime ton chapeau.']],
 [['emploi','J’ai un nouvel emploi.'],['bureau','Mon bureau est petit.'],['responsable','Voici ma responsable.'],['réunion','La réunion est à deux heures.'],['bureau','Mon bureau est ici.'],['équipe','J’aime mon équipe.']],
 [['école','Mon école est proche.'],['professeur','Mon professeur est gentil.'],['livre','Voici mon livre.'],['crayon','J’ai besoin d’un crayon.'],['leçon','La leçon est facile.'],['question','J’ai une question.']],
 [['musique','J’aime la musique.'],['film','Ce film est bon.'],['lire','Je veux lire.'],['danser','J’aime danser.'],['jeu','Ce jeu est amusant.'],['week-end','Je me repose le week-end.']],
 [['football','Je joue au football.'],['nager','J’aime nager.'],['courir','Je veux courir dans le parc.'],['marcher','J’aime marcher.'],['ballon','Le ballon est ici.'],['tennis','Je joue au tennis.']],
 [['tête','J’ai mal à la tête.'],['fatigué','Je suis fatigué.'],['médecin','J’ai besoin d’un médecin.'],['se reposer','Je veux me reposer.'],['bien','Je me sens bien aujourd’hui.'],['rendez-vous','J’ai un rendez-vous.']],
 [['ordinateur','Mon ordinateur est neuf.'],['mot de passe','J’ai besoin d’un mot de passe.'],['écran','L’écran est grand.'],['message','J’ai un message.'],['internet','Internet est lent.'],['photo','Cette photo est belle.']],
 [['lundi','Je travaille le lundi.'],['aujourd’hui','Je suis libre aujourd’hui.'],['demain','À demain.'],['heure','À quelle heure est la réunion ?'],['tôt','Je me lève tôt.'],['en retard','J’arrive en retard.']],
 [['heureux','Je suis heureux.'],['triste','Je me sens triste aujourd’hui.'],['en colère','Je suis en colère.'],['enthousiaste','Je suis enthousiaste.'],['inquiet','Je suis inquiet.'],['calme','Je me sens calme.']],
 [['vouloir','Je veux étudier.'],['visiter','Je veux visiter la France.'],['apprendre','Je veux apprendre le français.'],['aller','Je veux aller à la maison.'],['voyager','J’aime voyager.'],['rester','Je veux rester ici.']],
 [['aide','J’ai besoin d’aide.'],['répéter','Peux-tu répéter ?'],['lentement','Parle lentement, s’il te plaît.'],['comprendre','Je ne comprends pas.'],['pardon','Pardon, je ne comprends pas.'],['s’il te plaît','Aide-moi, s’il te plaît.']],
 [['bienvenue','Bienvenue chez moi.'],['merci','Merci pour ton aide.'],['au revoir','Au revoir, à bientôt.'],['fête','La fête est vendredi.'],['anniversaire','Joyeux anniversaire, Ana.'],['ensemble','Nous étudions ensemble.']]
 ],it:[
 [['nome','Mi chiamo Ana.'],['ciao','Ciao, sono Leo.'],['Brasile','Vengo dal Brasile.'],['italiano','Parlo italiano.'],['amico','Questo è il mio amico.'],['conoscere','Piacere di conoscerti.']],
 [['età','Ho vent’anni.'],['telefono','Questo è il mio telefono.'],['email','Qual è la tua email?'],['indirizzo','Questo è il mio indirizzo.'],['cognome','Il mio cognome è Silva.'],['nazionalità','Sono di nazionalità brasiliana.']],
 [['madre','Questa è mia madre.'],['padre','Mio padre è qui.'],['sorella','Ho una sorella.'],['fratello','Mio fratello ha dieci anni.'],['genitori','I miei genitori abitano qui.'],['famiglia','Amo la mia famiglia.']],
 [['casa','Questa è la mia casa.'],['camera','La mia camera è piccola.'],['cucina','La cucina è pulita.'],['porta','La porta è aperta.'],['finestra','Chiudi la finestra, per favore.'],['letto','Il letto è nuovo.']],
 [['mattina','Studio la mattina.'],['colazione','Faccio colazione alle sette.'],['lavoro','Lavoro tutti i giorni.'],['pranzo','Pranzo a mezzogiorno.'],['notte','Leggo di notte.'],['dormire','Voglio dormire.']],
 [['caffè','Vorrei un caffè.'],['tè','Un tè, per favore.'],['latte','Un caffè con latte, per favore.'],['zucchero','Senza zucchero, per favore.'],['tazza','Una tazza, per favore.'],['conto','Il conto, per favore.']],
 [['pane','Mangio pane.'],['riso','Mi piace il riso.'],['acqua','Bevo acqua.'],['mela','Questa mela è rossa.'],['pollo','Vorrei del pollo.'],['verdure','Mangio verdure.']],
 [['prezzo','Qual è il prezzo?'],['comprare','Voglio comprare questo.'],['contanti','Pago in contanti.'],['carta','Posso pagare con la carta?'],['borsa','Ho bisogno di una borsa.'],['resto','Ecco il resto.']],
 [['strada','Questa strada è lunga.'],['banca','Dov’è la banca?'],['parco','Il parco è vicino.'],['sinistra','Gira a sinistra.'],['destra','Gira a destra.'],['stazione','La stazione è lì.']],
 [['biglietto','Ho bisogno di un biglietto.'],['passaporto','Ecco il mio passaporto.'],['aeroporto','L’aeroporto è grande.'],['volo','Il mio volo parte alle sei.'],['bagaglio','Questo è il mio bagaglio.'],['mappa','Ho una mappa.']],
 [['prenotazione','Ho una prenotazione.'],['chiave','Ecco la chiave.'],['notti','Vorrei prenotare due notti.'],['bagno','Dov’è il bagno?'],['piano','La mia camera è su questo piano.'],['asciugamano','Ho bisogno di un asciugamano.']],
 [['autobus','Prendo l’autobus.'],['treno','Il treno è qui.'],['taxi','Ho bisogno di un taxi.'],['auto','Questa è la mia auto.'],['bicicletta','Vado in bicicletta.'],['fermata','Dov’è la fermata?']],
 [['sole','Oggi c’è il sole.'],['pioggia','Mi piace la pioggia.'],['freddo','Qui fa freddo.'],['caldo','Oggi fa caldo.'],['vento','Il vento è forte.'],['tempo','Fa bel tempo.']],
 [['camicia','Questa camicia è blu.'],['scarpe','Le mie scarpe sono nuove.'],['taglia','Che taglia è?'],['cappotto','Ho bisogno di un cappotto.'],['vestito','Questo vestito è rosso.'],['cappello','Mi piace il tuo cappello.']],
 [['impiego','Ho un nuovo impiego.'],['ufficio','Il mio ufficio è piccolo.'],['responsabile','Questa è la mia responsabile.'],['riunione','La riunione è alle due.'],['scrivania','La mia scrivania è qui.'],['squadra','Mi piace la mia squadra.']],
 [['scuola','La mia scuola è vicina.'],['insegnante','Il mio insegnante è gentile.'],['libro','Questo è il mio libro.'],['matita','Ho bisogno di una matita.'],['lezione','La lezione è facile.'],['domanda','Ho una domanda.']],
 [['musica','Mi piace la musica.'],['film','Questo film è bello.'],['leggere','Voglio leggere.'],['ballare','Mi piace ballare.'],['gioco','Questo gioco è divertente.'],['fine settimana','Mi riposo nel fine settimana.']],
 [['calcio','Gioco a calcio.'],['nuotare','Mi piace nuotare.'],['correre','Voglio correre nel parco.'],['camminare','Mi piace camminare.'],['palla','La palla è qui.'],['tennis','Gioco a tennis.']],
 [['testa','Mi fa male la testa.'],['stanco','Sono stanco.'],['medico','Ho bisogno di un medico.'],['riposare','Voglio riposare.'],['bene','Oggi mi sento bene.'],['appuntamento','Ho un appuntamento.']],
 [['computer','Il mio computer è nuovo.'],['password','Ho bisogno di una password.'],['schermo','Lo schermo è grande.'],['messaggio','Ho un messaggio.'],['internet','Internet è lento.'],['foto','Questa foto è bella.']],
 [['lunedì','Lavoro il lunedì.'],['oggi','Oggi sono libero.'],['domani','A domani.'],['ora','A che ora è la riunione?'],['presto','Mi alzo presto.'],['in ritardo','Arrivo in ritardo.']],
 [['felice','Sono felice.'],['triste','Oggi mi sento triste.'],['arrabbiato','Sono arrabbiato.'],['entusiasta','Sono entusiasta.'],['preoccupato','Sono preoccupato.'],['tranquillo','Mi sento tranquillo.']],
 [['volere','Voglio studiare.'],['visitare','Voglio visitare l’Italia.'],['imparare','Voglio imparare l’italiano.'],['andare','Voglio andare a casa.'],['viaggiare','Mi piace viaggiare.'],['restare','Voglio restare qui.']],
 [['aiuto','Ho bisogno di aiuto.'],['ripetere','Puoi ripetere?'],['lentamente','Parla lentamente, per favore.'],['capire','Non capisco.'],['scusa','Scusa, non capisco.'],['per favore','Aiutami, per favore.']],
 [['benvenuto','Benvenuto a casa mia.'],['grazie','Grazie per il tuo aiuto.'],['arrivederci','Arrivederci, a presto.'],['festa','La festa è venerdì.'],['compleanno','Buon compleanno, Ana.'],['insieme','Studiamo insieme.']]
 ]};
 const metadata={fr:{name:'francês',opening:'Bonjour ! Pratiquons le français.',frames:{A2:['Dans cette situation, je peux dire : « ','Nesta situação posso dizer: “'],B1:['Pour expliquer mon expérience, j’ai choisi cette expression : « ','Para explicar minha experiência, escolhi esta expressão: “'],B2:['Bien qu’il existe d’autres possibilités, cette formulation me paraît appropriée : « ','Embora existam outras opções, esta formulação me parece adequada: “'],C1:['Sans négliger les nuances du contexte, il conviendrait de préciser ceci : « ','Sem desconsiderar as nuances do contexto, seria conveniente precisar o seguinte: “'],C2:['Quand bien même sa portée pourrait donner lieu à des interprétations divergentes, cette formulation se prête à la lecture suivante : « ','Ainda que seu alcance pudesse dar margem a interpretações divergentes, esta formulação permite a seguinte leitura: “']}},it:{name:'italiano',opening:'Ciao! Pratichiamo l’italiano.',frames:{A2:['In questa situazione posso dire: «','Nesta situação posso dizer: “'],B1:['Per spiegare la mia esperienza, ho scelto questa espressione: «','Para explicar minha experiência, escolhi esta expressão: “'],B2:['Sebbene esistano altre possibilità, ritengo adeguata questa formulazione: «','Embora existam outras opções, considero adequada esta formulação: “'],C1:['Senza trascurare le sfumature del contesto, sarebbe opportuno precisare quanto segue: «','Sem desconsiderar as nuances do contexto, seria conveniente precisar o seguinte: “'],C2:['Ancorché la sua portata possa prestarsi a interpretazioni divergenti, la formulazione ammette questa lettura: «','Ainda que seu alcance possa dar margem a interpretações divergentes, a formulação admite esta leitura: “']}}};
 function build(language){const meta=metadata[language];const lessons=Spanish.lessons.map(base=>{const g=Math.floor((base.number-1)/6),i=(base.number-1)%6,[word,text]=data[language][g][i],source=Spanish.lessons[g*6+i];let pt=source.example.pt;if(g===22&&i===1)pt=language==='fr'?'Quero visitar a França.':'Quero visitar a Itália.';if(g===22&&i===2)pt=`Quero aprender ${meta.name}.`;if(g===0&&i===3)pt=`Falo ${meta.name}.`;const frame=meta.frames[base.level],en=frame?frame[0]+text+'»':text;const translation=frame?frame[1]+pt+'”':pt;const vocabulary=data[language][g].map(([en],j)=>({en,pt:Spanish.lessons[g*6+j].vocabulary[j].pt}));if(g===0)vocabulary[3].pt=meta.name;vocabulary.push({en,pt:translation});const meaning=vocabulary[i].pt,options=[meaning,vocabulary[(i+1)%6].pt,vocabulary[(i+2)%6].pt],shift=base.number%3;const next=Spanish.lessons[g*6+(i+1)%6].example.pt,other=Spanish.lessons[g*6+(i+2)%6].example.pt;return{...base,language,title:`${base.topic}: ${word}`,objective:base.objective.replace(/espanhol/g,meta.name).replace(base.title.split(': ')[1],word),vocabulary,example:{en,pt:translation},conversation:{...base.conversation,opening:meta.opening,prompt:`Pratique o tema ${base.topic} em ${meta.name} ${base.level}. Use «${word}» e responda a uma pergunta por vez.`,instructions:base.conversation.instructions.replace(/espanhol/g,meta.name)},questions:[{prompt:`O que significa «${word}»?`,options:[...options.slice(shift),...options.slice(0,shift)],answer:(3-shift)%3,explanation:`${word} — ${meaning}`},{prompt:`Qual tradução corresponde a «${en}»?`,options:[frame?frame[1]+next+'”':next,translation,frame?frame[1]+other+'”':other],answer:1,explanation:translation}]};});return{levels:Spanish.levels,lessons,get:id=>lessons.find(l=>l.id===id)};}
 const api={fr:build('fr'),it:build('it')};root.StudyRomance=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
