'use strict';
(function(root){const Spanish=typeof module!=='undefined'?require('./curriculum-es.js'):root.StudySpanish;
 const rows={de:[
 [['Name','Ich heiße Ana.'],['hallo','Hallo, ich bin Leo.'],['Brasilien','Ich komme aus Brasilien.'],['Deutsch','Ich spreche Deutsch.'],['Freund','Das ist mein Freund.'],['kennenlernen','Schön, dich kennenzulernen.']],
 [['Alter','Ich bin zwanzig Jahre alt.'],['Telefon','Das ist mein Telefon.'],['E-Mail','Wie lautet deine E-Mail-Adresse?'],['Adresse','Das ist meine Adresse.'],['Nachname','Mein Nachname ist Silva.'],['Nationalität','Meine Nationalität ist brasilianisch.']],
 [['Mutter','Das ist meine Mutter.'],['Vater','Mein Vater ist hier.'],['Schwester','Ich habe eine Schwester.'],['Bruder','Mein Bruder ist zehn Jahre alt.'],['Eltern','Meine Eltern wohnen hier.'],['Familie','Ich liebe meine Familie.']],
 [['Haus','Das ist mein Haus.'],['Zimmer','Mein Zimmer ist klein.'],['Küche','Die Küche ist sauber.'],['Tür','Die Tür ist offen.'],['Fenster','Schließ bitte das Fenster.'],['Bett','Das Bett ist neu.']],
 [['Morgen','Ich lerne am Morgen.'],['Frühstück','Ich frühstücke um sieben Uhr.'],['Arbeit','Ich arbeite jeden Tag.'],['Mittagessen','Ich esse um zwölf Uhr zu Mittag.'],['Nacht','Ich lese nachts.'],['schlafen','Ich möchte schlafen.']],
 [['Kaffee','Ich hätte gern einen Kaffee.'],['Tee','Einen Tee, bitte.'],['Milch','Einen Kaffee mit Milch, bitte.'],['Zucker','Ohne Zucker, bitte.'],['Tasse','Eine Tasse, bitte.'],['Rechnung','Die Rechnung, bitte.']],
 [['Brot','Ich esse Brot.'],['Reis','Ich mag Reis.'],['Wasser','Ich trinke Wasser.'],['Apfel','Dieser Apfel ist rot.'],['Hähnchen','Ich hätte gern Hähnchen.'],['Gemüse','Ich esse Gemüse.']],
 [['Preis','Wie hoch ist der Preis?'],['kaufen','Ich möchte das kaufen.'],['Bargeld','Ich bezahle bar.'],['Karte','Kann ich mit Karte bezahlen?'],['Tasche','Ich brauche eine Tasche.'],['Wechselgeld','Hier ist dein Wechselgeld.']],
 [['Straße','Diese Straße ist lang.'],['Bank','Wo ist die Bank?'],['Park','Der Park ist in der Nähe.'],['links','Bieg links ab.'],['rechts','Bieg rechts ab.'],['Bahnhof','Der Bahnhof ist dort.']],
 [['Fahrkarte','Ich brauche eine Fahrkarte.'],['Reisepass','Hier ist mein Reisepass.'],['Flughafen','Der Flughafen ist groß.'],['Flug','Mein Flug geht um sechs Uhr.'],['Gepäck','Das ist mein Gepäck.'],['Karte','Ich habe eine Karte.']],
 [['Reservierung','Ich habe eine Reservierung.'],['Schlüssel','Hier ist der Schlüssel.'],['Nächte','Ich möchte zwei Nächte buchen.'],['Badezimmer','Wo ist das Badezimmer?'],['Stockwerk','Mein Zimmer ist in diesem Stockwerk.'],['Handtuch','Ich brauche ein Handtuch.']],
 [['Bus','Ich nehme den Bus.'],['Zug','Der Zug ist hier.'],['Taxi','Ich brauche ein Taxi.'],['Auto','Das ist mein Auto.'],['Fahrrad','Ich fahre mit dem Fahrrad.'],['Haltestelle','Wo ist die Haltestelle?']],
 [['Sonne','Heute scheint die Sonne.'],['Regen','Ich mag Regen.'],['Kälte','Hier ist es kalt.'],['Hitze','Heute ist es heiß.'],['Wind','Der Wind ist stark.'],['Wetter','Das Wetter ist schön.']],
 [['Hemd','Dieses Hemd ist blau.'],['Schuhe','Meine Schuhe sind neu.'],['Größe','Welche Größe ist das?'],['Mantel','Ich brauche einen Mantel.'],['Kleid','Dieses Kleid ist rot.'],['Hut','Ich mag deinen Hut.']],
 [['Stelle','Ich habe eine neue Stelle.'],['Büro','Mein Büro ist klein.'],['Chefin','Das ist meine Chefin.'],['Besprechung','Die Besprechung ist um zwei Uhr.'],['Schreibtisch','Mein Schreibtisch ist hier.'],['Team','Ich mag mein Team.']],
 [['Schule','Meine Schule ist in der Nähe.'],['Lehrer','Mein Lehrer ist nett.'],['Buch','Das ist mein Buch.'],['Bleistift','Ich brauche einen Bleistift.'],['Lektion','Die Lektion ist einfach.'],['Frage','Ich habe eine Frage.']],
 [['Musik','Ich mag Musik.'],['Film','Dieser Film ist gut.'],['lesen','Ich möchte lesen.'],['tanzen','Ich tanze gern.'],['Spiel','Dieses Spiel macht Spaß.'],['Wochenende','Am Wochenende ruhe ich mich aus.']],
 [['Fußball','Ich spiele Fußball.'],['schwimmen','Ich schwimme gern.'],['laufen','Ich möchte im Park laufen.'],['spazieren gehen','Ich gehe gern spazieren.'],['Ball','Der Ball ist hier.'],['Tennis','Ich spiele Tennis.']],
 [['Kopf','Mein Kopf tut weh.'],['müde','Ich bin müde.'],['Arzt','Ich brauche einen Arzt.'],['sich ausruhen','Ich möchte mich ausruhen.'],['gut','Heute fühle ich mich gut.'],['Termin','Ich habe einen Termin.']],
 [['Computer','Mein Computer ist neu.'],['Passwort','Ich brauche ein Passwort.'],['Bildschirm','Der Bildschirm ist groß.'],['Nachricht','Ich habe eine Nachricht.'],['Internet','Das Internet ist langsam.'],['Foto','Dieses Foto ist schön.']],
 [['Montag','Ich arbeite montags.'],['heute','Heute habe ich frei.'],['morgen','Bis morgen.'],['Uhrzeit','Um wie viel Uhr ist die Besprechung?'],['früh','Ich stehe früh auf.'],['zu spät','Ich komme zu spät.']],
 [['glücklich','Ich bin glücklich.'],['traurig','Heute bin ich traurig.'],['wütend','Ich bin wütend.'],['begeistert','Ich bin begeistert.'],['besorgt','Ich bin besorgt.'],['ruhig','Ich fühle mich ruhig.']],
 [['wollen','Ich möchte lernen.'],['besuchen','Ich möchte Deutschland besuchen.'],['lernen','Ich möchte Deutsch lernen.'],['gehen','Ich möchte nach Hause gehen.'],['reisen','Ich reise gern.'],['bleiben','Ich möchte hier bleiben.']],
 [['Hilfe','Ich brauche Hilfe.'],['wiederholen','Kannst du das wiederholen?'],['langsam','Sprich bitte langsam.'],['verstehen','Ich verstehe nicht.'],['Entschuldigung','Entschuldigung, ich verstehe nicht.'],['bitte','Hilf mir bitte.']],
 [['willkommen','Willkommen in meinem Haus.'],['danke','Danke für deine Hilfe.'],['auf Wiedersehen','Auf Wiedersehen, bis bald.'],['Party','Die Party ist am Freitag.'],['Geburtstag','Alles Gute zum Geburtstag, Ana.'],['zusammen','Wir lernen zusammen.']]
 ],ja:[
 [['名前','私はアナです。'],['こんにちは','こんにちは、レオです。'],['ブラジル','ブラジル出身です。'],['日本語','日本語を話します。'],['友達','こちらは私の友達です。'],['会う','お会いできてうれしいです。']],
 [['年齢','私は二十歳です。'],['電話','これは私の電話です。'],['メール','メールアドレスは何ですか。'],['住所','これは私の住所です。'],['名字','私の名字はシルバです。'],['国籍','私の国籍はブラジルです。']],
 [['母','こちらは私の母です。'],['父','父はここにいます。'],['姉','姉が一人います。'],['弟','弟は十歳です。'],['両親','両親はここに住んでいます。'],['家族','家族が大好きです。']],
 [['家','これは私の家です。'],['部屋','私の部屋は小さいです。'],['台所','台所はきれいです。'],['ドア','ドアは開いています。'],['窓','窓を閉めてください。'],['ベッド','ベッドは新しいです。']],
 [['朝','朝に勉強します。'],['朝食','七時に朝食を食べます。'],['仕事','毎日働きます。'],['昼食','正午に昼食を食べます。'],['夜','夜に本を読みます。'],['寝る','寝たいです。']],
 [['コーヒー','コーヒーを一杯お願いします。'],['お茶','お茶をお願いします。'],['牛乳','牛乳入りのコーヒーをお願いします。'],['砂糖','砂糖なしでお願いします。'],['カップ','カップを一つお願いします。'],['会計','お会計をお願いします。']],
 [['パン','パンを食べます。'],['ご飯','ご飯が好きです。'],['水','水を飲みます。'],['りんご','このりんごは赤いです。'],['鶏肉','鶏肉をお願いします。'],['野菜','野菜を食べます。']],
 [['値段','値段はいくらですか。'],['買う','これを買いたいです。'],['現金','現金で払います。'],['カード','カードで払えますか。'],['袋','袋が必要です。'],['お釣り','こちらがお釣りです。']],
 [['通り','この通りは長いです。'],['銀行','銀行はどこですか。'],['公園','公園は近くにあります。'],['左','左に曲がってください。'],['右','右に曲がってください。'],['駅','駅はあそこです。']],
 [['切符','切符が必要です。'],['パスポート','こちらが私のパスポートです。'],['空港','空港は大きいです。'],['便','私の便は六時に出発します。'],['荷物','これは私の荷物です。'],['地図','地図を持っています。']],
 [['予約','予約しています。'],['鍵','こちらが鍵です。'],['二泊','二泊予約したいです。'],['浴室','浴室はどこですか。'],['階','私の部屋はこの階です。'],['タオル','タオルが必要です。']],
 [['バス','バスに乗ります。'],['電車','電車はここにあります。'],['タクシー','タクシーが必要です。'],['車','これは私の車です。'],['自転車','自転車で行きます。'],['停留所','停留所はどこですか。']],
 [['晴れ','今日は晴れです。'],['雨','雨が好きです。'],['寒い','ここは寒いです。'],['暑い','今日は暑いです。'],['風','風は強いです。'],['天気','いい天気です。']],
 [['シャツ','このシャツは青いです。'],['靴','私の靴は新しいです。'],['サイズ','これは何サイズですか。'],['コート','コートが必要です。'],['ワンピース','このワンピースは赤いです。'],['帽子','あなたの帽子が好きです。']],
 [['仕事','新しい仕事があります。'],['事務所','私の事務所は小さいです。'],['上司','こちらは私の上司です。'],['会議','会議は二時です。'],['机','私の机はここです。'],['チーム','私のチームが好きです。']],
 [['学校','私の学校は近くにあります。'],['先生','私の先生は親切です。'],['本','これは私の本です。'],['鉛筆','鉛筆が必要です。'],['授業','授業は簡単です。'],['質問','質問があります。']],
 [['音楽','音楽が好きです。'],['映画','この映画はいいです。'],['読む','本を読みたいです。'],['踊る','踊るのが好きです。'],['ゲーム','このゲームは楽しいです。'],['週末','週末に休みます。']],
 [['サッカー','サッカーをします。'],['泳ぐ','泳ぐのが好きです。'],['走る','公園で走りたいです。'],['歩く','歩くのが好きです。'],['ボール','ボールはここです。'],['テニス','テニスをします。']],
 [['頭','頭が痛いです。'],['疲れた','疲れています。'],['医者','医者が必要です。'],['休む','休みたいです。'],['元気','今日は元気です。'],['予約','予約があります。']],
 [['パソコン','私のパソコンは新しいです。'],['パスワード','パスワードが必要です。'],['画面','画面は大きいです。'],['メッセージ','メッセージがあります。'],['インターネット','インターネットは遅いです。'],['写真','この写真はきれいです。']],
 [['月曜日','月曜日に働きます。'],['今日','今日は暇です。'],['明日','また明日。'],['時間','会議は何時ですか。'],['早い','早く起きます。'],['遅刻','遅刻します。']],
 [['うれしい','うれしいです。'],['悲しい','今日は悲しいです。'],['怒る','怒っています。'],['楽しみ','楽しみです。'],['心配','心配しています。'],['落ち着く','落ち着いています。']],
 [['したい','勉強したいです。'],['訪れる','日本を訪れたいです。'],['学ぶ','日本語を学びたいです。'],['行く','家に帰りたいです。'],['旅行','旅行が好きです。'],['滞在','ここに滞在したいです。']],
 [['助け','助けが必要です。'],['繰り返す','もう一度言ってもらえますか。'],['ゆっくり','ゆっくり話してください。'],['分かる','分かりません。'],['すみません','すみません、分かりません。'],['お願いします','助けてください。']],
 [['ようこそ','私の家へようこそ。'],['ありがとう','助けてくれてありがとう。'],['さようなら','さようなら、また会いましょう。'],['パーティー','パーティーは金曜日です。'],['誕生日','アナさん、お誕生日おめでとう。'],['一緒','一緒に勉強します。']]
 ],ko:[
 [['이름','제 이름은 아나예요.'],['안녕하세요','안녕하세요, 저는 레오예요.'],['브라질','저는 브라질에서 왔어요.'],['한국어','저는 한국어를 말해요.'],['친구','이 사람은 제 친구예요.'],['만나다','만나서 반가워요.']],
 [['나이','저는 스무 살이에요.'],['전화','이것은 제 전화예요.'],['이메일','이메일 주소가 뭐예요?'],['주소','이것은 제 주소예요.'],['성','제 성은 실바예요.'],['국적','제 국적은 브라질이에요.']],
 [['어머니','이분은 제 어머니예요.'],['아버지','아버지는 여기 계세요.'],['여동생','저는 여동생이 있어요.'],['남동생','제 남동생은 열 살이에요.'],['부모님','부모님은 여기 사세요.'],['가족','저는 가족을 사랑해요.']],
 [['집','이것은 제 집이에요.'],['방','제 방은 작아요.'],['부엌','부엌은 깨끗해요.'],['문','문이 열려 있어요.'],['창문','창문을 닫아 주세요.'],['침대','침대는 새것이에요.']],
 [['아침','아침에 공부해요.'],['아침 식사','일곱 시에 아침 식사를 해요.'],['일','매일 일해요.'],['점심','정오에 점심을 먹어요.'],['밤','밤에 책을 읽어요.'],['자다','자고 싶어요.']],
 [['커피','커피 한 잔 주세요.'],['차','차 한 잔 주세요.'],['우유','우유를 넣은 커피 주세요.'],['설탕','설탕 없이 주세요.'],['컵','컵 하나 주세요.'],['계산서','계산서 주세요.']],
 [['빵','빵을 먹어요.'],['밥','밥을 좋아해요.'],['물','물을 마셔요.'],['사과','이 사과는 빨개요.'],['닭고기','닭고기 주세요.'],['채소','채소를 먹어요.']],
 [['가격','가격이 얼마예요?'],['사다','이것을 사고 싶어요.'],['현금','현금으로 내요.'],['카드','카드로 내도 돼요?'],['봉투','봉투가 필요해요.'],['거스름돈','여기 거스름돈이 있어요.']],
 [['거리','이 거리는 길어요.'],['은행','은행이 어디에 있어요?'],['공원','공원은 가까워요.'],['왼쪽','왼쪽으로 도세요.'],['오른쪽','오른쪽으로 도세요.'],['역','역은 저기에 있어요.']],
 [['표','표가 필요해요.'],['여권','여기 제 여권이 있어요.'],['공항','공항은 커요.'],['항공편','제 항공편은 여섯 시에 출발해요.'],['짐','이것은 제 짐이에요.'],['지도','지도가 있어요.']],
 [['예약','예약했어요.'],['열쇠','여기 열쇠가 있어요.'],['이틀 숙박','이틀 숙박을 예약하고 싶어요.'],['욕실','욕실이 어디에 있어요?'],['층','제 방은 이 층에 있어요.'],['수건','수건이 필요해요.']],
 [['버스','버스를 타요.'],['기차','기차는 여기에 있어요.'],['택시','택시가 필요해요.'],['자동차','이것은 제 자동차예요.'],['자전거','자전거로 가요.'],['정류장','정류장이 어디에 있어요?']],
 [['해','오늘은 해가 나요.'],['비','비를 좋아해요.'],['춥다','여기는 추워요.'],['덥다','오늘은 더워요.'],['바람','바람이 세요.'],['날씨','날씨가 좋아요.']],
 [['셔츠','이 셔츠는 파란색이에요.'],['신발','제 신발은 새것이에요.'],['사이즈','무슨 사이즈예요?'],['코트','코트가 필요해요.'],['원피스','이 원피스는 빨간색이에요.'],['모자','당신의 모자가 좋아요.']],
 [['직장','새 직장이 생겼어요.'],['사무실','제 사무실은 작아요.'],['상사','이분은 제 상사예요.'],['회의','회의는 두 시예요.'],['책상','제 책상은 여기에 있어요.'],['팀','제 팀을 좋아해요.']],
 [['학교','제 학교는 가까워요.'],['선생님','제 선생님은 친절해요.'],['책','이것은 제 책이에요.'],['연필','연필이 필요해요.'],['수업','수업은 쉬워요.'],['질문','질문이 있어요.']],
 [['음악','음악을 좋아해요.'],['영화','이 영화는 좋아요.'],['읽다','책을 읽고 싶어요.'],['춤추다','춤추는 것을 좋아해요.'],['게임','이 게임은 재미있어요.'],['주말','주말에 쉬어요.']],
 [['축구','축구를 해요.'],['수영','수영을 좋아해요.'],['달리다','공원에서 달리고 싶어요.'],['걷다','걷는 것을 좋아해요.'],['공','공은 여기에 있어요.'],['테니스','테니스를 해요.']],
 [['머리','머리가 아파요.'],['피곤하다','피곤해요.'],['의사','의사가 필요해요.'],['쉬다','쉬고 싶어요.'],['잘','오늘은 기분이 좋아요.'],['진료 예약','진료 예약이 있어요.']],
 [['컴퓨터','제 컴퓨터는 새것이에요.'],['비밀번호','비밀번호가 필요해요.'],['화면','화면은 커요.'],['메시지','메시지가 있어요.'],['인터넷','인터넷은 느려요.'],['사진','이 사진은 예뻐요.']],
 [['월요일','월요일에 일해요.'],['오늘','오늘은 시간이 있어요.'],['내일','내일 봐요.'],['시간','회의는 몇 시예요?'],['일찍','일찍 일어나요.'],['늦다','늦었어요.']],
 [['행복하다','행복해요.'],['슬프다','오늘은 슬퍼요.'],['화나다','화가 났어요.'],['신나다','신나요.'],['걱정하다','걱정하고 있어요.'],['차분하다','마음이 차분해요.']],
 [['원하다','공부하고 싶어요.'],['방문하다','한국을 방문하고 싶어요.'],['배우다','한국어를 배우고 싶어요.'],['가다','집에 가고 싶어요.'],['여행','여행을 좋아해요.'],['머무르다','여기에 머무르고 싶어요.']],
 [['도움','도움이 필요해요.'],['반복하다','다시 말해 줄 수 있어요?'],['천천히','천천히 말해 주세요.'],['이해하다','이해하지 못해요.'],['죄송하다','죄송하지만 이해하지 못해요.'],['부탁하다','도와주세요.']],
 [['환영하다','우리 집에 오신 것을 환영해요.'],['감사하다','도와주셔서 감사해요.'],['안녕히 가세요','안녕히 가세요, 또 만나요.'],['파티','파티는 금요일이에요.'],['생일','아나 씨, 생일 축하해요.'],['함께','함께 공부해요.']]
 ],zh:[
 [['名字','我叫安娜。'],['你好','你好，我是里奥。'],['巴西','我来自巴西。'],['中文','我会说中文。'],['朋友','这是我的朋友。'],['认识','很高兴认识你。']],
 [['年龄','我二十岁。'],['电话','这是我的电话。'],['电子邮件','你的电子邮件地址是什么？'],['地址','这是我的地址。'],['姓','我姓席尔瓦。'],['国籍','我的国籍是巴西。']],
 [['妈妈','这是我妈妈。'],['爸爸','我爸爸在这里。'],['妹妹','我有一个妹妹。'],['弟弟','我弟弟十岁。'],['父母','我父母住在这里。'],['家庭','我爱我的家庭。']],
 [['房子','这是我的房子。'],['房间','我的房间很小。'],['厨房','厨房很干净。'],['门','门开着。'],['窗户','请关窗户。'],['床','这张床是新的。']],
 [['早上','我早上学习。'],['早餐','我七点吃早餐。'],['工作','我每天工作。'],['午餐','我中午吃午餐。'],['晚上','我晚上看书。'],['睡觉','我想睡觉。']],
 [['咖啡','我想要一杯咖啡。'],['茶','请给我一杯茶。'],['牛奶','请给我加牛奶的咖啡。'],['糖','请不要加糖。'],['杯子','请给我一个杯子。'],['账单','请给我账单。']],
 [['面包','我吃面包。'],['米饭','我喜欢米饭。'],['水','我喝水。'],['苹果','这个苹果是红色的。'],['鸡肉','我想要鸡肉。'],['蔬菜','我吃蔬菜。']],
 [['价格','价格是多少？'],['买','我想买这个。'],['现金','我用现金付款。'],['银行卡','可以用银行卡付款吗？'],['袋子','我需要一个袋子。'],['零钱','这是你的零钱。']],
 [['街道','这条街道很长。'],['银行','银行在哪里？'],['公园','公园很近。'],['左边','请向左转。'],['右边','请向右转。'],['车站','车站在那里。']],
 [['票','我需要一张票。'],['护照','这是我的护照。'],['机场','机场很大。'],['航班','我的航班六点起飞。'],['行李','这是我的行李。'],['地图','我有一张地图。']],
 [['预订','我已经预订了。'],['钥匙','这是钥匙。'],['两晚','我想预订两晚。'],['浴室','浴室在哪里？'],['楼层','我的房间在这个楼层。'],['毛巾','我需要一条毛巾。']],
 [['公交车','我坐公交车。'],['火车','火车在这里。'],['出租车','我需要一辆出租车。'],['汽车','这是我的汽车。'],['自行车','我骑自行车去。'],['车站','车站在哪里？']],
 [['太阳','今天有太阳。'],['雨','我喜欢下雨。'],['冷','这里很冷。'],['热','今天很热。'],['风','风很大。'],['天气','天气很好。']],
 [['衬衫','这件衬衫是蓝色的。'],['鞋','我的鞋是新的。'],['尺码','这是什么尺码？'],['大衣','我需要一件大衣。'],['连衣裙','这件连衣裙是红色的。'],['帽子','我喜欢你的帽子。']],
 [['工作','我有一份新工作。'],['办公室','我的办公室很小。'],['经理','这是我的经理。'],['会议','会议在两点。'],['书桌','我的书桌在这里。'],['团队','我喜欢我的团队。']],
 [['学校','我的学校很近。'],['老师','我的老师很友好。'],['书','这是我的书。'],['铅笔','我需要一支铅笔。'],['课','这节课很简单。'],['问题','我有一个问题。']],
 [['音乐','我喜欢音乐。'],['电影','这部电影很好。'],['读','我想读书。'],['跳舞','我喜欢跳舞。'],['游戏','这个游戏很有趣。'],['周末','我周末休息。']],
 [['足球','我踢足球。'],['游泳','我喜欢游泳。'],['跑步','我想在公园跑步。'],['走路','我喜欢走路。'],['球','球在这里。'],['网球','我打网球。']],
 [['头','我的头疼。'],['累','我很累。'],['医生','我需要医生。'],['休息','我想休息。'],['好','我今天感觉很好。'],['预约','我有一个预约。']],
 [['电脑','我的电脑是新的。'],['密码','我需要密码。'],['屏幕','屏幕很大。'],['消息','我有一条消息。'],['互联网','互联网很慢。'],['照片','这张照片很漂亮。']],
 [['星期一','我星期一工作。'],['今天','我今天有空。'],['明天','明天见。'],['时间','会议几点开始？'],['早','我起得早。'],['迟到','我迟到了。']],
 [['开心','我很开心。'],['难过','我今天很难过。'],['生气','我生气了。'],['兴奋','我很兴奋。'],['担心','我很担心。'],['平静','我感觉很平静。']],
 [['想','我想学习。'],['参观','我想去中国。'],['学','我想学中文。'],['去','我想回家。'],['旅行','我喜欢旅行。'],['留下','我想留在这里。']],
 [['帮助','我需要帮助。'],['重复','你能再说一遍吗？'],['慢慢','请慢慢说。'],['理解','我不理解。'],['对不起','对不起，我不理解。'],['请','请帮帮我。']],
 [['欢迎','欢迎来我家。'],['谢谢','谢谢你的帮助。'],['再见','再见，回头见。'],['聚会','聚会在星期五。'],['生日','安娜，生日快乐。'],['一起','我们一起学习。']]
 ]};
 const metadata={de:{name:'alemão',country:'a Alemanha',opening:'Hallo! Lass uns Deutsch üben.',frames:['In dieser Situation kann ich sagen: „','Um meine Erfahrung zu erklären, habe ich diesen Ausdruck gewählt: „','Obwohl es andere Möglichkeiten gibt, halte ich diese Formulierung für passend: „','Ohne die Nuancen des Kontexts zu vernachlässigen, wäre Folgendes zu präzisieren: „','Auch wenn ihre Tragweite unterschiedliche Deutungen zulassen mag, bietet sich folgende Lesart an: „']},ja:{name:'japonês',country:'o Japão',opening:'こんにちは。日本語を練習しましょう。',frames:['この場面では、次のように言えます。「','自分の経験を説明するために、この表現を選びました。「','ほかの選択肢もありますが、この表現が適切だと思います。「','文脈の微妙な違いを考慮すると、次のように明確にする必要があります。「','解釈が分かれる可能性はあるものの、この表現は次のように読むことができます。「']},ko:{name:'coreano',country:'a Coreia do Sul',opening:'안녕하세요. 한국어를 연습해요.',frames:['이 상황에서는 이렇게 말할 수 있어요. “','제 경험을 설명하기 위해 이 표현을 선택했어요. “','다른 선택지도 있지만 이 표현이 적절하다고 생각해요. “','맥락의 미묘한 차이를 고려하면 다음과 같이 명확히 할 필요가 있습니다. “','해석이 달라질 여지가 있더라도 이 표현은 다음과 같이 이해할 수 있습니다. “']},zh:{name:'mandarim',country:'a China',opening:'你好！我们一起练习中文吧。',frames:['在这种情况下，我可以这样说：“','为了解释我的经历，我选择了这个表达：“','虽然还有其他选择，但我认为这种表述很合适：“','考虑到语境中的细微差别，有必要进一步明确如下：“','尽管其含义可能引发不同解读，这种表述仍可以作如下理解：“']}};
 const prefixes=['Nesta situação posso dizer: “','Para explicar minha experiência, escolhi esta expressão: “','Embora existam outras opções, considero adequada esta formulação: “','Sem desconsiderar as nuances do contexto, seria conveniente precisar o seguinte: “','Ainda que possa dar margem a interpretações diferentes, esta formulação permite a seguinte leitura: “'];
 function build(language){const meta=metadata[language],levels=Spanish.levels;const baseRows=Spanish.lessons.filter(l=>l.level==='A1');function sentence(g,i){let pt=baseRows[g*6+i].example.pt;if(g===0&&i===3)pt=`Falo ${meta.name}.`;if(g===22&&i===1)pt=`Quero visitar ${meta.country}.`;if(g===22&&i===2)pt=`Quero aprender ${meta.name}.`;if(g===10&&i===2)pt='Quero reservar duas noites.';return pt;}const lessons=Spanish.lessons.map(base=>{const g=Math.floor((base.number-1)/6),i=(base.number-1)%6,[word,text]=rows[language][g][i],advanced=levels.indexOf(base.level)-1,closing=language==='ja'?'」':'”';const en=advanced<0?text:meta.frames[advanced]+text+closing,pt=advanced<0?sentence(g,i):prefixes[advanced]+sentence(g,i)+'”';const vocabulary=rows[language][g].map(([en],j)=>({en,pt:g===0&&j===3?meta.name:baseRows[g*6+j].vocabulary[j].pt}));vocabulary.push({en,pt});const meaning=vocabulary[i].pt,options=[meaning,vocabulary[(i+1)%6].pt,vocabulary[(i+2)%6].pt],shift=base.number%3;const translated=j=>advanced<0?sentence(g,j):prefixes[advanced]+sentence(g,j)+'”';return{...base,language,title:`${base.topic}: ${word}`,objective:base.objective.replace(/espanhol/g,meta.name).replace(base.title.split(': ')[1],word),vocabulary,example:{en,pt},conversation:{...base.conversation,opening:meta.opening,prompt:`Pratique o tema ${base.topic} em ${meta.name} ${base.level}. Use «${word}» e responda a uma pergunta por vez.`,instructions:base.conversation.instructions.replace(/espanhol/g,meta.name)},questions:[{prompt:`O que significa «${word}»?`,options:[...options.slice(shift),...options.slice(0,shift)],answer:(3-shift)%3,explanation:`${word} — ${meaning}`},{prompt:`Qual tradução corresponde a «${en}»?`,options:[translated((i+1)%6),pt,translated((i+2)%6)],answer:1,explanation:pt}]};});return{levels,lessons,get:id=>lessons.find(l=>l.id===id)};}
 const api=Object.fromEntries(Object.keys(rows).map(code=>[code,build(code)]));root.StudyGlobalCourses=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
