'use strict';
(function(root){
 const groups=[
 ['Apresentações',[['nombre','nome','Me llamo Ana.','Meu nome é Ana.'],['hola','olá','Hola, soy Leo.','Olá, sou Leo.'],['Brasil','Brasil','Soy de Brasil.','Sou do Brasil.'],['español','espanhol','Hablo español.','Falo espanhol.'],['amigo','amigo','Este es mi amigo.','Este é meu amigo.'],['conocer','conhecer','Encantado de conocerte.','Prazer em conhecer você.']]],
 ['Dados pessoais',[['edad','idade','Tengo veinte años.','Tenho vinte anos.'],['teléfono','telefone','Este es mi teléfono.','Este é meu telefone.'],['correo','e-mail','¿Cuál es tu correo?','Qual é seu e-mail?'],['dirección','endereço','Esta es mi dirección.','Este é meu endereço.'],['apellido','sobrenome','Mi apellido es Silva.','Meu sobrenome é Silva.'],['nacionalidad','nacionalidade','Mi nacionalidad es brasileña.','Minha nacionalidade é brasileira.']]],
 ['Família',[['madre','mãe','Esta es mi madre.','Esta é minha mãe.'],['padre','pai','Mi padre está aquí.','Meu pai está aqui.'],['hermana','irmã','Tengo una hermana.','Tenho uma irmã.'],['hermano','irmão','Mi hermano tiene diez años.','Meu irmão tem dez anos.'],['padres','pais','Mis padres viven aquí.','Meus pais moram aqui.'],['familia','família','Quiero a mi familia.','Amo minha família.']]],
 ['Casa',[['casa','casa','Esta es mi casa.','Esta é minha casa.'],['habitación','quarto','Mi habitación es pequeña.','Meu quarto é pequeno.'],['cocina','cozinha','La cocina está limpia.','A cozinha está limpa.'],['puerta','porta','La puerta está abierta.','A porta está aberta.'],['ventana','janela','Cierra la ventana, por favor.','Feche a janela, por favor.'],['cama','cama','La cama es nueva.','A cama é nova.']]],
 ['Rotina',[['mañana','manhã','Estudio por la mañana.','Estudo de manhã.'],['desayuno','café da manhã','Desayuno a las siete.','Tomo café da manhã às sete.'],['trabajo','trabalho','Trabajo todos los días.','Trabalho todos os dias.'],['almuerzo','almoço','Almuerzo al mediodía.','Almoço ao meio-dia.'],['noche','noite','Leo por la noche.','Leio à noite.'],['dormir','dormir','Quiero dormir.','Quero dormir.']]],
 ['Cafeteria',[['café','café','Quisiera un café.','Gostaria de um café.'],['té','chá','Un té, por favor.','Um chá, por favor.'],['leche','leite','Café con leche, por favor.','Café com leite, por favor.'],['azúcar','açúcar','Sin azúcar, por favor.','Sem açúcar, por favor.'],['taza','xícara','Una taza, por favor.','Uma xícara, por favor.'],['cuenta','conta','La cuenta, por favor.','A conta, por favor.']]],
 ['Alimentação',[['pan','pão','Como pan.','Como pão.'],['arroz','arroz','Me gusta el arroz.','Gosto de arroz.'],['agua','água','Bebo agua.','Bebo água.'],['manzana','maçã','Esta manzana es roja.','Esta maçã é vermelha.'],['pollo','frango','Quisiera pollo.','Gostaria de frango.'],['verduras','verduras','Como verduras.','Como verduras.']]],
 ['Compras',[['precio','preço','¿Cuál es el precio?','Qual é o preço?'],['comprar','comprar','Quiero comprar esto.','Quero comprar isto.'],['efectivo','dinheiro em espécie','Pago en efectivo.','Pago em dinheiro.'],['tarjeta','cartão','¿Puedo pagar con tarjeta?','Posso pagar com cartão?'],['bolsa','sacola','Necesito una bolsa.','Preciso de uma sacola.'],['cambio','troco','Aquí tienes el cambio.','Aqui está o troco.']]],
 ['Cidade',[['calle','rua','Esta calle es larga.','Esta rua é longa.'],['banco','banco','¿Dónde está el banco?','Onde fica o banco?'],['parque','parque','El parque está cerca.','O parque fica perto.'],['izquierda','esquerda','Gira a la izquierda.','Vire à esquerda.'],['derecha','direita','Gira a la derecha.','Vire à direita.'],['estación','estação','La estación está allí.','A estação fica ali.']]],
 ['Viagens',[['billete','passagem','Necesito un billete.','Preciso de uma passagem.'],['pasaporte','passaporte','Aquí está mi pasaporte.','Aqui está meu passaporte.'],['aeropuerto','aeroporto','El aeropuerto es grande.','O aeroporto é grande.'],['vuelo','voo','Mi vuelo sale a las seis.','Meu voo sai às seis.'],['equipaje','bagagem','Este es mi equipaje.','Esta é minha bagagem.'],['mapa','mapa','Tengo un mapa.','Tenho um mapa.']]],
 ['Hotel',[['reserva','reserva','Tengo una reserva.','Tenho uma reserva.'],['llave','chave','Aquí está la llave.','Aqui está a chave.'],['noches','noites','Quiero reservar dos noches.','Quero reservar duas noites.'],['baño','banheiro','¿Dónde está el baño?','Onde fica o banheiro?'],['piso','andar','Mi habitación está en este piso.','Meu quarto fica neste andar.'],['toalla','toalha','Necesito una toalla.','Preciso de uma toalha.']]],
 ['Transporte',[['autobús','ônibus','Tomo el autobús.','Pego o ônibus.'],['tren','trem','El tren está aquí.','O trem está aqui.'],['taxi','táxi','Necesito un taxi.','Preciso de um táxi.'],['coche','carro','Este es mi coche.','Este é meu carro.'],['bicicleta','bicicleta','Voy en bicicleta.','Vou de bicicleta.'],['parada','parada','¿Dónde está la parada?','Onde fica a parada?']]],
 ['Clima',[['sol','sol','Hoy hace sol.','Hoje faz sol.'],['lluvia','chuva','Me gusta la lluvia.','Gosto da chuva.'],['frío','frio','Aquí hace frío.','Aqui faz frio.'],['calor','calor','Hoy hace calor.','Hoje faz calor.'],['viento','vento','El viento es fuerte.','O vento é forte.'],['tiempo','tempo','Hace buen tiempo.','O tempo está bom.']]],
 ['Roupas',[['camisa','camisa','Esta camisa es azul.','Esta camisa é azul.'],['zapatos','sapatos','Mis zapatos son nuevos.','Meus sapatos são novos.'],['talla','tamanho de roupa','¿Qué talla es?','Qual é o tamanho?'],['abrigo','casaco','Necesito un abrigo.','Preciso de um casaco.'],['vestido','vestido','Este vestido es rojo.','Este vestido é vermelho.'],['sombrero','chapéu','Me gusta tu sombrero.','Gosto do seu chapéu.']]],
 ['Trabalho',[['empleo','emprego','Tengo un empleo nuevo.','Tenho um emprego novo.'],['oficina','escritório','Mi oficina es pequeña.','Meu escritório é pequeno.'],['gerente','gerente','Esta es mi gerente.','Esta é minha gerente.'],['reunión','reunião','La reunión es a las dos.','A reunião é às duas.'],['escritorio','mesa de trabalho','Mi escritorio está aquí.','Minha mesa fica aqui.'],['equipo','equipe','Me gusta mi equipo.','Gosto da minha equipe.']]],
 ['Estudos',[['escuela','escola','Mi escuela está cerca.','Minha escola fica perto.'],['profesor','professor','Mi profesor es amable.','Meu professor é gentil.'],['libro','livro','Este es mi libro.','Este é meu livro.'],['lápiz','lápis','Necesito un lápiz.','Preciso de um lápis.'],['lección','aula','La lección es fácil.','A aula é fácil.'],['pregunta','pergunta','Tengo una pregunta.','Tenho uma pergunta.']]],
 ['Lazer',[['música','música','Me gusta la música.','Gosto de música.'],['película','filme','Esta película es buena.','Este filme é bom.'],['leer','ler','Quiero leer.','Quero ler.'],['bailar','dançar','Me gusta bailar.','Gosto de dançar.'],['juego','jogo','Este juego es divertido.','Este jogo é divertido.'],['fin de semana','fim de semana','Descanso el fin de semana.','Descanso no fim de semana.']]],
 ['Esportes',[['fútbol','futebol','Juego al fútbol.','Jogo futebol.'],['nadar','nadar','Me gusta nadar.','Gosto de nadar.'],['correr','correr','Quiero correr en el parque.','Quero correr no parque.'],['caminar','caminhar','Me gusta caminar.','Gosto de caminhar.'],['pelota','bola','La pelota está aquí.','A bola está aqui.'],['tenis','tênis','Juego al tenis.','Jogo tênis.']]],
 ['Bem-estar',[['cabeza','cabeça','Me duele la cabeza.','Minha cabeça dói.'],['cansado','cansado','Estoy cansado.','Estou cansado.'],['médico','médico','Necesito un médico.','Preciso de um médico.'],['descansar','descansar','Quiero descansar.','Quero descansar.'],['bien','bem','Hoy me siento bien.','Hoje me sinto bem.'],['cita','consulta','Tengo una cita.','Tenho uma consulta.']]],
 ['Tecnologia',[['ordenador','computador','Mi ordenador es nuevo.','Meu computador é novo.'],['contraseña','senha','Necesito una contraseña.','Preciso de uma senha.'],['pantalla','tela','La pantalla es grande.','A tela é grande.'],['mensaje','mensagem','Tengo un mensaje.','Tenho uma mensagem.'],['internet','internet','Internet es lento.','A internet está lenta.'],['foto','foto','Esta foto es bonita.','Esta foto é bonita.']]],
 ['Agenda',[['lunes','segunda-feira','Trabajo los lunes.','Trabalho às segundas-feiras.'],['hoy','hoje','Hoy estoy libre.','Hoje estou livre.'],['mañana','amanhã','Hasta mañana.','Até amanhã.'],['hora','hora','¿A qué hora es la reunión?','A que horas é a reunião?'],['temprano','cedo','Me levanto temprano.','Acordo cedo.'],['tarde','atrasado','Llego tarde.','Chego atrasado.']]],
 ['Sentimentos',[['feliz','feliz','Estoy feliz.','Estou feliz.'],['triste','triste','Hoy me siento triste.','Hoje me sinto triste.'],['enfadado','com raiva','Estoy enfadado.','Estou com raiva.'],['emocionado','animado','Estoy emocionado.','Estou animado.'],['preocupado','preocupado','Estoy preocupado.','Estou preocupado.'],['tranquilo','tranquilo','Me siento tranquilo.','Sinto-me tranquilo.']]],
 ['Planos',[['querer','querer','Quiero estudiar.','Quero estudar.'],['visitar','visitar','Quiero visitar España.','Quero visitar a Espanha.'],['aprender','aprender','Quiero aprender español.','Quero aprender espanhol.'],['ir','ir','Quiero ir a casa.','Quero ir para casa.'],['viajar','viajar','Me gusta viajar.','Gosto de viajar.'],['quedarse','ficar','Quiero quedarme aquí.','Quero ficar aqui.']]],
 ['Pedir ajuda',[['ayuda','ajuda','Necesito ayuda.','Preciso de ajuda.'],['repetir','repetir','¿Puedes repetirlo?','Você pode repetir?'],['despacio','devagar','Habla despacio, por favor.','Fale devagar, por favor.'],['entender','entender','No entiendo.','Não entendo.'],['perdón','desculpa','Perdón, no entiendo.','Desculpe, não entendo.'],['por favor','por favor','Ayúdame, por favor.','Ajude-me, por favor.']]],
 ['Encontros',[['bienvenido','bem-vindo','Bienvenido a mi casa.','Bem-vindo à minha casa.'],['gracias','obrigado','Gracias por tu ayuda.','Obrigado pela sua ajuda.'],['adiós','adeus','Adiós, hasta pronto.','Adeus, até logo.'],['fiesta','festa','La fiesta es el viernes.','A festa é na sexta-feira.'],['cumpleaños','aniversário','Feliz cumpleaños, Ana.','Feliz aniversário, Ana.'],['juntos','juntos','Estudiamos juntos.','Estudamos juntos.']]]
 ];
 const levels=['A1','A2','B1','B2','C1','C2'];
 const tasks={A1:'Responda com uma frase simples e uma informação pessoal.',A2:'Troque informações e faça uma pergunta usando passado ou planos futuros.',B1:'Relate uma experiência, explique um motivo e responda a uma pergunta de acompanhamento.',B2:'Defenda uma opinião, apresente um contraponto e negocie uma solução.',C1:'Reconheça uma ressalva, sintetize perspectivas e ajuste o registro para dois públicos.',C2:'Interprete sentidos implícitos, preserve nuances e reformule uma posição com precisão.'};
 const frames={A2:['En esta situación puedo decir: «','Nesta situação posso dizer: “'],B1:['Para explicar mi experiencia, elegí esta expresión: «','Para explicar minha experiência, escolhi esta expressão: “'],B2:['Aunque existen otras opciones, considero adecuada esta formulación: «','Embora existam outras opções, considero adequada esta formulação: “'],C1:['Sin perjuicio de los matices del contexto, convendría precisar lo siguiente: «','Sem desconsiderar as nuances do contexto, seria conveniente precisar o seguinte: “'],C2:['Aun cuando su alcance pudiera prestarse a interpretaciones divergentes, la formulación admite esta lectura: «','Ainda que seu alcance pudesse dar margem a interpretações divergentes, a formulação admite esta leitura: “']};
 const lessons=levels.flatMap(level=>groups.flatMap(([topic,entries],g)=>entries.map(([word,pt,example,translation],i)=>{const number=g*6+i+1;const en=level==='A1'?example:frames[level][0]+example+'»';const meaning=level==='A1'?translation:frames[level][1]+translation+'”';const options=[pt,entries[(i+1)%6][1],entries[(i+2)%6][1]],shift=number%3;const translated=entries.map(e=>level==='A1'?e[3]:frames[level][1]+e[3]+'”');return{id:`${level}-${String(number).padStart(3,'0')}`,language:'es',level,number,title:`${topic}: ${word}`,topic,objective:`Praticar ${word} em espanhol ${level}. ${tasks[level]}`,vocabulary:[...entries.map(([en,pt])=>({en,pt})),{en,pt:meaning}],example:{en,pt:meaning},conversation:{opening:'¡Hola! Practiquemos español.',prompt:tasks[level]+` Tema: ${topic}. Use «${word}».`,instructions:`Ensine espanhol ${level} para brasileiros. ${tasks[level]} Tema: ${topic}. Corrija um erro relevante por vez; explique em português quando necessário.`},questions:[{prompt:`O que significa «${word}»?`,options:[...options.slice(shift),...options.slice(0,shift)],answer:(3-shift)%3,explanation:`${word} — ${pt}`},{prompt:`Qual tradução corresponde a «${en}»?`,options:[translated[(i+1)%6],meaning,translated[(i+2)%6]],answer:1,explanation:meaning}],status:'generated'};})));
 const api={levels,lessons,get:id=>lessons.find(l=>l.id===id)};root.StudySpanish=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
