'use strict';
(function(root){
 const levels=['A1','A2','B1','B2','C1','C2'];
 const topics=[
 ['Introduções', [['name','nome','My name is Ana.','Meu nome é Ana.'],['hello','olá','Hello, my name is Leo.','Olá, meu nome é Leo.'],['from','de / origem','I am from Brazil.','Eu sou do Brasil.'],['English','inglês','I speak English.','Eu falo inglês.'],['friend','amigo','This is my friend.','Este é meu amigo.'],['meet','conhecer','Nice to meet you.','Prazer em conhecer você.']]],
 ['Dados pessoais',[['age','idade','What is your age?','Qual é a sua idade?'],['phone','telefone','This is my phone number.','Este é meu número de telefone.'],['email','e-mail','What is your email?','Qual é o seu e-mail?'],['address','endereço','This is my address.','Este é meu endereço.'],['years','anos','I am twenty years old.','Eu tenho vinte anos.'],['last name','sobrenome','My last name is Silva.','Meu sobrenome é Silva.']]],
 ['Família',[['mother','mãe','This is my mother.','Esta é minha mãe.'],['father','pai','My father is here.','Meu pai está aqui.'],['sister','irmã','I have a sister.','Eu tenho uma irmã.'],['brother','irmão','My brother is ten.','Meu irmão tem dez anos.'],['parents','pais','My parents live here.','Meus pais moram aqui.'],['family','família','I love my family.','Eu amo minha família.']]],
 ['Casa',[['house','casa','This is my house.','Esta é minha casa.'],['room','quarto / cômodo','My room is small.','Meu quarto é pequeno.'],['kitchen','cozinha','The kitchen is clean.','A cozinha está limpa.'],['door','porta','The door is open.','A porta está aberta.'],['window','janela','Close the window, please.','Feche a janela, por favor.'],['bed','cama','The bed is new.','A cama é nova.']]],
 ['Rotina',[['morning','manhã','I study in the morning.','Eu estudo de manhã.'],['breakfast','café da manhã','I eat breakfast at seven.','Eu tomo café da manhã às sete.'],['work','trabalho / trabalhar','I work every day.','Eu trabalho todos os dias.'],['lunch','almoço','I have lunch at noon.','Eu almoço ao meio-dia.'],['evening','fim da tarde / noite','I read in the evening.','Eu leio à noite.'],['sleep','dormir','I sleep at ten.','Eu durmo às dez.']]],
 ['Cafeteria',[['coffee','café','I would like a coffee.','Eu gostaria de um café.'],['tea','chá','A tea, please.','Um chá, por favor.'],['milk','leite','Coffee with milk, please.','Café com leite, por favor.'],['sugar','açúcar','No sugar, please.','Sem açúcar, por favor.'],['cup','xícara','One cup, please.','Uma xícara, por favor.'],['bill','conta','The bill, please.','A conta, por favor.']]],
 ['Alimentação',[['bread','pão','I eat bread.','Eu como pão.'],['rice','arroz','I like rice.','Eu gosto de arroz.'],['water','água','I drink water.','Eu bebo água.'],['apple','maçã','This apple is red.','Esta maçã é vermelha.'],['chicken','frango','I would like chicken.','Eu gostaria de frango.'],['vegetables','vegetais','I eat vegetables.','Eu como vegetais.']]],
 ['Compras',[['price','preço','What is the price?','Qual é o preço?'],['buy','comprar','I want to buy this.','Eu quero comprar isto.'],['cash','dinheiro em espécie','I pay in cash.','Eu pago em dinheiro.'],['card','cartão','Can I pay by card?','Posso pagar com cartão?'],['bag','sacola / bolsa','I need a bag.','Eu preciso de uma sacola.'],['change','troco','Here is your change.','Aqui está seu troco.']]],
 ['Cidade',[['street','rua','This street is long.','Esta rua é longa.'],['bank','banco','Where is the bank?','Onde fica o banco?'],['park','parque','The park is near.','O parque é perto.'],['left','esquerda','Turn left, please.','Vire à esquerda, por favor.'],['right','direita','Turn right here.','Vire à direita aqui.'],['station','estação','The station is there.','A estação fica ali.']]],
 ['Viagens',[['ticket','passagem / ingresso','I need a ticket.','Eu preciso de uma passagem.'],['passport','passaporte','Here is my passport.','Aqui está meu passaporte.'],['airport','aeroporto','The airport is big.','O aeroporto é grande.'],['flight','voo','My flight is at six.','Meu voo é às seis.'],['luggage','bagagem','This is my luggage.','Esta é minha bagagem.'],['map','mapa','I have a map.','Eu tenho um mapa.']]],
 ['Hotel',[['reservation','reserva','I have a reservation.','Eu tenho uma reserva.'],['key','chave','Here is your key.','Aqui está sua chave.'],['night','noite','One night, please.','Uma noite, por favor.'],['bathroom','banheiro','Where is the bathroom?','Onde fica o banheiro?'],['floor','andar / piso','My room is on this floor.','Meu quarto fica neste andar.'],['towel','toalha','I need a towel.','Eu preciso de uma toalha.']]],
 ['Transporte',[['bus','ônibus','I take the bus.','Eu pego o ônibus.'],['train','trem','The train is here.','O trem está aqui.'],['taxi','táxi','I need a taxi.','Eu preciso de um táxi.'],['car','carro','This is my car.','Este é meu carro.'],['bike','bicicleta','I ride a bike.','Eu ando de bicicleta.'],['stop','parada','Where is the bus stop?','Onde fica a parada de ônibus?']]],
 ['Clima',[['sunny','ensolarado','It is sunny today.','Está ensolarado hoje.'],['rain','chuva','I like the rain.','Eu gosto da chuva.'],['cold','frio','It is cold here.','Está frio aqui.'],['hot','quente','It is hot today.','Está quente hoje.'],['wind','vento','The wind is strong.','O vento está forte.'],['weather','tempo / clima','The weather is nice.','O tempo está agradável.']]],
 ['Roupas',[['shirt','camisa','This shirt is blue.','Esta camisa é azul.'],['shoes','sapatos','My shoes are new.','Meus sapatos são novos.'],['size','tamanho','What size is this?','Qual é o tamanho disto?'],['coat','casaco','I need a coat.','Eu preciso de um casaco.'],['dress','vestido','This dress is red.','Este vestido é vermelho.'],['hat','chapéu','I like your hat.','Eu gosto do seu chapéu.']]],
 ['Trabalho',[['job','emprego','I have a new job.','Eu tenho um emprego novo.'],['office','escritório','My office is small.','Meu escritório é pequeno.'],['manager','gerente','This is my manager.','Este é meu gerente.'],['meeting','reunião','The meeting is at two.','A reunião é às duas.'],['desk','mesa de trabalho','My desk is here.','Minha mesa fica aqui.'],['team','equipe','I like my team.','Eu gosto da minha equipe.']]],
 ['Estudos',[['school','escola','My school is near.','Minha escola é perto.'],['teacher','professor','My teacher is kind.','Meu professor é gentil.'],['book','livro','This is my book.','Este é meu livro.'],['pencil','lápis','I need a pencil.','Eu preciso de um lápis.'],['lesson','aula','The lesson is easy.','A aula é fácil.'],['question','pergunta','I have a question.','Eu tenho uma pergunta.']]],
 ['Lazer',[['music','música','I like music.','Eu gosto de música.'],['movie','filme','This movie is good.','Este filme é bom.'],['read','ler','I read every day.','Eu leio todos os dias.'],['dance','dançar','I like to dance.','Eu gosto de dançar.'],['game','jogo','This game is fun.','Este jogo é divertido.'],['weekend','fim de semana','I rest at the weekend.','Eu descanso no fim de semana.']]],
 ['Esportes',[['football','futebol','I play football.','Eu jogo futebol.'],['swim','nadar','I swim on Mondays.','Eu nado às segundas-feiras.'],['run','correr','I run in the park.','Eu corro no parque.'],['walk','caminhar','I walk every morning.','Eu caminho todas as manhãs.'],['ball','bola','The ball is here.','A bola está aqui.'],['tennis','tênis (esporte)','I like tennis.','Eu gosto de tênis.']]],
 ['Bem-estar',[['head','cabeça','My head hurts.','Minha cabeça dói.'],['tired','cansado','I am tired.','Eu estou cansado.'],['doctor','médico','I need a doctor.','Eu preciso de um médico.'],['rest','descansar','I need to rest.','Eu preciso descansar.'],['well','bem','I feel well today.','Eu me sinto bem hoje.'],['appointment','consulta / compromisso','I have an appointment.','Eu tenho uma consulta.']]],
 ['Tecnologia',[['computer','computador','My computer is new.','Meu computador é novo.'],['password','senha','I need a password.','Eu preciso de uma senha.'],['screen','tela','The screen is big.','A tela é grande.'],['message','mensagem','I have a message.','Eu tenho uma mensagem.'],['internet','internet','The internet is slow.','A internet está lenta.'],['photo','foto','This photo is nice.','Esta foto é bonita.']]],
 ['Agenda',[['Monday','segunda-feira','I work on Monday.','Eu trabalho na segunda-feira.'],['today','hoje','I am free today.','Eu estou livre hoje.'],['tomorrow','amanhã','See you tomorrow.','Até amanhã.'],['time','hora / tempo','What time is the meeting?','A que horas é a reunião?'],['early','cedo','I get up early.','Eu acordo cedo.'],['late','atrasado / tarde','I am late.','Eu estou atrasado.']]],
 ['Sentimentos',[['happy','feliz','I am happy.','Eu estou feliz.'],['sad','triste','I feel sad today.','Eu me sinto triste hoje.'],['angry','com raiva','He is angry.','Ele está com raiva.'],['excited','animado','I am excited.','Eu estou animado.'],['worried','preocupado','She is worried.','Ela está preocupada.'],['fine','bem','I am fine, thank you.','Eu estou bem, obrigado.']]],
 ['Planos simples',[['want','querer','I want to study.','Eu quero estudar.'],['visit','visitar','I want to visit Brazil.','Eu quero visitar o Brasil.'],['learn','aprender','I want to learn English.','Eu quero aprender inglês.'],['go','ir','I want to go home.','Eu quero ir para casa.'],['travel','viajar','I like to travel.','Eu gosto de viajar.'],['stay','ficar','I want to stay here.','Eu quero ficar aqui.']]],
 ['Pedir ajuda',[['help','ajuda / ajudar','Can you help me?','Você pode me ajudar?'],['repeat','repetir','Please repeat that.','Por favor, repita isso.'],['slowly','devagar','Please speak slowly.','Por favor, fale devagar.'],['understand','entender','I do not understand.','Eu não entendo.'],['sorry','desculpa','I am sorry.','Desculpe.'],['please','por favor','Help me, please.','Ajude-me, por favor.']]],
 ['Encontros sociais',[['welcome','bem-vindo','Welcome to my home.','Bem-vindo à minha casa.'],['thanks','obrigado','Thanks for your help.','Obrigado pela sua ajuda.'],['goodbye','adeus / tchau','Goodbye, see you soon.','Tchau, até logo.'],['party','festa','The party is on Friday.','A festa é na sexta-feira.'],['birthday','aniversário','Happy birthday, Ana!','Feliz aniversário, Ana!'],['together','juntos','We study together.','Nós estudamos juntos.']]]
 ];
 const lessons=topics.flatMap(([topic,entries],topicIndex)=>entries.map((entry,index)=>({id:`A1-${String(topicIndex*6+index+1).padStart(3,'0')}`,level:'A1',number:topicIndex*6+index+1,title:`${topic}: ${entry[0]}`,topic,objective:`Usar “${entry[0]}” em uma situação de ${topic.toLowerCase()}.`,vocabulary:entries.map(([en,pt])=>({en,pt})),example:{en:entry[2],pt:entry[3]},conversation:{opening:'Hello! Let us practice English together.',prompt:`Use the phrase "${entry[2]}" in a short conversation.`,instructions:`Pratique o tema ${topic}, com foco em ${entry[0]}, em inglês A1. Apresente uma situação concreta. Faça uma pergunta simples de cada vez e aceite respostas pessoais. Exemplo de referência: ${entry[2]}`},questions:[{prompt:`Qual é o significado de “${entry[0]}”?`,options:[entry[1],entries[(index+1)%6][1],entries[(index+2)%6][1]],answer:0,explanation:`${entry[0]} — ${entry[1]}`},{prompt:`Qual tradução corresponde a “${entry[2]}”?`,options:[entries[(index+2)%6][3],entry[3],entries[(index+1)%6][3]],answer:1,explanation:`${entry[2]} — ${entry[3]}`}],status:'generated'})));
 const a2Topics=typeof module!=='undefined'?require('./curriculum-a2.js'):root.StudyA2;
 lessons.push(...a2Topics.flatMap(([topic,entries],topicIndex)=>entries.map((entry,index)=>({id:`A2-${String(topicIndex*6+index+1).padStart(3,'0')}`,level:'A2',number:topicIndex*6+index+1,title:`${topic}: ${entry[0]}`,topic,objective:`Usar “${entry[0]}” para trocar informações em uma situação de ${topic.toLowerCase()}.`,vocabulary:entries.map(([en,pt])=>({en,pt})),example:{en:entry[2],pt:entry[3]},conversation:{opening:'Hi! Tell me about your situation.',prompt:`Crie uma conversa de três ou quatro falas sobre ${topic.toLowerCase()}. Use “${entry[0]}”, faça uma pergunta e acrescente uma informação pessoal. Referência: “${entry[2]}”`,instructions:`Pratique inglês A2 com um adulto brasileiro. Contexto: ${topic}. Foco: ${entry[0]}. Exemplo: ${entry[2]}. Assuma um papel concreto nesta situação e faça uma pergunta por vez. Incentive o aluno a acrescentar detalhes, relatar um acontecimento ou fazer um pedido. Use frases curtas com vocabulário cotidiano; explique uma correção em português se necessário.`},questions:[{prompt:`Nesta situação, o que significa “${entry[0]}”?`,options:[entry[1],entries[(index+1)%6][1],entries[(index+2)%6][1]],answer:0,explanation:`${entry[0]} — ${entry[1]}`},{prompt:`Qual sentido corresponde a “${entry[2]}”?`,options:[entries[(index+2)%6][3],entry[3],entries[(index+1)%6][3]],answer:1,explanation:`${entry[2]} — ${entry[3]}`}],status:'generated'}))));
 const b1Topics=typeof module!=='undefined'?require('./curriculum-b1.js'):root.StudyB1;
 lessons.push(...b1Topics.flatMap(([topic,entries],topicIndex)=>entries.map((entry,index)=>({id:`B1-${String(topicIndex*6+index+1).padStart(3,'0')}`,level:'B1',number:topicIndex*6+index+1,title:`${topic}: ${entry[0]}`,topic,objective:`Usar “${entry[0]}” para explicar uma experiência, opinião ou solução em ${topic.toLowerCase()}.`,vocabulary:entries.map(([en,pt])=>({en,pt})),example:{en:entry[2],pt:entry[3]},conversation:{opening:'Tell me more about your experience or opinion.',prompt:`Simule uma conversa de cinco ou seis falas sobre ${topic.toLowerCase()}. Use “${entry[0]}”, explique um motivo, dê um exemplo e faça uma pergunta de acompanhamento. Referência: “${entry[2]}”`,instructions:`Pratique inglês B1 com um adulto brasileiro. Contexto: ${topic}. Foco: ${entry[0]}. Exemplo: ${entry[2]}. Assuma um papel concreto no contexto e faça uma pergunta por vez. Incentive explicações de experiências, opiniões e planos com motivos e exemplos. Use linguagem clara de nível intermediário. Pergunte sobre um detalhe da resposta do aluno. Corrija um ponto relevante de estrutura ou escolha lexical sem interromper a conversa; explique em português quando necessário.`},questions:[{prompt:`Neste contexto, o que significa “${entry[0]}”?`,options:[entry[1],entries[(index+1)%6][1],entries[(index+2)%6][1]],answer:0,explanation:`${entry[0]} — ${entry[1]}`},{prompt:`Qual interpretação corresponde a “${entry[2]}”?`,options:[entries[(index+2)%6][3],entry[3],entries[(index+1)%6][3]],answer:1,explanation:`${entry[2]} — ${entry[3]}`}],status:'generated'}))));
 function advancedLessons(level,source,skills){return source.flatMap(([topic,entries],topicIndex)=>entries.map((entry,index)=>({id:`${level}-${String(topicIndex*6+index+1).padStart(3,'0')}`,level,number:topicIndex*6+index+1,title:`${topic}: ${entry[0]}`,topic,objective:`Usar “${entry[0]}” para ${skills.objective} em ${topic.toLowerCase()}.`,vocabulary:entries.map(([en,pt])=>({en,pt})),example:{en:entry[2],pt:entry[3]},conversation:{opening:skills.opening,prompt:`Simule uma conversa sobre ${topic.toLowerCase()}. Use “${entry[0]}”. ${skills.task} Referência: “${entry[2]}”`,instructions:`Pratique inglês ${level} com um adulto brasileiro. Contexto: ${topic}. Foco lexical: ${entry[0]}. Exemplo: ${entry[2]}. Assuma um papel concreto no contexto. ${skills.tutor} Faça uma pergunta por vez, aproveite a resposta do aluno para continuar a troca e corrija um ponto relevante de estrutura, escolha lexical ou registro. Explique em português quando solicitado; não atribua uma nota de fluência a uma única resposta.`},questions:[{prompt:`Qual sentido “${entry[0]}” tem neste contexto?`,options:[entry[1],entries[(index+1)%6][1],entries[(index+2)%6][1]],answer:0,explanation:`${entry[0]} — ${entry[1]}`},{prompt:`Qual interpretação preserva o sentido de “${entry[2]}”?`,options:[entries[(index+2)%6][3],entry[3],entries[(index+1)%6][3]],answer:1,explanation:`${entry[2]} — ${entry[3]}`}],status:'generated'})));}
 const b2Topics=typeof module!=='undefined'?require('./curriculum-b2.js'):root.StudyB2;
 lessons.push(...advancedLessons('B2',b2Topics,{objective:'desenvolver e comparar argumentos',opening:'What would you propose, and what might someone disagree with?',task:'Desenvolva seis a oito falas: apresente uma posição, um motivo, um contraponto e uma concessão. Responda a uma pergunta de acompanhamento e procure um acordo.',tutor:'Use linguagem de nível B2. Incentive argumentos detalhados, comparação de opções, hipóteses e defesa de uma posição. Apresente um contraponto plausível sem transformar toda troca em debate. Ajude o aluno a adequar o registro à situação.'}));
 // Rotate answer positions so repetition cannot replace comprehension.
 lessons.forEach(lesson=>lesson.questions.forEach((question,index)=>{const shift=(lesson.number+index)%question.options.length;question.options=[...question.options.slice(shift),...question.options.slice(0,shift)];question.answer=(question.answer-shift+question.options.length)%question.options.length;}));
 const api={levels,lessons,get:id=>lessons.find(lesson=>lesson.id===id)};root.StudyCurriculum=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
