'use strict';
(()=>{const L=StudyLexicon,root=document.createElement('section');root.id='dictionary';root.className='module lesson';root.innerHTML='<p class="eyebrow">DESCUBRA · ENTENDA · USE</p><h2>Seu dicionário de inglês.</h2><p>Pesquise em inglês ou português e veja como usar uma palavra ou expressão.</p><form id="dictionary-form"><label for="dictionary-query">Palavra ou expressão <input id="dictionary-query" type="search" required maxlength="80" placeholder="Ex.: work, get along ou trabalho" autocomplete="off"></label><button class="button">Pesquisar</button></form><p id="dictionary-status" role="status"></p><div id="dictionary-local"></div><article id="dictionary-ai" class="connection-card" hidden><p class="eyebrow">EXPLICAÇÃO DA IA</p><h3 id="dictionary-ai-term"></h3><p id="dictionary-meaning"></p><h4>Como usar</h4><p id="dictionary-usage"></p><div id="dictionary-examples"></div><div id="dictionary-related" class="word-bank"></div><p class="muted">Explicação gerada por IA; confira o contexto. Não é uma citação de um dicionário externo.</p></article><button id="dictionary-ask" class="button secondary" disabled>Pedir explicação à IA</button><p id="dictionary-availability">Verificando disponibilidade da IA…</p><p class="muted">A consulta enviada à IA é processada pela OpenAI. Sem IA configurada, a base do curso continua disponível.</p>';
 document.querySelector('#reset').before(root);const $=s=>root.querySelector(s);let configured=false,controller=null,query='',revision=0;
 function stop(){revision++;controller?.abort();controller=null;$('#dictionary-ask').disabled=!configured||!query;}
 function audio(text){const button=document.createElement('button');button.className='listen';button.textContent='🔊 Ouvir exemplo';button.addEventListener('click',()=>{pauseScene();speak(text);});return button;}
 function local(value){stop();query=value.trim();if(!query){$('#dictionary-status').textContent='Digite uma palavra ou expressão para pesquisar.';$('#dictionary-ask').disabled=true;return;}$('#dictionary-ai').hidden=true;const list=$('#dictionary-local');list.replaceChildren();const matches=L.search(query,{limit:4}),exact=L.search(query,{exact:true,limit:12});const entries=exact.length?exact:matches;$('#dictionary-status').textContent=entries.length?`${entries.length} referências do curso para “${query}”.`:`Não encontrei “${query}” na base do curso. Você pode pedir uma explicação à IA.`;const used=new Set();for(const e of entries){if(used.has(e.en))continue;used.add(e.en);const card=document.createElement('article');card.className='connection-card';const title=document.createElement('h3');title.textContent=e.term;const meaning=document.createElement('p');meaning.textContent=e.meaning;const en=document.createElement('p');en.className='dictionary-english';en.textContent=e.en;const pt=document.createElement('p');pt.textContent=e.pt;const caption=document.createElement('small');caption.textContent=`Base do curso · ${e.level} · ${e.topic}`;card.append(title,meaning,en,pt,caption,audio(e.en));list.append(card);}$('#dictionary-ask').disabled=!configured||!query;}
 function renderAI(data){$('#dictionary-ai-term').textContent=data.term;$('#dictionary-meaning').textContent=data.meaningPt;$('#dictionary-usage').textContent=data.usagePt;$('#dictionary-examples').replaceChildren();for(const e of data.examples){const box=document.createElement('article'),en=document.createElement('p'),pt=document.createElement('p');en.className='dictionary-english';en.textContent=e.en;pt.textContent=e.pt;box.append(en,pt,audio(e.en));$('#dictionary-examples').append(box);}$('#dictionary-related').replaceChildren();for(const term of data.related){const button=document.createElement('button');button.type='button';button.textContent=term;button.addEventListener('click',()=>{$('#dictionary-query').value=term;local(term);});$('#dictionary-related').append(button);}$('#dictionary-ai').hidden=false;}
 async function ask(){if(!configured||!query)return;stop();const version=revision;controller=new AbortController();$('#dictionary-ask').disabled=true;$('#dictionary-status').textContent='A IA está preparando a explicação…';try{const response=await fetch('/api/dictionary',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':globalThis.StudyAccount?.csrf()||''},body:JSON.stringify({query,level:StudyAssessment.currentLevel(StudyJourney.get())||'A1'}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(50000)])});const data=await response.json();if(!response.ok)throw Error(data.error);if(version!==revision)return;renderAI(data);$('#dictionary-status').textContent='Significado e exemplos preparados pela IA.';}catch(error){if(version===revision&&error.name!=='AbortError')$('#dictionary-status').textContent=(error.name==='TimeoutError'?'A consulta demorou demais. Tente novamente.':error.message)||'Não foi possível consultar. As referências do curso continuam disponíveis.';}finally{if(version===revision){controller=null;$('#dictionary-ask').disabled=!configured||!query;}}}
 $('#dictionary-form').addEventListener('submit',event=>{event.preventDefault();local($('#dictionary-query').value);if(configured)ask();});$('#dictionary-query').addEventListener('input',()=>{stop();query='';$('#dictionary-ask').disabled=true;$('#dictionary-ai').hidden=true;});$('#dictionary-ask').addEventListener('click',ask);document.addEventListener('studyia:navigate',()=>{if(!location.hash.startsWith('#dictionary'))stop();});
 if(location.protocol==='file:')$('#dictionary-availability').textContent='Abra pelo servidor para usar a IA. A base do curso está disponível.';else fetch('/api/status').then(r=>r.json()).then(data=>{configured=data.configured===true;$('#dictionary-availability').textContent=configured?'IA disponível: a busca também solicita exemplos e explicação.':'IA ainda não configurada. Consulte palavras e exemplos da base do curso.';$('#dictionary-ask').disabled=!configured||!query;}).catch(()=>$('#dictionary-availability').textContent='Servidor da IA indisponível. A base do curso continua disponível.');
 globalThis.StudyDictionary={search(term){location.hash='dictionary';$('#dictionary-query').value=term;local(term);}};
})();
