 .dockerignore                               |  16 [32m+++[m
 .env.example                                |  28 [32m+++++[m
 .gitattributes                              |   5 [32m+[m
 .github/workflows/tests.yml                 |  33 [32m+++++[m
 .gitignore                                  |  44 [32m+++++++[m
 Dockerfile                                  |   9 [32m++[m
 README.md                                   |  72 [32m+++++++++++[m
 account-ui.js                               |  24 [32m++++[m
 account.css                                 |   4 [32m+[m
 ai.js                                       |  67 [32m++++++++++[m
 app.js                                      |  37 [32m++++++[m
 assessment-ui.js                            |  28 [32m+++++[m
 assessment.css                              |   1 [32m+[m
 assessment.js                               |  19 [32m+++[m
 assets/icons/LICENSE.txt                    |  43 [32m+++++++[m
 assets/icons/arrow-left.svg                 |  14 [32m+++[m
 assets/icons/audio-lines.svg                |  18 [32m+++[m
 assets/icons/book-a.svg                     |  15 [32m+++[m
 assets/icons/book-open-text.svg             |  18 [32m+++[m
 assets/icons/house.svg                      |  14 [32m+++[m
 assets/icons/list-checks.svg                |  17 [32m+++[m
 assets/icons/messages-square.svg            |  14 [32m+++[m
 assets/icons/sliders-horizontal.svg         |  21 [32m++++[m
 assets/icons/user-round.svg                 |  14 [32m+++[m
 assets/school/elementos-01.png              | Bin [31m0[m -> [32m63513[m bytes
 assets/school/elementos-02.png              | Bin [31m0[m -> [32m77557[m bytes
 assets/school/elementos-04.png              | Bin [31m0[m -> [32m91538[m bytes
 assets/school/elementos-05.png              | Bin [31m0[m -> [32m46745[m bytes
 assets/school/elementos-06.png              | Bin [31m0[m -> [32m32821[m bytes
 assets/school/elementos-07.png              | Bin [31m0[m -> [32m63784[m bytes
 assets/school/elementos-08.png              | Bin [31m0[m -> [32m80294[m bytes
 assets/school/elementos-09.png              | Bin [31m0[m -> [32m46035[m bytes
 assets/school/elementos-10.png              | Bin [31m0[m -> [32m66510[m bytes
 auth/identity.mjs                           |   4 [32m+[m
 backend/accounts.mjs                        |  20 [32m+++[m
 backend/api.mjs                             |  13 [32m++[m
 backend/database.mjs                        |   4 [32m+[m
 backend/dictionary.mjs                      |   6 [32m+[m
 backend/http-security.mjs                   |  12 [32m++[m
 backend/languages.mjs                       |   2 [32m+[m
 backend/learning.mjs                        |  19 [32m+++[m
 backend/migrate.mjs                         |   3 [32m+[m
 backend/migrations/001_company.sql          |  31 [32m+++++[m
 backend/migrations/002_onboarding.sql       |   1 [32m+[m
 backend/migrations/003_spanish.sql          |  28 [32m+++++[m
 backend/migrations/004_french_italian.sql   |  56 [32m+++++++++[m
 backend/migrations/005_global_languages.sql | 114 [32m+++++++++++++++++[m
 backend/realtime.mjs                        |  45 [32m+++++++[m
 backend/speech.mjs                          |  28 [32m+++++[m
 backend/teaching.mjs                        |   6 [32m+[m
 brand.css                                   |  37 [32m++++++[m
 compose.yaml                                |  79 [32m++++++++++++[m
 conversation.css                            |   4 [32m+[m
 conversation.js                             |  53 [32m++++++++[m
 course-plan.js                              |  15 [32m+++[m
 course.css                                  |   1 [32m+[m
 course.js                                   |  33 [32m+++++[m
 curriculum-a2.js                            | 183 [32m++++++++++++++++++++++++++++[m
 curriculum-b1.js                            | 182 [32m+++++++++++++++++++++++++++[m
 curriculum-b2.js                            | 182 [32m+++++++++++++++++++++++++++[m
 curriculum-c1.js                            | 182 [32m+++++++++++++++++++++++++++[m
 curriculum-c2.js                            | 183 [32m++++++++++++++++++++++++++++[m
 curriculum-es.js                            |  35 [32m++++++[m
 curriculum-global.js                        | 112 [32m+++++++++++++++++[m
 curriculum-romance.js                       |  59 [32m+++++++++[m
 curriculum-ui.js                            |  23 [32m++++[m
 curriculum.css                              |   2 [32m+[m
 curriculum.js                               |  46 [32m+++++++[m
 deploy/docker.env.example                   |  13 [32m++[m
 deploy/docker/create-certs.sh               |  23 [32m++++[m
 deploy/docker/init-db.sh                    |   9 [32m++[m
 deploy/docker/nginx.conf                    |  26 [32m++++[m
 deploy/nginx.conf                           |  27 [32m++++[m
 deploy/studyia.service                      |  21 [32m++++[m
 dev-server.mjs                              |  19 [32m+++[m
 dictionary-ui.js                            |  12 [32m++[m
 dictionary.css                              |   2 [32m+[m
 docs/access-and-menu.md                     |  17 [32m+++[m
 docs/ai-setup.md                            |  36 [32m++++++[m
 docs/assessment-and-identity.md             |  35 [32m++++++[m
 docs/centos-stream-9.md                     |  46 [32m+++++++[m
 docs/course-status.md                       |  36 [32m++++++[m
 docs/deploy-centos9.md                      | 171 [32m++++++++++++++++++++++++++[m
 docs/deploy-docker-internal.md              | 154 [32m+++++++++++++++++++++++[m
 docs/dictionary.md                          |  13 [32m++[m
 docs/global-languages.md                    |  11 [32m++[m
 docs/icons.md                               |   7 [32m++[m
 docs/languages.md                           |   7 [32m++[m
 docs/natural-voice.md                       |  13 [32m++[m
 docs/postgresql-operations.md               |  61 [32m++++++++++[m
 docs/product.md                             |  53 [32m++++++++[m
 docs/realtime-teacher.md                    |  25 [32m++++[m
 docs/roadmap.md                             |  43 [32m+++++++[m
 docs/school-elements.md                     |   9 [32m++[m
 docs/teacher-practice.md                    |  13 [32m++[m
 enhancements.js                             |  34 [32m++++++[m
 index.html                                  |  21 [32m++++[m
 journey-store.js                            |   6 [32m+[m
 language-config.js                          |   2 [32m+[m
 language-practice.js                        |   5 [32m+[m
 language-ui.js                              |  12 [32m++[m
 language.js                                 |   2 [32m+[m
 layout.css                                  |   1 [32m+[m
 learning-data.js                            |  18 [32m+++[m
 lexicon.js                                  |   9 [32m++[m
 media.css                                   |   1 [32m+[m
 media.js                                    |  62 [32m++++++++++[m
 menu-icons.css                              |  26 [32m++++[m
 menu-icons.js                               |  25 [32m++++[m
 menu.css                                    |   6 [32m+[m
 menu.js                                     |  20 [32m+++[m
 natural-voice.js                            |  10 [32m++[m
 navigation.js                               |  85 [32m+++++++++++++[m
 numbers.css                                 |   1 [32m+[m
 numbers.js                                  |  43 [32m+++++++[m
 onboarding.css                              |   9 [32m++[m
 onboarding.js                               |  22 [32m++++[m
 package-lock.json                           | 174 [32m++++++++++++++++++++++++++[m
 package.json                                |   1 [32m+[m
 personalization.css                         |   1 [32m+[m
 personalization.js                          |  33 [32m+++++[m
 progress-panel.js                           |  10 [32m++[m
 pronunciation.mjs                           |   3 [32m+[m
 realtime-ui.js                              |  43 [32m+++++++[m
 realtime.css                                |   2 [32m+[m
 review.css                                  |   1 [32m+[m
 review.js                                   |  28 [32m+++++[m
 school-elements.css                         |  22 [32m++++[m
 school-logo.jpg                             | Bin [31m0[m -> [32m229764[m bytes
 server.mjs                                  | 116 [32m++++++++++++++++++[m
 styles.css                                  |   1 [32m+[m
 tests/assessment.test.mjs                   |   9 [32m++[m
 tests/company.test.mjs                      |  13 [32m++[m
 tests/course-backup.test.mjs                |   5 [32m+[m
 tests/course-plan.test.mjs                  |  25 [32m++++[m
 tests/curriculum.test.mjs                   |  19 [32m+++[m
 tests/dev-login.test.mjs                    |   4 [32m+[m
 tests/dictionary.test.mjs                   |   6 [32m+[m
 tests/global-languages.test.mjs             |   3 [32m+[m
 tests/http-security.test.mjs                |  27 [32m++++[m
 tests/identity-speech.test.mjs              |   5 [32m+[m
 tests/learning-data.test.mjs                |   8 [32m++[m
 tests/lesson-chat.test.mjs                  |   3 [32m+[m
 tests/natural-voice.test.mjs                |   3 [32m+[m
 tests/onboarding.test.mjs                   |   2 [32m+[m
 tests/postgres-helper.mjs                   |   7 [32m++[m
 tests/realtime.test.mjs                     |  20 [32m+++[m
 tests/romance.test.mjs                      |   6 [32m+[m
 tests/server.test.mjs                       |   8 [32m++[m
 tests/spanish.test.mjs                      |   7 [32m++[m
 tests/teacher-practice.test.mjs             |  10 [32m++[m
 tests/topics.test.mjs                       |   9 [32m++[m
 tests/vocabulary-check.test.mjs             |   5 [32m+[m
 themes.css                                  |   2 [32m+[m
 vocabulary-check.js                         |  11 [32m++[m
 vocabulary.css                              |   1 [32m+[m
 vocabulary.js                               |  16 [32m+++[m
 157 files changed, 4369 insertions(+)
