'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const lang=StudyLanguage,selector=document.createElement('label');selector.className='language-picker';selector.innerHTML='Aprender <select id="study-language" aria-label="Idioma de aprendizagem"><option value="en">Inglês</option><option value="es">Espanhol</option><option value="fr">Francês</option><option value="it">Italiano</option></select><span id="language-status" role="status"></span>';document.querySelector('header').append(selector);const select=selector.querySelector('select');select.value=lang.code;
 select.addEventListener('change',async()=>{const next=select.value;select.disabled=true;try{if(StudyAccount.signedIn())await StudyAccount.request('language',{language:next});localStorage.setItem('studyia.language',next);location.hash='home';location.reload();}catch(error){selector.querySelector('span').textContent=error.message;select.value=lang.code;select.disabled=false;}});
 if(lang.code==='en')return;
 function translate(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement.closest('.language-picker')||['SCRIPT','STYLE','TEXTAREA'].includes(node.parentElement.tagName))continue;node.nodeValue=node.nodeValue.replace(/inglês/gi,m=>m[0]==='I'?lang.label:lang.name).replace(/inglê[s–-]português/gi,lang.name+'–português').replace(/🇬🇧/g,lang.flag).replace(/🇬🇧/g,lang.flag);}const voice=document.querySelector('#ai-voice-language option');voice.value=lang.speech;voice.textContent=lang.label;document.querySelector('#vocab-search').placeholder=lang.code==='fr'?'Ex.: tasse ou xícara':lang.code==='it'?'Ex.: tazza ou xícara':'Ex.: café ou xícara';document.querySelector('#dictionary-query').placeholder=lang.code==='fr'?'Ex.: travail, demain ou trabalho':lang.code==='it'?'Ex.: lavoro, domani ou trabalho':'Ex.: trabajo, mañana ou trabalho';}
 const units=document.querySelector('#units .unit-list');[...units.children].forEach(n=>n.hidden=true);for(const [id,title]of [['A1-001','Apresentações'],['A1-031','Na cafeteria'],['A1-055','Viagens']]){const a=document.createElement('a');a.href='#learning?lesson='+id;a.className='unit-link';a.textContent=title+' · '+lang.label;units.append(a);}
 const studio=document.querySelector('#studio');const teacher=document.querySelector('#ai-panel');const video=studio.querySelector('.video-section');const lab=document.createElement('article');lab.className='connection-card';lab.innerHTML='<h3>Ouça e pratique '+lang.name+'</h3><label>Seu nível <select id="spanish-audio-level">'+StudyCurriculum.levels.map(l=>'<option>'+l+'</option>').join('')+'</select></label><p id="spanish-audio-text"></p><p id="spanish-audio-translation"></p><button id="spanish-audio" class="button">Ouvir exemplo</button><button id="spanish-next" class="button secondary">Próximo exemplo</button><a class="button secondary" href="#catalog">Praticar nas aulas</a>';studio.querySelectorAll('.subnav,.activity-panel').forEach(n=>n.hidden=true);studio.append(lab);if(video)studio.append(video);let number=0;const level=lab.querySelector('select');function audio(){const lesson=StudyCurriculum.lessons.filter(l=>l.level===level.value)[number];lab.querySelector('#spanish-audio-text').textContent=lesson.example.en;lab.querySelector('#spanish-audio-translation').textContent=lesson.example.pt;}level.onchange=()=>{number=0;audio();};lab.querySelector('#spanish-next').onclick=()=>{number=(number+1)%150;audio();};lab.querySelector('#spanish-audio').onclick=()=>speak(lab.querySelector('#spanish-audio-text').textContent,lang.speech);audio();
 const conversation=document.querySelector('#conversation');const buttons=conversation.querySelectorAll(':scope>.subnav button');buttons[2]?.click();buttons.forEach((b,i)=>{if(i<2)b.hidden=true;});
 const review=document.querySelector('#review');function reviewSpanish(){if(location.hash!=='#review')return;review.querySelectorAll(':scope > :not(.spanish-review)').forEach(n=>n.hidden=true);let content=review.querySelector('.spanish-review');if(!content){content=document.createElement('div');content.className='spanish-review';review.append(content);}content.replaceChildren();const h=document.createElement('h2');h.textContent='Revisão de '+lang.name;const p=document.createElement('p');p.textContent='Revise o vocabulário e os exemplos das aulas que já começou.';content.append(h,p);const progress=JSON.parse(localStorage.getItem(StudyData.keys.curriculum)||'{}');const lessons=Object.keys(progress).map(id=>StudyCurriculum.get(id)).filter(Boolean);for(const lesson of lessons.slice(-12)){const a=document.createElement('a');a.className='unit-link';a.href='#learning?lesson='+lesson.id;a.textContent=lesson.title+' — '+lesson.example.en;content.append(a);}if(!lessons.length)p.textContent='Comece sua primeira aula para formar sua lista de revisão.';}
 function route(){if(['#lesson','#numbers','#cafe'].includes(location.hash)){location.hash='learning?lesson='+({'#lesson':'A1-001','#numbers':'A1-121','#cafe':'A1-031'}[location.hash]);return;}translate();reviewSpanish();}window.addEventListener('hashchange',route);window.addEventListener('load',translate);document.addEventListener('studyia:account',()=>setTimeout(translate,0));route();
});
