'use strict';
(function(root){
 const scenes={
 'Introduções':['You are at your first English class. A new student sits next to you. You smile and introduce yourself. You ask a question and listen to the answer.','Você está na primeira aula de inglês. Um aluno novo senta ao seu lado. Você se apresenta, faz uma pergunta e escuta a resposta.'],
 'Dados pessoais':['You are at a reception desk. The receptionist needs your details to complete a form. Give only the information requested. Ask the receptionist to repeat anything you do not understand.','Você está em uma recepção. O atendente precisa de dados para preencher um formulário. Responda ao que foi perguntado e peça para repetir quando necessário.'],
 'Família':['A colleague shows you a family photo. You show a photo too and explain who the people are. Give one detail about each person. Then ask about your colleague’s family.','Um colega mostra uma foto da família. Você apresenta as pessoas da sua foto e dá um detalhe sobre cada uma. Depois pergunta sobre a família dele.'],
 'Casa':['A friend visits your home for the first time. You show the rooms and explain where things are. Your friend asks a question. Give a short, clear answer.','Um amigo visita sua casa. Você apresenta os cômodos e explica onde ficam os objetos. Responda às perguntas com clareza.'],
 'Rotina':['Your new colleague asks about your day. Explain when you work, eat and study. Compare one part of your routines. Ask what your colleague does after work.','Um colega pergunta sobre seu dia. Explique horários de trabalho, refeições e estudos. Compare uma parte das rotinas.'],
 'Cafeteria':['You enter a café before work. Read the menu and decide what you want. The server asks for your order. Make your request politely and check it before you pay.','Você entra em uma cafeteria antes do trabalho. Escolha seu pedido, faça-o com educação e confira antes de pagar.'],
 'Alimentação':['You are having lunch with a friend. Talk about the food you like and what you usually eat. Your friend offers you something. Accept or refuse politely.','Você almoça com um amigo. Fale de preferências e hábitos. Aceite ou recuse uma oferta com educação.'],
 'Compras':['You find an item you want in a shop. Ask about the price and payment options. Check the information before buying it. Thank the assistant when you finish.','Você encontra um produto em uma loja. Pergunte o preço e as formas de pagamento, confira e agradeça.'],
 'Cidade':['You are walking in an unfamiliar neighbourhood. You need to find a place. Ask someone for directions and listen carefully. Repeat the important part to check you understood.','Você está em um bairro desconhecido. Peça orientação e repita a parte importante para confirmar que entendeu.'],
 'Viagens':['You arrive at the airport with time to spare. Check your documents and travel information. An employee asks you a question. Answer clearly and ask for help if necessary.','Você chega ao aeroporto com antecedência. Confira documentos e informações e responda ao funcionário.'],
 'Hotel':['You arrive at a hotel after a trip. Speak to the receptionist and check your booking. Ask about something you need. Confirm the answer before going to your room.','Você chega ao hotel. Confira a reserva, pergunte sobre algo de que precisa e confirme a resposta.'],
 'Transporte':['You need to get to a meeting. Compare the transport options and ask where to wait. Check the destination before getting on. Keep your question short and specific.','Você precisa chegar a uma reunião. Compare meios de transporte, pergunte onde esperar e confira o destino.'],
 'Clima':['You and a friend are planning an outdoor activity. Look outside and talk about the weather. Decide what to take with you. Change the plan if you need to.','Você planeja uma atividade ao ar livre. Comente o tempo, escolha o que levar e ajuste o plano.'],
 'Roupas':['You are choosing clothes for an event. Describe an item and check whether it fits. Ask a friend for an opinion. Explain your choice with one simple detail.','Você escolhe roupas para um evento. Descreva a peça, confira o tamanho e peça uma opinião.'],
 'Trabalho':['It is your first day at work. A colleague shows you the office. Introduce yourself and ask where you should go. Check the time of your next activity.','É seu primeiro dia no trabalho. Apresente-se, pergunte onde ir e confira o horário da próxima atividade.'],
 'Estudos':['You are in a class and need some information. Ask your teacher or a classmate a clear question. Explain what you need. Thank them and check your understanding.','Você está em aula e precisa de informação. Faça uma pergunta clara, explique sua necessidade e confirme que entendeu.'],
 'Lazer':['You meet a friend after work. Talk about what you enjoy doing. Suggest something you can do together. Ask whether your friend likes the idea.','Você encontra um amigo após o trabalho. Fale de interesses, sugira uma atividade e peça a opinião dele.'],
 'Esportes':['A friend asks about exercise. Say what you do and when you do it. Invite your friend to join you. Check a time and place that work for both of you.','Um amigo pergunta sobre exercícios. Explique o que faz e quando, convide-o e combinem horário e local.'],
 'Bem-estar':['You do not feel well during the day. Explain the problem to someone you trust. Ask for the help you need. Use a short sentence so the other person understands.','Você não está se sentindo bem. Explique o problema a alguém de confiança e peça ajuda de forma clara.'],
 'Tecnologia':['You are using a device and something is not working. Describe what you see. Ask a colleague for help. Check whether the suggested solution works.','Algo não funciona em um aparelho. Descreva o que vê, peça ajuda e teste a solução.'],
 'Agenda':['You need to arrange a time with a colleague. Check the day and the time. Say when you are available. Repeat the final arrangement to avoid a misunderstanding.','Você combina um horário com um colega. Confira dia e hora, diga sua disponibilidade e confirme o combinado.'],
 'Sentimentos':['A friend asks how you are. Explain how you feel and give a simple reason if you want to. Ask how your friend feels too. Listen before you respond.','Um amigo pergunta como você está. Conte como se sente, dê um motivo se quiser e escute seu amigo.'],
 'Planos simples':['You are planning the next day. Tell someone what you want to do. Ask whether they want to join you. Check one practical detail before you agree.','Você planeja o dia seguinte. Diga o que quer fazer, convide alguém e confira um detalhe prático.'],
 'Pedir ajuda':['You are in a new place and do not understand something. Get someone’s attention politely. Explain what you need. Ask them to repeat or speak slowly if necessary.','Você não entende algo em um lugar novo. Chame alguém com educação, explique sua necessidade e peça para repetir ou falar devagar.'],
 'Encontros sociais':['You meet people at a small event. Start a short conversation and ask an easy question. Listen and respond to what they say. End the conversation politely.','Você conhece pessoas em um evento. Comece uma conversa, faça uma pergunta, escute e encerre com educação.']
 };
 const rules=[
 [/\b(am|is|are)\b/i,'Verbo to be e ordem da frase','Use I am, he/she/it is e you/we/they are para identidade, estado ou descrição. Na negativa, coloque not depois do verbo. Na pergunta, o verbo vem antes do sujeito.','I am tired. → I am not tired. → Are you tired?','Não use do junto com be: “Are you tired?” e não “Do you are tired?”.'],
 [/\b(have|has) (you|she|he|they|we|ever)|\b(have|has) (been|worked|lived|finished)|\bsince\b/i,'Present perfect e relação com o presente','Have/has + particípio relaciona uma experiência ou resultado ao presente. Ever pergunta sobre experiência de vida. Since introduz o início de um período; for informa sua duração. Um momento passado concluído normalmente pede simple past.','Have you ever travelled abroad? / I travelled last year.','“Last year” delimita um passado concluído; não o trate como “since last year”.'],
 [/\bgoing to\b/i,'Intenções com going to','Forme be + going to + verbo-base. A forma de be acompanha o sujeito. Use para uma intenção ou uma previsão apoiada em sinais presentes; acrescente quando e onde para tornar seu plano útil.','I am going to study tonight. / Are you going to study?','“I going to study” perde o auxiliar am. Going to não recebe -s no verbo seguinte.'],
 [/\b(would|could|might|may|must|should|can)\b/i,'Modais e grau de certeza','Após um modal, use o verbo-base, sem -s e normalmente sem to. Can indica capacidade ou possibilidade; could/would podem suavizar pedidos; may/might evitam tratar uma possibilidade como certeza. Observe o contexto antes de escolher.','Could you help me? / It might rain. / She can swim.','“She can swims” está errado: a concordância não altera o verbo após can. May não significa certeza.'],
 [/\b(if|unless|provided|assuming)\b/i,'Condição e consequência','Identifique a condição e depois o resultado. If introduz uma condição; unless significa “a menos que”. Hipóteses irreais e fatos possíveis usam estruturas diferentes: compare if + present, will com if + past, would.','If it rains, we will stay home. / If I had time, I would help.','Unless já contém a ideia de “se não”; acrescentar outra negativa pode inverter o sentido.'],
 [/\b(although|nevertheless|however|whereas|despite|yet)\b/i,'Contraste e concessão','Although liga uma oração que reconhece uma dificuldade. Despite acompanha substantivo ou -ing. Nevertheless/however retomam um contraste entre afirmações. Whereas compara situações diferentes. Preserve a direção do argumento, não apenas palavras isoladas.','Although it rained, we left. / Despite the rain, we left.','“Despite it rained” não segue o padrão: use despite the rain ou although it rained.'],
 [/\b(because|therefore|thus|consequently|so that)\b/i,'Motivo, resultado e finalidade','Because apresenta uma causa. Therefore/thus/consequently apresentam uma consequência. So that explica uma finalidade. Pergunte se o segundo trecho responde “por quê?”, “com que resultado?” ou “para quê?”.','We left early because the trip was long. / We left early so that we could arrive on time.','Trocar because por therefore pode inverter a relação entre causa e resultado.'],
 [/\b(grew|moved|went|saw|bought|did|was|were|yesterday)\b|\w+ed\b/i,'Passado e sequência de acontecimentos','No simple past, conte um acontecimento concluído. Verbos regulares recebem -ed; irregulares têm formas próprias. Com did/didn’t, o verbo principal volta à forma-base. Marque a sequência com first, then e finally quando fizer sentido.','I moved last year. / Did you move last year? / I did not move.','“Did you moved?” marca o passado duas vezes; use “Did you move?”.'],
 [/\b(my|your|his|her|our|their)\b/i,'Posse e identificação','My, your, his, her, our e their vêm antes do substantivo. Eles indicam de quem algo é. My não significa I: “my name” é “meu nome”. Para falar de uma pessoa, mantenha claro quem possui cada objeto.','My name is Ana. / This is her book. / Is this your bag?','“I name” não substitui “my name”. Em inglês, a escolha de his/her depende do possuidor.'],
 [/\b(where|what|when|how|who)\b/i,'Perguntas que realmente pedem informação','What pede informação sobre algo; where pede lugar; when pede momento; how pede modo. Nas perguntas com be, coloque be antes do sujeito. Com verbos comuns, use do/does no presente e mantenha o verbo-base.','Where is the bank? / What do you need? / Where does she work?','“Where she works?” não é a ordem de uma pergunta direta; use “Where does she work?”.'],
 [/\b(more|less|better|worse|than)\b/i,'Comparação e referência','Compare duas alternativas deixando claro o critério. Use -er ou more conforme o adjetivo; better/worse são irregulares. Than introduz a segunda alternativa. Less e fewer não são intercambiáveis em todos os contextos.','This route is faster than that one. / This option is more expensive.','Não duplique o comparativo: “more cheaper” não substitui “cheaper”.'],
 [/\b(to|in order to)\b/i,'Infinitivo e propósito','To + verbo-base pode indicar uma ação desejada ou um propósito. O contexto mostra qual. Diferencie o infinitivo das preposições que exigem -ing, como interested in learning.','I want to learn. / I study to communicate. / I am interested in learning.','“I want learning” não segue o padrão de want to + verbo.'],
 [/.*/,'Estrutura, referência e escolha de palavras','Localize o sujeito, a ação ou estado e o complemento. Depois veja o papel da expressão da aula. Uma tradução palavra por palavra pode perder o sentido: aprenda a expressão com a frase inteira e adapte um detalhe de cada vez.','I work every day. / She works every day. / Do you work every day?','No presente simples afirmativo, he/she/it normalmente pede -s. Com does, use a forma-base.']
 ];
 const soundTips=[[/\b(thank|this|that|the|there|three|think)\b/i,'TH: a ponta da língua se aproxima dos dentes. Em think/three não há vibração da voz; em this/that há. Compare ouvindo, sem substituir sempre por t ou d.'],[/\b(name|late|day|rain|say)\b/i,'O som /eɪ/ desliza entre duas posições: name /neɪm/. Termine a palavra sem acrescentar uma vogal depois de m.'],[/\b(work|word|world)\b/i,'Em inglês americano, work /wɝːk/ tem uma vogal com r; em muitas variedades britânicas, /wɜːk/. Não acrescente uma sílaba depois do k final.'],[/\b(phone|home|go|no)\b/i,'Em inglês americano, /oʊ/ é um ditongo: phone /foʊn/. Em no, mantenha a vogal e não acrescente outra sílaba.'],[/\b(can|cat|bag|family)\b/i,'Observe /æ/, como em cat: uma vogal mais aberta que o “é” de muitos sotaques brasileiros. Can pode soar reduzido numa frase sem ênfase.']];
 function order(values,seed){let n=2166136261;for(const c of seed)n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;const out=[...values];for(let i=out.length-1;i>0;i--){n=(Math.imul(n,1664525)+1013904223)>>>0;const j=n%(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
 function enrich(lessons){for(const l of lessons){
  const peers=lessons.filter(p=>p.level===l.level&&p.topic===l.topic),rule=[...rules.slice(1,7),rules[0],...rules.slice(7)].find(r=>r[0].test(l.example.en)),focus=l.title.split(': ').slice(1).join(': ');
  const scene=scenes[l.topic]||[l.level==='A2'?'You are talking to someone you know. Explain what happened, check an important detail and decide what to do next.':l.level==='B1'?'You are discussing a real decision with a colleague. Describe the situation, explain a reason and ask a follow-up question.':'You are preparing a recommendation for a group. Separate facts from assumptions, consider an objection and explain the limits of your conclusion.',`Situação de ${l.topic.toLowerCase()}: ${l.level==='A2'?'conte um acontecimento e confira detalhes':l.level==='B1'?'explique uma escolha, um motivo e um exemplo':'defenda uma posição, reconheça uma objeção e ajuste o registro ao público'}.`];
  const sound=soundTips.find(r=>r[0].test(l.example.en))?.[1]||'Ouça a frase em partes. Identifique a palavra mais importante e mantenha suas consoantes finais. Palavras de função, como a e to, podem ser reduzidas; não pronuncie todas as sílabas com a mesma força. Variedades de sotaque são aceitáveis quando a fala é compreensível.';
  l.depth={context:scene,reading:[{en:scene[0],pt:scene[1]},{en:l.example.en,pt:l.example.pt},...peers.filter(p=>p.id!==l.id).slice(0,3).map(p=>p.example)],usage:`Use “${focus}” para cumprir o objetivo: ${l.objective} A frase principal é “${l.example.en}”. Identifique quem fala, a quem e qual informação ou ação espera. Nos exemplos relacionados, compare o que muda e mantenha a intenção adequada ao contexto.`,grammar:{title:rule[1],explanation:rule[2],example:rule[3],trap:rule[4]},pronunciation:sound,practice:[`Leia o contexto sem traduzir cada palavra. Explique em português a intenção de “${l.example.en}”.`,`Adapte a frase principal para uma situação sua, mantendo a estrutura. Acrescente um lugar, horário ou motivo que faça sentido.`,l.level==='A1'?'Escreva quatro falas: comece a interação, responda, faça uma pergunta e encerre com educação.':l.conversation.prompt]};
  l.questions.forEach((q,i)=>{const correct=q.options[q.answer],pool=i===0?l.vocabulary.map(v=>v.pt):peers.map(p=>p.example.pt);const alternatives=[correct,...order([...new Set(pool)].filter(x=>x!==correct),l.id+':distractors:'+i).slice(0,4)];q.options=order(alternatives,l.id+':options:'+i);q.answer=q.options.indexOf(correct);q.explanation+=i===0?` Na frase “${l.example.en}”, compare a expressão com as demais palavras do tema; elas pertencem à mesma situação, mas têm outra função.`:` Compare sujeito, tempo, negação e intenção. Uma frase do mesmo tema não é necessariamente uma tradução da frase apresentada.`;});
 }
 return lessons;}
 const api={enrich,order};root.StudyLessonDepth=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
