'use strict';
(function(root){const C=typeof module!=='undefined'?require('./curriculum.js'):root.StudyCurriculum;
 const initial=[['Hello!','Olá!','Hello, Ana!','Olá, Ana!'],['My name is…','Meu nome é…','My name is Samuel.','Meu nome é Samuel.'],['What is your name?','Qual é o seu nome?','Hello! What is your name?','Olá! Qual é o seu nome?'],['Nice to meet you.','Prazer em conhecer você.','Nice to meet you, Ana.','Prazer em conhecer você, Ana.'],['Seven','Sete','Seven coffees, please.','Sete cafés, por favor.'],['Twelve','Doze',"It's twelve o'clock.",'São doze horas.'],['What time is it?','Que horas são?',"What time is it? It's three o'clock.",'Que horas são? São três horas.'],['O’clock','Usado para indicar horas exatas',"It's nine o'clock.",'São nove horas.'],['A coffee','Um café','I would like a coffee, please.','Eu gostaria de um café, por favor.'],['Please','Por favor','A coffee, please.','Um café, por favor.'],['No, thank you.','Não, obrigado.','Anything else? No, thank you.','Mais alguma coisa? Não, obrigado.'],['How much is it?','Quanto custa?','A coffee, please. How much is it?','Um café, por favor. Quanto custa?']];
 const entries=initial.map(([term,meaning,en,pt],id)=>({id,term,meaning,en,pt,level:'A1',topic:'Primeiros passos',lessonId:null}));
 C.lessons.forEach(l=>{const term=l.title.slice(l.title.indexOf(':')+1).trim(),v=l.vocabulary.find(v=>v.en===term);entries.push({id:entries.length,term,meaning:v.pt,en:l.example.en,pt:l.example.pt,level:l.level,topic:l.topic,lessonId:l.id});});
 const normalize=value=>String(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
 function search(query,{level='',limit=20,exact=false}={}){const key=normalize(query);return entries.filter(e=>(!level||e.level===level)&&(!key||(exact?[e.term,e.meaning].some(s=>normalize(s)===key):normalize([e.term,e.meaning,e.topic,e.en,e.pt].join(' ')).includes(key)))).slice(0,limit);}
 const api={entries,normalize,search};root.StudyLexicon=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
