'use strict';
(()=>{
 let configured=false,revision=0,abort=null,audio=null,url=null;const voices=['zezinho','mariazinha'];
 function choice(){const id=globalThis.StudyAccount?.user()?.id||'guest';try{return JSON.parse(localStorage.getItem('studyia.voice.'+id)||'null')||{mode:'natural',character:'mariazinha'};}catch{return{mode:'natural',character:'mariazinha'};}}
 function stop(){revision++;abort?.abort();abort=null;if(audio){audio.pause();audio.removeAttribute('src');audio.load();audio=null;}if(url){URL.revokeObjectURL(url);url=null;}}
 async function play(text,lang,rate,onEnd,status){const pref=choice();if(!configured||pref.mode==='browser'||!globalThis.StudyAccount?.signedIn())return false;stop();const version=revision;abort=new AbortController();const current=abort;const timer=setTimeout(()=>current.abort(),30000);status.textContent='Preparando voz natural da IA…';try{const response=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':StudyAccount.csrf()},body:JSON.stringify({text,language:lang.slice(0,2),character:voices.includes(pref.character)?pref.character:'mariazinha',speed:Math.max(.5,Math.min(1.5,Number(rate)||1))}),signal:current.signal});if(!response.ok){const data=await response.json();throw Error(data.error||'Áudio indisponível.');}const blob=await response.blob();if(version!==revision)return true;url=URL.createObjectURL(blob);audio=new Audio(url);audio.onended=()=>{if(version!==revision)return;stop();status.textContent='';onEnd?.();};audio.onerror=()=>{if(version===revision){stop();status.textContent='Não foi possível reproduzir a voz natural. Tente novamente.';}};await audio.play();if(version===revision)status.textContent='Reproduzindo voz natural da IA…';}catch(error){if(version===revision){stop();status.textContent=error.name==='AbortError'?'Áudio interrompido. Tente novamente.':error.message;}}finally{clearTimeout(timer);}return true;}
 globalThis.StudyNaturalVoice={stop,play,choice,enabled:()=>configured&&choice().mode!=='browser'&&Boolean(globalThis.StudyAccount?.signedIn())};
 document.addEventListener('DOMContentLoaded',()=>{const box=document.createElement('article');box.className='connection-card';box.innerHTML='<h3>Voz da plataforma</h3><p>Escolha a voz das aulas, exemplos, dicionário e listening. A voz natural é gerada por IA a partir do texto e não utiliza seu microfone.</p><label>Leitura <select id="natural-voice-mode"><option value="natural">Voz natural com IA</option><option value="browser">Voz do navegador</option></select></label><label>Professor <select id="natural-voice-character"><option value="zezinho">Zezinho</option><option value="mariazinha">Mariazinha</option></select></label><button id="natural-voice-preview" type="button" class="button secondary">Ouvir voz escolhida</button><p id="natural-voice-status" role="status"></p>';document.querySelector('#settings').append(box);const status=box.querySelector('#natural-voice-status'),mode=box.querySelector('#natural-voice-mode'),character=box.querySelector('#natural-voice-character');function render(){const pref=choice();mode.value=pref.mode==='browser'?'browser':'natural';character.value=voices.includes(pref.character)?pref.character:'mariazinha';status.textContent=configured?'Voz natural disponível para contas conectadas.':'Voz natural aguardando configuração no servidor. A leitura atual usa a voz do navegador.';}function save(){stop();try{const id=StudyAccount.user()?.id||'guest';localStorage.setItem('studyia.voice.'+id,JSON.stringify({mode:mode.value,character:character.value}));status.textContent='Preferência de voz salva.';}catch{status.textContent='Não foi possível salvar sua preferência.';}}mode.onchange=save;character.onchange=save;box.querySelector('button').onclick=()=>{pauseScene();speak(StudyCurriculum.get('A1-001').example.en);};document.addEventListener('studyia:account',render);fetch('/api/speech').then(r=>r.json()).then(data=>{configured=Boolean(data.configured);render();}).catch(()=>{status.textContent='Não foi possível verificar a voz natural.';});render();});
 window.addEventListener('pagehide',stop);document.addEventListener('studyia:navigate',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
})();
