'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const steps=[
  ['#menu-toggle','Seu menu','Clique no logo para abrir ou recolher o menu. Aqui estão os atalhos principais da plataforma.'],
  ['#home .hero .button','Sua próxima aula','Continue de onde parou. As aulas são liberadas em sequência conforme você conclui as atividades e provas.'],
  ['.sidebar a[href="#dictionary"]','Dicionário','Pesquise palavras, veja o significado em português e exemplos de uso em inglês.'],
  ['.sidebar a[href="#conversation"]','Conversação com IA','Abra a área de prática para conversar e treinar a escuta com o professor IA.'],
  ['.sidebar a[href="#review"]','Revisão','Retome conteúdos que precisam de mais prática para reforçar seu aprendizado.'],
  ['.sidebar a[href="#account"]','Minha conta','Confira sua identificação e gerencie seu acesso. Seu progresso pertence à sua conta.']
 ];
 let layer=null,index=0,userId=null,checking=false,starting=false,previousFocus=null,inertNodes=[],menuWasOpen=false;
 const seen=new Set();
 function position(){if(!layer)return;const target=document.querySelector(steps[index][0]);if(!target||!target.getClientRects().length)return;const r=target.getBoundingClientRect(),spot=layer.querySelector('.tour-spot'),box=layer.querySelector('.tour-box'),svg=layer.querySelector('.tour-arrow');Object.assign(spot.style,{left:r.left-5+'px',top:r.top-5+'px',width:r.width+10+'px',height:r.height+10+'px'});const w=box.offsetWidth,h=box.offsetHeight,gap=28,pad=12,clamp=(n,min,max)=>Math.max(min,Math.min(max,n));const candidates=[{x:r.right+gap,y:clamp(r.top,pad,innerHeight-h-pad)},{x:r.left-w-gap,y:clamp(r.top,pad,innerHeight-h-pad)},{x:clamp(r.left,pad,innerWidth-w-pad),y:r.bottom+gap},{x:clamp(r.left,pad,innerWidth-w-pad),y:r.top-h-gap}];const chosen=candidates.find(p=>p.x>=pad&&p.y>=pad&&p.x+w<=innerWidth-pad&&p.y+h<=innerHeight-pad)||{x:pad,y:pad};Object.assign(box.style,{left:chosen.x+'px',top:chosen.y+'px'});const cx=r.left+r.width/2,cy=r.top+r.height/2;let sx=clamp(cx,chosen.x+12,chosen.x+w-12),sy=clamp(cy,chosen.y+12,chosen.y+h-12),ex=cx,ey=cy;if(chosen.x>=r.right){sx=chosen.x;ex=r.right+6;}else if(chosen.x+w<=r.left){sx=chosen.x+w;ex=r.left-6;}else if(chosen.y>=r.bottom){sy=chosen.y;ey=r.bottom+6;}else{sy=chosen.y+h;ey=r.top-6;}const line=svg.querySelector('line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);}
 function render(){const toggle=document.querySelector('#menu-toggle'),wantOpen=index!==1;if((toggle.getAttribute('aria-expanded')==='true')!==wantOpen)toggle.click();const [,title,description]=steps[index];layer.querySelector('small').textContent=`Passo ${index+1} de ${steps.length}`;layer.querySelector('h2').textContent=title;layer.querySelector('p').textContent=description.replace(/inglês/g,globalThis.StudyLanguage?.name||'inglês');layer.querySelector('#tour-prev').hidden=index===0;layer.querySelector('#tour-next').textContent=index===steps.length-1?'Concluir':'Próximo';document.querySelector(steps[index][0])?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});position();layer.querySelector('#tour-next').focus();}
 function close(){if(!layer)return;layer.remove();layer=null;document.body.classList.remove('tour-running');inertNodes.forEach(([node,value])=>node.inert=value);inertNodes=[];if((document.querySelector('#menu-toggle').getAttribute('aria-expanded')==='true')!==menuWasOpen)document.querySelector('#menu-toggle').click();previousFocus?.focus();}
 async function finish(){const buttons=layer.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await StudyAccount.request('onboarding',{});seen.add(userId);close();}catch{layer.querySelector('p').textContent='Não foi possível registrar o guia. Tente novamente para salvar sua escolha.';buttons.forEach(b=>b.disabled=false);}}
 function start(){if(layer||starting||!StudyAccount.signedIn())return;starting=true;userId=StudyAccount.user().id;previousFocus=document.activeElement;location.hash='home';requestAnimationFrame(()=>requestAnimationFrame(()=>{starting=false;if(!StudyAccount.signedIn()||StudyAccount.user().id!==userId)return;document.body.classList.add('tour-running');menuWasOpen=document.querySelector('#menu-toggle').getAttribute('aria-expanded')==='true';if(!menuWasOpen)document.querySelector('#menu-toggle').click();layer=document.createElement('div');layer.className='tour-layer';layer.innerHTML='<div class="tour-spot"></div><svg class="tour-arrow" aria-hidden="true"><defs><marker id="tour-arrowhead" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="#4caf45"/></marker></defs><line stroke="#4caf45" stroke-width="3" marker-end="url(#tour-arrowhead)"/></svg><section class="tour-box" role="dialog" aria-modal="true" aria-labelledby="tour-title" aria-describedby="tour-description"><small></small><h2 id="tour-title"></h2><p id="tour-description"></p><div class="tour-actions"><button id="tour-skip" class="reset">Pular guia</button><button id="tour-prev" class="button secondary">Anterior</button><button id="tour-next" class="button">Próximo</button></div></section>';inertNodes=[...document.body.children].filter(n=>!['SCRIPT','STYLE'].includes(n.tagName)).map(n=>[n,n.inert]);inertNodes.forEach(([n])=>n.inert=true);document.body.append(layer);index=0;layer.querySelector('#tour-next').onclick=()=>index===steps.length-1?finish():(index++,render());layer.querySelector('#tour-prev').onclick=()=>{index--;render();};layer.querySelector('#tour-skip').onclick=finish;layer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish();}if(e.key==='Tab'){const items=[...layer.querySelectorAll('button')].filter(b=>!b.hidden&&!b.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});render();}));}
 async function check(){if(!globalThis.StudyAccount?.ready()){setTimeout(refresh,250);return;}if(layer&&StudyAccount.user()?.id!==userId)close();const user=StudyAccount.user();if(!user||layer||starting||checking||seen.has(user.id))return;checking=true;try{const result=await StudyAccount.request('onboarding');if(StudyAccount.user()?.id!==user.id)return;if(result.seen)seen.add(user.id);else start();}catch{}finally{checking=false;}}
 const replay=document.createElement('button');replay.className='button secondary';replay.id='tour-replay';replay.textContent='Ver guia da plataforma';replay.addEventListener('click',start);document.querySelector('#settings').append(replay);
 function refresh(){replay.hidden=!globalThis.StudyAccount?.signedIn();check();}
 document.addEventListener('studyia:account',()=>setTimeout(refresh,150));window.addEventListener('load',()=>setTimeout(refresh,250));const observer=new ResizeObserver(position);steps.forEach(([selector])=>{const target=document.querySelector(selector);if(target)observer.observe(target);});window.addEventListener('resize',position);window.addEventListener('scroll',position,true);
});
