'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const steps=[
  ['#menu-toggle','Seu menu','Clique no logo para abrir ou recolher o menu. Aqui estão os atalhos principais da plataforma.'],
  ['#home .hero .button','Sua próxima aula','Continue de onde parou. As aulas são liberadas em sequência conforme você conclui as atividades e provas.'],
  ['.sidebar a[href="#dictionary"]','Dicionário','Pesquise palavras, veja o significado em português e exemplos de uso em inglês.'],
  ['.sidebar a[href="#conversation"]','Conversação com IA','Abra a área de prática para conversar e treinar a escuta com o professor IA.'],
  ['.sidebar a[href="#review"]','Revisão','Retome conteúdos que precisam de mais prática para reforçar seu aprendizado.'],
  ['.sidebar a[href="#account"]','Minha conta','Confira sua identificação e gerencie seu acesso. Seu progresso pertence à sua conta.']
 ];
 let layer=null,index=0,userId=null,checking=false,starting=false,previousFocus=null,inertNodes=[],menuWasOpen=false;
 const seen=new Set();
 function position(){if(!layer)return;const target=document.querySelector(steps[index][0]);if(!target||!target.getClientRects().length)return;const r=target.getBoundingClientRect(),spot=layer.querySelector('.tour-spot'),box=layer.querySelector('.tour-box'),arrow=layer.querySelector('.tour-arrow');Object.assign(spot.style,{left:r.left-5+'px',top:r.top-5+'px',width:r.width+10+'px',height:r.height+10+'px'});const w=box.offsetWidth,h=box.offsetHeight;let left=r.right+36,top=r.top;if(left+w>innerWidth-12){left=Math.max(12,Math.min(innerWidth-w-12,r.left));top=r.bottom+36;if(top+h>innerHeight-12)top=r.top-h-36;}top=Math.max(12,Math.min(innerHeight-h-12,top));Object.assign(box.style,{left:left+'px',top:top+'px'});const beside=left>=r.right;Object.assign(arrow.style,{left:(beside?r.right+12:Math.max(12,Math.min(innerWidth-40,r.left+r.width/2)))+'px',top:(beside?Math.max(12,Math.min(innerHeight-40,r.top+10)):top>r.bottom?r.bottom+9:r.top-34)+'px',transform:beside?'rotate(45deg)':top>r.bottom?'rotate(135deg)':'rotate(-45deg)'});}
 function render(){const [,title,description]=steps[index];layer.querySelector('small').textContent=`Passo ${index+1} de ${steps.length}`;layer.querySelector('h2').textContent=title;layer.querySelector('p').textContent=description;layer.querySelector('#tour-prev').hidden=index===0;layer.querySelector('#tour-next').textContent=index===steps.length-1?'Concluir':'Próximo';document.querySelector(steps[index][0])?.scrollIntoView({block:'nearest'});position();layer.querySelector('#tour-next').focus();}
 function close(){if(!layer)return;layer.remove();layer=null;inertNodes.forEach(([node,value])=>node.inert=value);inertNodes=[];if(!menuWasOpen&&document.querySelector('#menu-toggle').getAttribute('aria-expanded')==='true')document.querySelector('#menu-toggle').click();previousFocus?.focus();}
 async function finish(){const buttons=layer.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await StudyAccount.request('onboarding',{});seen.add(userId);close();}catch{layer.querySelector('p').textContent='Não foi possível registrar o guia. Tente novamente para salvar sua escolha.';buttons.forEach(b=>b.disabled=false);}}
 function start(){if(layer||starting||!StudyAccount.signedIn())return;starting=true;userId=StudyAccount.user().id;previousFocus=document.activeElement;location.hash='home';requestAnimationFrame(()=>requestAnimationFrame(()=>{starting=false;if(!StudyAccount.signedIn()||StudyAccount.user().id!==userId)return;menuWasOpen=document.querySelector('#menu-toggle').getAttribute('aria-expanded')==='true';if(!menuWasOpen)document.querySelector('#menu-toggle').click();layer=document.createElement('div');layer.className='tour-layer';layer.innerHTML='<div class="tour-spot"></div><div class="tour-arrow" aria-hidden="true"></div><section class="tour-box" role="dialog" aria-modal="true" aria-labelledby="tour-title" aria-describedby="tour-description"><small></small><h2 id="tour-title"></h2><p id="tour-description"></p><div class="tour-actions"><button id="tour-skip" class="reset">Pular guia</button><button id="tour-prev" class="button secondary">Anterior</button><button id="tour-next" class="button">Próximo</button></div></section>';inertNodes=[...document.body.children].filter(n=>!['SCRIPT','STYLE'].includes(n.tagName)).map(n=>[n,n.inert]);inertNodes.forEach(([n])=>n.inert=true);document.body.append(layer);index=0;layer.querySelector('#tour-next').onclick=()=>index===steps.length-1?finish():(index++,render());layer.querySelector('#tour-prev').onclick=()=>{index--;render();};layer.querySelector('#tour-skip').onclick=finish;layer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish();}if(e.key==='Tab'){const items=[...layer.querySelectorAll('button')].filter(b=>!b.hidden&&!b.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});render();}));}
 async function check(){if(!globalThis.StudyAccount?.ready()){setTimeout(refresh,250);return;}if(layer&&StudyAccount.user()?.id!==userId)close();const user=StudyAccount.user();if(!user||layer||starting||checking||seen.has(user.id))return;checking=true;try{const result=await StudyAccount.request('onboarding');if(StudyAccount.user()?.id!==user.id)return;if(result.seen)seen.add(user.id);else start();}catch{}finally{checking=false;}}
 const replay=document.createElement('button');replay.className='button secondary';replay.id='tour-replay';replay.textContent='Ver guia da plataforma';replay.addEventListener('click',start);document.querySelector('#settings').append(replay);
 function refresh(){replay.hidden=!globalThis.StudyAccount?.signedIn();check();}
 document.addEventListener('studyia:account',()=>setTimeout(refresh,150));window.addEventListener('load',()=>setTimeout(refresh,250));const observer=new ResizeObserver(position);steps.forEach(([selector])=>{const target=document.querySelector(selector);if(target)observer.observe(target);});window.addEventListener('resize',position);window.addEventListener('scroll',position,true);
});
