'use strict';
document.addEventListener('DOMContentLoaded', () => {
 const D=StudyData;const defaults={name:'',goal:'everyday',dailyGoal:3};
 let profile={...defaults},activity={};
 const settings=document.querySelector('#settings');
 const block=document.createElement('article');block.className='connection-card';
 block.innerHTML='<h3>Seu plano de estudo</h3><form id="profile-form"><label for="profile-name">Como podemos chamar você? <input id="profile-name" maxlength="40" autocomplete="given-name" placeholder="Seu nome (opcional)"></label><label for="profile-goal">Seu objetivo <select id="profile-goal"><option value="everyday">Conversas do dia a dia</option><option value="travel">Viagens</option><option value="work">Trabalho</option></select></label><label for="profile-daily">Meta diária <select id="profile-daily"><option value="3">3 atividades</option><option value="5">5 atividades</option><option value="10">10 atividades</option></select></label><button class="button">Salvar plano</button></form><p id="profile-status" role="status"></p>';
 settings.prepend(block);
 const status=block.querySelector('#profile-status');
 try{const saved=localStorage.getItem(D.keys.profile);if(saved)profile=D.profile(JSON.parse(saved));const days=localStorage.getItem(D.keys.activity);if(days)activity=D.activity(JSON.parse(days));}catch{status.textContent='Não foi possível recuperar todas as preferências. Você pode salvar um novo plano.';}
 block.querySelector('#profile-name').value=profile.name;block.querySelector('#profile-goal').value=profile.goal;block.querySelector('#profile-daily').value=profile.dailyGoal;
 const stats=document.createElement('section');stats.className='daily-dashboard';stats.setAttribute('aria-label','Sua meta diária');stats.innerHTML='<article><small>SEU PLANO</small><h3 id="profile-greeting"></h3><p id="profile-summary"></p><a href="#settings">Ajustar meu plano →</a></article><article><small>META DE HOJE</small><h3 id="daily-count"></h3><progress id="daily-bar"></progress><p id="daily-message" aria-live="polite"></p></article>';
 document.querySelector('#home .hero').after(stats);
 function render(){const today=activity[D.dayKey()]?.length||0;stats.querySelector('#profile-greeting').textContent=profile.name?`Vamos praticar, ${profile.name}?`:'Seu plano começa aqui.';stats.querySelector('#profile-summary').textContent=`${D.goals[profile.goal]} · ${profile.dailyGoal} atividades por dia`;stats.querySelector('#daily-count').textContent=`${today} de ${profile.dailyGoal} atividades`;stats.querySelector('#daily-bar').max=profile.dailyGoal;stats.querySelector('#daily-bar').value=Math.min(today,profile.dailyGoal);stats.querySelector('#daily-message').textContent=today>=profile.dailyGoal?'Meta de hoje concluída. Continue se quiser!':'Conclua exercícios, revisões ou trocas com o professor para avançar.';}
 function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{status.textContent='O navegador não permitiu salvar. As alterações valem nesta sessão.';return false;}}
 block.querySelector('#profile-form').addEventListener('submit',event=>{event.preventDefault();profile=D.profile({name:block.querySelector('#profile-name').value,goal:block.querySelector('#profile-goal').value,dailyGoal:Number(block.querySelector('#profile-daily').value)});const saved=persist(D.keys.profile,profile);if(saved)status.textContent='Plano salvo. Você pode alterá-lo quando quiser.';render();});
 function record(token){const day=D.dayKey();const tokens=activity[day]||[];if(tokens.includes(token)||tokens.length>=100)return;activity[day]=[...tokens,token];activity=Object.fromEntries(Object.entries(activity).sort(([a],[b])=>a.localeCompare(b)).slice(-90));persist(D.keys.activity,activity);render();}
 document.addEventListener('studyia:attempt',event=>{const {unit,index,correct}=event.detail||{};if(correct&&['introductions','numbers','cafe','listening'].includes(unit)&&Number.isInteger(index))record(`lesson-${unit}-${index}`);});
 document.addEventListener('studyia:activity',event=>{const token=event.detail?.token;if(typeof token==='string'&&/^[a-z0-9-]{1,80}$/.test(token))record(token);});
 window.addEventListener('focus',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});setInterval(render,60000);
 const backup=document.createElement('article');backup.className='connection-card';backup.innerHTML='<h3>Leve seu progresso com você</h3><p>Baixe uma cópia do perfil, aulas, revisão e atividades. O arquivo não inclui conversas, gravações ou chaves de IA.</p><button id="backup-export" class="button secondary">Baixar backup</button><label for="backup-file">Selecionar backup para restaurar <input id="backup-file" type="file" accept=".json,application/json"></label><p id="backup-preview" role="status"></p><button id="backup-import" class="button" hidden>Restaurar este backup</button><p id="backup-status" role="status"></p>';settings.append(backup);
 const feedback=backup.querySelector('#backup-status');let candidate=null;
 function snapshot(){const data={profile,activity,curriculum:{},introductions:[],numbers:[],cafe:[],listening:[],review:{pending:[],reviewed:0},vocabulary:[],appearance:JSON.parse(localStorage.getItem(D.keys.appearance)||'"system"')};for(const key of ['introductions','numbers','cafe','listening','review','vocabulary','curriculum']){const saved=localStorage.getItem(D.keys[key]);if(saved)data[key]=JSON.parse(saved);}return D.backup({format:'studyia-backup',version:4,data});}
 backup.querySelector('#backup-export').addEventListener('click',()=>{try{const data=snapshot();const file=new Blob([JSON.stringify({format:'studyia-backup',version:4,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'});const url=URL.createObjectURL(file);const link=document.createElement('a');link.href=url;link.download=`studyia-backup-${D.dayKey()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);feedback.textContent='Backup preparado para download.';}catch{feedback.textContent='Não foi possível exportar. Verifique se o armazenamento do navegador está disponível.';}});
 backup.querySelector('#backup-file').addEventListener('change',async event=>{candidate=null;backup.querySelector('#backup-import').hidden=true;backup.querySelector('#backup-preview').textContent='';const file=event.target.files[0];if(!file)return;try{if(file.size>200000)throw Error('Escolha um backup de até 200 KB.');candidate=D.backup(JSON.parse(await file.text()));backup.querySelector('#backup-preview').textContent=`Backup válido: ${candidate.profile.name||'sem nome'}, ${candidate.introductions.length+candidate.numbers.length+candidate.cafe.length+candidate.listening.length} exercícios concluídos, ${candidate.review.pending.length} revisões pendentes. Restaurar substituirá seu perfil e progresso atuais.`;backup.querySelector('#backup-import').hidden=false;feedback.textContent='Revise o resumo antes de restaurar.';}catch(error){feedback.textContent=error instanceof SyntaxError?'O arquivo não contém JSON válido.':error.message;}});
 backup.querySelector('#backup-import').addEventListener('click',()=>{if(!candidate||!confirm('Substituir seu perfil e progresso pelos dados deste backup?'))return;const previous={};try{for(const key of Object.keys(D.keys))previous[key]=localStorage.getItem(D.keys[key]);for(const key of Object.keys(D.keys))localStorage.setItem(D.keys[key],JSON.stringify(candidate[key]));location.reload();}catch{let recovered=true;for(const[key,value]of Object.entries(previous)){try{if(value===null)localStorage.removeItem(D.keys[key]);else localStorage.setItem(D.keys[key],value);}catch{recovered=false;}}feedback.textContent=recovered?'Não foi possível restaurar. Os dados anteriores foram preservados.':'O armazenamento falhou durante a restauração. Preserve seu arquivo de backup e tente novamente.';}});
 const tabs=document.createElement('nav');tabs.className='subnav';tabs.setAttribute('aria-label','Preferências');
 const existing=document.createElement('div');existing.append(settings.querySelector('#reset'),settings.querySelector('#storage-message'));
 const connection=document.querySelector('#ai-connection').closest('article');
 const panels=[['Meu plano',block],['Progresso',existing],['Professor IA',connection],['Backup',backup]].map(([name,node],index)=>{const panel=document.createElement('div');panel.id=`settings-panel-${index}`;panel.className='activity-panel';panel.append(node);settings.append(panel);const button=document.createElement('button');button.textContent=name;button.setAttribute('aria-controls',panel.id);button.addEventListener('click',()=>select(index));tabs.append(button);return{panel,button};});
 function select(index){panels.forEach((entry,i)=>{entry.panel.hidden=i!==index;entry.button.setAttribute('aria-pressed',String(i===index));});}
 settings.querySelector('h2').after(tabs);select(0);render();
});
