'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const root=document.createElement('article');root.className='connection-card';root.innerHTML='<h3>Sua evolução nas atividades</h3><p>Veja o que concluiu. Estes números indicam atividades feitas, não certificação de nível nem nota de fluência.</p><div id="progress-units"></div><p id="progress-total" role="status"></p>';
 document.querySelector('#settings-panel-1').prepend(root);
 const units=[['introductions','Apresentação pessoal',3,'lesson'],['numbers','Números e horários',4,'numbers'],['cafe','Na cafeteria',3,'cafe'],['listening','Compreensão auditiva',3,'studio']];
 function render(){const list=root.querySelector('#progress-units');list.replaceChildren();let total=0;for(const[key,title,max,route]of units){let count=0;try{count=StudyData.lesson(JSON.parse(localStorage.getItem(StudyData.keys[key])||'[]'),max).length;}catch{}total+=count;const item=document.createElement('article');item.className='progress-row';const link=document.createElement('a');link.href='#'+route;link.textContent=title;const label=document.createElement('span');label.textContent=`${count} de ${max}`;const bar=document.createElement('progress');bar.max=max;bar.value=count;bar.setAttribute('aria-label',`${title}: ${count} de ${max}`);item.append(link,label,bar);list.append(item);}root.querySelector('#progress-total').textContent=`${total} de 13 atividades concluídas.`;}
 const course=document.createElement('article');course.className='connection-card';root.after(course);
 function courseProgress(){let saved={};try{saved=StudyData.curriculum(JSON.parse(localStorage.getItem(StudyData.keys.curriculum)||'{}'));}catch{}course.replaceChildren();const heading=document.createElement('h3');heading.textContent='Evolução avaliada por provas';course.append(heading);const estimate=document.createElement('p');estimate.textContent=StudyJourney.get().pending?'Diagnóstico inicial pendente.':'Nível estimado: '+StudyAssessment.currentLevel(StudyJourney.get());course.append(estimate);for(const level of StudyCurriculum.levels){const lessons=StudyCurriculum.lessons.filter(l=>l.level===level);const p=document.createElement('p');const done=lessons.filter(l=>saved[l.id]?.length===3).length;p.textContent=lessons.length?`${level}: ${done} de ${lessons.length} aulas praticadas`:`${level}: em preparação`;course.append(p);const state=StudyJourney.get(),passed=Array.from({length:15},(_,i)=>StudyAssessment.passed(state,level,i+1)).filter(Boolean).length,score=StudyAssessment.performance(state,level);const label=document.createElement('p');label.textContent=passed+' de 15 blocos aprovados · desempenho acumulado '+score+'%';const bar=document.createElement('progress');bar.max=100;bar.value=score;bar.setAttribute('aria-label',level+': desempenho acumulado '+score+'%');course.append(label,bar);}const link=document.createElement('a');link.href='#catalog';link.textContent='Abrir meu curso →';course.append(link);}
 document.addEventListener('studyia:progress',()=>{render();courseProgress();});new MutationObserver(render).observe(document.querySelector('#progress'),{childList:true});window.addEventListener('focus',()=>{render();courseProgress();});render();courseProgress();
});
