'use strict';
(() => {
  const catalog = {
    'introductions-0': {question:'Como dizer “Meu nome é Ana”?',answers:['my name is ana'],explanation:'My name is Ana. — Meu nome é Ana.',unit:'Apresentação pessoal'},
    'introductions-1': {question:'Como perguntar o nome de alguém?',answers:['what is your name',"what's your name"],explanation:'What is your name? — Qual é o seu nome?',unit:'Apresentação pessoal'},
    'introductions-2': {question:'Como dizer “Prazer em conhecer você”?',answers:['nice to meet you'],explanation:'Nice to meet you. — Prazer em conhecer você.',unit:'Apresentação pessoal'},
    'numbers-0': {question:'Escreva o número 7 em inglês.',answers:['seven'],explanation:'Seven significa sete.',unit:'Números e horários'},
    'numbers-1': {question:'Escreva o número 12 em inglês.',answers:['twelve'],explanation:'Twelve significa doze.',unit:'Números e horários'},
    'numbers-2': {question:'Como dizer “São três horas”?',answers:["it's three o'clock","it is three o'clock"],explanation:'It’s three o’clock. — São três horas exatas.',unit:'Números e horários'},
    'numbers-3': {question:'Como dizer “São nove horas”?',answers:["it's nine o'clock","it is nine o'clock"],explanation:'It’s nine o’clock. — São nove horas exatas.',unit:'Números e horários'}
  };
  const key='studyia.review.v1';let pending=[],reviewed=0,active=null,answered=false;
  const root=document.createElement('section');root.id='review';root.className='module lesson';
  root.innerHTML='<p class="eyebrow">RELEMBRE E FORTALEÇA</p><h2>Um pouco de revisão.</h2><p>Os exercícios que você errar nas aulas aparecem aqui. Acertar durante a aula mantém o item nesta revisão, para você praticar novamente.</p><div class="review-summary"><article><strong id="review-count">0</strong><span>itens para revisar</span></article><article><strong id="review-total">0</strong><span>revisões concluídas</span></article></div><div id="review-empty"><h3>Seu próximo passo está nas aulas.</h3><p>Ainda não há itens pendentes. Continue aprendendo ou revisite uma unidade.</p><a href="#units" class="button">Explorar aulas →</a></div><div id="review-practice" hidden><p id="review-unit" class="eyebrow"></p><h3 id="review-question"></h3><form id="review-form"><label for="review-answer">Sua resposta em inglês</label><input id="review-answer" maxlength="100" required autocomplete="off"><button class="button">Conferir revisão</button></form><p id="review-feedback" role="status"></p><button id="review-hint" class="reset">Mostrar exemplo</button><button id="review-next" class="button secondary" hidden>Próxima revisão →</button></div><p id="review-storage" role="status"></p><button id="review-clear" class="reset">Limpar histórico de revisão</button>';
  document.querySelector('#reset').before(root);
  try{const saved=JSON.parse(localStorage.getItem(key)||'{}');if(Array.isArray(saved.pending))pending=[...new Set(saved.pending.filter(id=>Object.hasOwn(catalog,id)))];if(Number.isSafeInteger(saved.reviewed)&&saved.reviewed>=0)reviewed=saved.reviewed;}catch{root.querySelector('#review-storage').textContent='Não foi possível recuperar a revisão. Você pode continuar.';}
  function save(){try{localStorage.setItem(key,JSON.stringify({pending,reviewed}));}catch{root.querySelector('#review-storage').textContent='Não foi possível salvar. Sua revisão fica disponível nesta sessão.';}}
  function summary(){root.querySelector('#review-count').textContent=pending.length;root.querySelector('#review-total').textContent=reviewed;const badge=document.querySelector('#home-review-count');if(badge)badge.textContent=pending.length?`${pending.length} ${pending.length===1?'item para revisar':'itens para revisar'}`:'Nenhuma revisão pendente';}
  function render(){active=pending[0]||null;answered=false;summary();root.querySelector('#review-empty').hidden=Boolean(active);root.querySelector('#review-practice').hidden=!active;root.querySelector('#review-feedback').textContent='';root.querySelector('#review-next').hidden=true;root.querySelector('#review-hint').disabled=false;root.querySelector('#review-answer').value='';root.querySelector('#review-answer').disabled=false;root.querySelector('#review-form button').disabled=false;if(active){root.querySelector('#review-unit').textContent=catalog[active].unit;root.querySelector('#review-question').textContent=catalog[active].question;}}
  document.addEventListener('studyia:attempt',event=>{const{unit,index,correct}=event.detail||{};const id=`${unit}-${index}`;if(correct||!Object.hasOwn(catalog,id))return;if(!pending.includes(id)){pending.push(id);save();if(!active&&!answered)render();else summary();}});
  const normalize=text=>text.trim().toLowerCase().replace(/[’‘]/g,"'").replace(/[.!?]+$/g,'').replace(/\s+/g,' ');
  root.querySelector('#review-form').addEventListener('submit',event=>{event.preventDefault();if(!active||answered)return;const answer=normalize(root.querySelector('#review-answer').value);if(!answer)return;if(catalog[active].answers.includes(answer)){pending=pending.filter(id=>id!==active);reviewed++;answered=true;save();summary();root.querySelector('#review-feedback').textContent=`Muito bem! ${catalog[active].explanation}`;root.querySelector('#review-answer').disabled=true;root.querySelector('#review-form button').disabled=true;root.querySelector('#review-hint').disabled=true;root.querySelector('#review-next').hidden=false;}else{root.querySelector('#review-feedback').textContent='Tente novamente. Você pode consultar o exemplo antes de responder.';}});
  root.querySelector('#review-hint').addEventListener('click',()=>{if(active)root.querySelector('#review-feedback').textContent=catalog[active].explanation;});
  root.querySelector('#review-next').addEventListener('click',()=>{render();if(active)root.querySelector('#review-answer').focus();});
  root.querySelector('#review-clear').addEventListener('click',()=>{if(!confirm('Limpar os itens pendentes e o histórico de revisão? O progresso das aulas será mantido.'))return;pending=[];reviewed=0;save();render();});
  document.addEventListener('DOMContentLoaded',summary);render();
})();
