'use strict';
(() => {
 const words=[['Hello!','Olá!','Hello, Ana!'],['My name is…','Meu nome é…','My name is Samuel.'],['What is your name?','Qual é o seu nome?','Hello! What is your name?'],['Nice to meet you.','Prazer em conhecer você.','Nice to meet you, Ana.'],['Seven','Sete','Seven coffees, please.'],['Twelve','Doze',"It's twelve o'clock."],['What time is it?','Que horas são?',"What time is it? It's three o'clock."],["O’clock",'Usado para indicar horas exatas',"It's nine o'clock."],['A coffee','Um café','I would like a coffee, please.'],['Please','Por favor','A coffee, please.'],['No, thank you.','Não, obrigado.','Anything else? No, thank you.'],['How much is it?','Quanto custa?','A coffee, please. How much is it?']];
 let favorites=[];try{favorites=StudyData.lesson(JSON.parse(localStorage.getItem(StudyData.keys.vocabulary)||'[]'),words.length);}catch{}
 let onlyFavorites=false,page=0,deck=words.map((_,i)=>i),position=0,revealed=false,session=new Set();
 const root=document.createElement('section');root.id='vocabulary';root.className='module lesson';root.innerHTML='<a href="#units" class="reset">← Voltar à trilha</a><p class="eyebrow">PALAVRAS PARA LEVAR COM VOCÊ</p><h2>Seu vocabulário.</h2><nav class="subnav" aria-label="Atividades de vocabulário"><button aria-pressed="true">Biblioteca</button><button aria-pressed="false">Cartões</button></nav><div id="vocab-library"><label for="vocab-search">Buscar palavra ou significado <input id="vocab-search" type="search" maxlength="80" placeholder="Ex.: coffee ou café"></label><button id="vocab-favorites" class="button secondary" aria-pressed="false">Só favoritos</button><p id="vocab-result" role="status"></p><div id="vocab-list"></div><div class="vocab-pagination"><button id="vocab-prev" class="button secondary">← Anterior</button><span id="vocab-page"></span><button id="vocab-next" class="button secondary">Próxima →</button></div></div><div id="vocab-flash" hidden><label for="flash-deck">Escolha seus cartões <select id="flash-deck"><option value="all">Todos os termos</option><option value="favorites">Meus favoritos</option></select></label><p id="flash-counter" class="eyebrow"></p><div class="flash-card"><h3 id="flash-word"></h3><p id="flash-meaning" hidden></p><p id="flash-example" hidden></p></div><button id="flash-reveal" class="button">Revelar significado</button><button id="flash-audio" class="button secondary">🔊 Ouvir</button><button id="flash-known" class="button secondary" disabled>Lembrei desta palavra</button><button id="flash-next" class="reset">Próximo cartão →</button><p id="flash-status" role="status"></p><p class="muted">Marcar uma palavra conta como prática na meta diária, uma vez por termo por dia. Isso não comprova domínio do vocabulário.</p></div><p id="vocab-storage" role="status"></p>';
 document.querySelector('#reset').before(root);
 function save(){try{localStorage.setItem(StudyData.keys.vocabulary,JSON.stringify(favorites));}catch{root.querySelector('#vocab-storage').textContent='Não foi possível salvar os favoritos. Eles ficam nesta sessão.';}}
 const normalize=text=>text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 function list(){const query=normalize(root.querySelector('#vocab-search').value);const ids=words.map((_,i)=>i).filter(i=>(!onlyFavorites||favorites.includes(i))&&normalize(words[i].join(' ')).includes(query));const pages=Math.max(1,Math.ceil(ids.length/4));page=Math.min(page,pages-1);const container=root.querySelector('#vocab-list');container.replaceChildren();ids.slice(page*4,page*4+4).forEach(id=>{const card=document.createElement('article');card.className='vocab-entry';const title=document.createElement('h3');title.textContent=words[id][0];const meaning=document.createElement('p');meaning.textContent=words[id][1];const example=document.createElement('p');example.className='muted';example.textContent=words[id][2];const audio=document.createElement('button');audio.className='listen';audio.textContent='🔊 Ouvir';audio.setAttribute('aria-label',`Ouvir ${words[id][0]}`);audio.addEventListener('click',()=>{pauseScene();speak(words[id][0]);});const favorite=document.createElement('button');favorite.className='listen';favorite.textContent=favorites.includes(id)?'★ Salvo':'☆ Favoritar';favorite.setAttribute('aria-label',`Favoritar ${words[id][0]}`);favorite.setAttribute('aria-pressed',String(favorites.includes(id)));favorite.addEventListener('click',()=>{favorites=favorites.includes(id)?favorites.filter(n=>n!==id):[...favorites,id];save();list();if(root.querySelector('#flash-deck').value==='favorites')buildDeck();});card.append(title,meaning,example,audio,favorite);container.append(card);});root.querySelector('#vocab-result').textContent=ids.length?`${ids.length} termos encontrados`:'Nenhum termo encontrado. Tente outra busca ou salve favoritos.';root.querySelector('#vocab-page').textContent=`${page+1} / ${pages}`;root.querySelector('#vocab-prev').disabled=page===0;root.querySelector('#vocab-next').disabled=page===pages-1;}
 root.querySelector('#vocab-search').addEventListener('input',()=>{page=0;list();});root.querySelector('#vocab-favorites').addEventListener('click',()=>{onlyFavorites=!onlyFavorites;page=0;root.querySelector('#vocab-favorites').setAttribute('aria-pressed',String(onlyFavorites));list();});root.querySelector('#vocab-prev').addEventListener('click',()=>{page--;list();});root.querySelector('#vocab-next').addEventListener('click',()=>{page++;list();});
 function flash(){revealed=false;const id=deck[position];const empty=id===undefined;root.querySelector('#flash-counter').textContent=empty?'SEM CARTÕES':`CARTÃO ${position+1} DE ${deck.length}`;root.querySelector('#flash-word').textContent=empty?'Salve alguns favoritos para praticar.':words[id][0];root.querySelector('#flash-meaning').hidden=true;root.querySelector('#flash-example').hidden=true;['#flash-reveal','#flash-audio','#flash-next'].forEach(selector=>root.querySelector(selector).disabled=empty);root.querySelector('#flash-known').disabled=true;root.querySelector('#flash-status').textContent=`${session.size} termos praticados nesta sessão.`;}
 function buildDeck(){deck=root.querySelector('#flash-deck').value==='favorites'?[...favorites]:words.map((_,i)=>i);position=0;flash();}
 root.querySelector('#flash-deck').addEventListener('change',()=>{pauseScene();buildDeck();});root.querySelector('#flash-reveal').addEventListener('click',()=>{const id=deck[position];if(id===undefined)return;revealed=true;root.querySelector('#flash-meaning').textContent=words[id][1];root.querySelector('#flash-example').textContent=words[id][2];root.querySelector('#flash-meaning').hidden=false;root.querySelector('#flash-example').hidden=false;root.querySelector('#flash-known').disabled=session.has(id);});root.querySelector('#flash-audio').addEventListener('click',()=>{if(deck[position]!==undefined){pauseScene();speak(words[deck[position]][0]);}});root.querySelector('#flash-known').addEventListener('click',()=>{const id=deck[position];if(!revealed||id===undefined||session.has(id))return;session.add(id);document.dispatchEvent(new CustomEvent('studyia:activity',{detail:{token:`flashcard-${id}`}}));root.querySelector('#flash-known').disabled=true;root.querySelector('#flash-status').textContent=`${session.size} termos praticados nesta sessão.`;});root.querySelector('#flash-next').addEventListener('click',()=>{pauseScene();if(deck.length){position=(position+1)%deck.length;flash();}});
 root.querySelectorAll('.subnav button').forEach((button,index)=>button.addEventListener('click',()=>{pauseScene();root.querySelector('#vocab-library').hidden=index!==0;root.querySelector('#vocab-flash').hidden=index!==1;root.querySelectorAll('.subnav button').forEach((tab,i)=>tab.setAttribute('aria-pressed',String(i===index)));}));list();flash();
})();
