import {randomBytes,randomUUID,createHash,scrypt,timingSafeEqual} from 'node:crypto';import {promisify} from 'node:util';
const derive=promisify(scrypt),token=()=>randomBytes(32).toString('base64url');export const digest=value=>createHash('sha256').update(value).digest('hex');
export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
export function email(value){if(typeof value!=='string'||value.length>254||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new HttpError(400,'Informe um email válido.');return value.trim().toLowerCase();}
const name=value=>{if(typeof value!=='string'||value.trim().length<2||value.length>80)throw new HttpError(400,'Informe um nome entre 2 e 80 caracteres.');return value.trim();};
async function passwordHash(password){if(typeof password!=='string'||password.length<12||password.length>128)throw new HttpError(400,'Use uma senha entre 12 e 128 caracteres.');const salt=randomBytes(16).toString('hex');return `scrypt$${salt}$${(await derive(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024})).toString('hex')}`;}
async function matches(password,stored){if(typeof password!=='string'||password.length>128)return false;const [,salt,hex]=stored.split('$'),key=await derive(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024}),expected=Buffer.from(hex,'hex');return expected.length===key.length&&timingSafeEqual(key,expected);}
export function accounts(db){const user=u=>({id:u.id,email:u.email,name:u.name,role:u.role}),cookie=req=>(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('studyia_session='))?.slice(16);
 async function company(){return(await db.query('SELECT name FROM company WHERE id=$1',['primary'])).rows[0]?.name||null;}
 async function session(req){const raw=cookie(req);if(!raw||raw.length>100)return null;const row=(await db.query('SELECT u.*,s.csrf FROM sessions s JOIN users u ON u.id=s.user_id WHERE token_hash=$1 AND expires>$2',[digest(raw),Date.now()])).rows[0];return row?{user:user(row),csrf:row.csrf}:null;}
 async function requireUser(req){const s=await session(req);if(!s)throw new HttpError(401,'Entre na sua conta para continuar.');return s;}
 async function requireAdmin(req){const s=await requireUser(req);if(s.user.role!=='admin')throw new HttpError(403,'Acesso exclusivo do administrador.');return s;}
 async function signIn(res,u){await db.query('DELETE FROM sessions WHERE expires<=$1',[Date.now()]);const raw=token(),csrf=token();await db.query('INSERT INTO sessions VALUES($1,$2,$3,$4)',[digest(raw),u.id,csrf,Date.now()+12*3600000]);res.setHeader('Set-Cookie',`studyia_session=${raw}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200`);return{user:user(u),csrf,company:await company()};}
 async function setup(body,res){const companyName=name(body.company),userName=name(body.name),address=email(body.email),hash=await passwordHash(body.password),id=randomUUID();return db.transaction(async()=>{await db.query('SELECT pg_advisory_xact_lock(48151702)');if(await company())throw new HttpError(409,'A empresa já foi configurada.');await db.query('INSERT INTO company VALUES($1,$2)',['primary',companyName]);await db.query('INSERT INTO users(id,company_id,email,name,password,role) VALUES($1,$2,$3,$4,$5,$6)',[id,'primary',address,userName,hash,'admin']);return signIn(res,{id,email:address,name:userName,role:'admin'});});}
 async function login(body,res){const address=email(body.email),row=(await db.query('SELECT * FROM users WHERE email=$1',[address])).rows[0],dummy='scrypt$00000000000000000000000000000000$'+'00'.repeat(64);if(!await matches(body.password,row?.password||dummy)||!row)throw new HttpError(401,'Email ou senha incorretos.');return signIn(res,row);}
 async function invite(req,body){const s=await requireAdmin(req),address=email(body.email),raw=token();await db.transaction(async()=>{if((await db.query('SELECT id FROM users WHERE email=$1',[address])).rows.length)throw new HttpError(409,'Este usuário já possui conta.');await db.query('DELETE FROM invitations WHERE email=$1 OR expires<=$2',[address,Date.now()]);await db.query('INSERT INTO invitations VALUES($1,$2,$3,$4)',[digest(raw),address,Date.now()+72*3600000,s.user.id]);});return{token:raw,email:address,expiresInHours:72};}
 async function accept(body,res){if(typeof body.token!=='string'||body.token.length>100)throw new HttpError(400,'Convite inválido.');const userName=name(body.name),hash=await passwordHash(body.password),id=randomUUID();return db.transaction(async()=>{const inv=(await db.query('SELECT * FROM invitations WHERE token_hash=$1 AND expires>$2 FOR UPDATE',[digest(body.token),Date.now()])).rows[0];if(!inv)throw new HttpError(400,'Convite inválido ou expirado.');await db.query('INSERT INTO users(id,company_id,email,name,password,role) VALUES($1,$2,$3,$4,$5,$6)',[id,'primary',inv.email,userName,hash,'student']);await db.query('DELETE FROM invitations WHERE token_hash=$1',[digest(body.token)]);return signIn(res,{id,email:inv.email,name:userName,role:'student'});});}
 async function logout(req,res){const raw=cookie(req);if(raw)await db.query('DELETE FROM sessions WHERE token_hash=$1',[digest(raw)]);res.setHeader('Set-Cookie','studyia_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');}
 return{company,session,requireUser,requireAdmin,setup,login,invite,accept,logout};}
