import {accounts,HttpError} from './accounts.mjs';import {learning} from './learning.mjs';import {courses} from './languages.mjs';
export function companyApi(db){const auth=accounts(db),english=learning(db),byLanguage=Object.fromEntries(Object.keys(courses).map(code=>[code,learning(db,code)])),limits=new Map();
 async function handle(req,res,url,json){if(!url.pathname.startsWith('/api/company/'))return false;try{const session=await auth.session(req);if(req.method!=='GET'){if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`)throw new HttpError(403,'Origem não autorizada.');if(session&&req.headers['x-csrf-token']!==session.csrf)throw new HttpError(403,'Sessão inválida. Recarregue a página.');if(req.headers['content-type']!=='application/json')throw new HttpError(415,'Envie JSON.');}let body={};if(req.method==='POST'){let raw='';for await(const chunk of req){raw+=chunk.toString();if(Buffer.byteLength(raw)>16000)throw new HttpError(413,'Solicitação muito grande.');}try{body=JSON.parse(raw);}catch{throw new HttpError(400,'JSON inválido.');}if(!body||typeof body!=='object'||Array.isArray(body))throw new HttpError(400,'Solicitação inválida.');}
 const key=req.method+' '+url.pathname;let value;
 if(key==='GET /api/company/session')value={available:true,development:db.development===true,company:await auth.company(),setupRequired:!await auth.company(),language:session?((await db.query('SELECT language FROM language_selection WHERE user_id=$1',[session.user.id])).rows[0]?.language||'en'):'en',user:session?.user||null,csrf:session?.csrf||null};
 else if(['POST /api/company/setup','POST /api/company/login','POST /api/company/accept'].includes(key)){const ip=req.socket.remoteAddress,now=Date.now();for(const[k,v]of limits)if(now-v.start>60000)limits.delete(k);if(limits.size>1000)throw new HttpError(429,'Aguarde antes de tentar novamente.');const limit=limits.get(ip)||{start:now,count:0};if(++limit.count>10)throw new HttpError(429,'Muitas tentativas. Aguarde um minuto.');limits.set(ip,limit);value=await auth[key.endsWith('setup')?'setup':key.endsWith('login')?'login':'accept'](body,res);}
 else if(key==='POST /api/company/logout'){await auth.requireUser(req);await auth.logout(req,res);value={ok:true};}
 else if(key==='POST /api/company/invite')value=await auth.invite(req,body);
 else if(key==='GET /api/company/report'){await auth.requireAdmin(req);const code=url.searchParams.get('language')||'en';if(!Object.hasOwn(byLanguage,code))throw new HttpError(400,'Idioma inválido.');value={users:await byLanguage[code].report()};}
 else{const user=(await auth.requireUser(req)).user;const language=body.language||url.searchParams.get('language')||'en';if(!Object.hasOwn(byLanguage,language))throw new HttpError(400,'Idioma inválido.');const course=byLanguage[language];if(key==='POST /api/company/language'){await db.query('INSERT INTO language_selection(user_id,language) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET language=excluded.language',[user.id,language]);value={language};}else if(key==='GET /api/company/onboarding')value={seen:Boolean((await db.query('SELECT user_id FROM onboarding WHERE user_id=$1',[user.id])).rows.length)};else if(key==='POST /api/company/onboarding'){await db.query('INSERT INTO onboarding(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING',[user.id]);value={seen:true};}else if(key==='GET /api/company/learning')value=await course.get(user.id);else if(key==='POST /api/company/entry')value=await course.entry(user.id,body.level);else if(key==='POST /api/company/stage')value=await course.stage(user.id,body);else if(key==='POST /api/company/answer')value=await course.answer(user.id,body);else if(key==='POST /api/company/retry')value=await course.draft(user.id,body.examId,true);else if(key==='POST /api/company/finish')value=await course.finish(user.id,body.examId);else throw new HttpError(404,'Recurso não encontrado.');}json(res,200,value);
 }catch(error){json(res,error instanceof HttpError?error.status:503,{error:error instanceof HttpError?error.message:'Serviço temporariamente indisponível. Nenhuma aprovação foi registrada.'});}return true;}
 return{handle,auth,course:english,forLanguage:language=>language==='es'?spanish:english};}
