import {randomUUID} from 'node:crypto';import Assessment from '../assessment.js';import English from '../curriculum.js';import {courses} from './languages.mjs';import Practice from '../language-practice.js';import {HttpError} from './accounts.mjs';
export function learning(database,language='en',{essayEvaluator}={}){
 if(!Object.hasOwn(courses,language))throw new HttpError(400,'Idioma inválido.');const C=courses[language],A=language!=='en'?Assessment.create(C,language):Assessment;
 const db=language!=='en'?{...database,query:(sql,params)=>database.query(sql.replace(/\b(learner_state|lesson_progress|exam_attempts|exam_answers)\b/g,language+'_$1'),params)}:database;

 async function read(id){const profile=(await db.query('SELECT declared,entry,pending FROM learner_state WHERE user_id=$1',[id])).rows[0]||A.defaults(),journey={declared:profile.declared,entry:profile.entry,pending:profile.pending,results:{},draft:null},curriculum={};for(const r of(await db.query('SELECT lesson_id,stage FROM lesson_progress WHERE user_id=$1 ORDER BY lesson_id,stage',[id])).rows)(curriculum[r.lesson_id]??=[]).push(r.stage);const attempts=(await db.query("SELECT * FROM exam_attempts WHERE user_id=$1 AND status IN ('completed','active') ORDER BY created_at,id",[id])).rows;for(const a of attempts){if(a.status==='active'){const marks=Array(10).fill(null);for(const r of(await db.query('SELECT question_index,mark FROM exam_answers WHERE attempt_id=$1',[a.id])).rows)marks[r.question_index]=r.mark;journey.draft={id:a.exam_id,marks};}else{const old=journey.results[a.exam_id];journey.results[a.exam_id]={score:a.exam_id.startsWith('block-')?Math.max(a.score,old?.score??0):a.score,attempts:(old?.attempts??0)+1,date:new Date(a.finished_at).toISOString()};}}return{journey,curriculum};}
 async function profile(id,journey){await db.query('INSERT INTO learner_state(user_id,declared,entry,pending) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET declared=excluded.declared,entry=excluded.entry,pending=excluded.pending',[id,journey.declared,journey.entry,journey.pending]);}
 const locked=(id,fn)=>db.transaction(async()=>{await db.lockUser(id);return fn();});
 async function entry(id,level){return locked(id,async()=>{const state=await get(id);state.journey=A.choose(state.journey,level);await profile(id,state.journey);await db.query("UPDATE exam_attempts SET status='abandoned' WHERE user_id=$1 AND status='active'",[id]);return get(id);});}
 async function stage(id,body){return locked(id,async()=>{const state=await get(id),lesson=C.get(body.lessonId),access=A.accessLesson(body.lessonId,state.journey,state.curriculum);if(!access.allowed)throw new HttpError(409,access.reason);if(!Number.isInteger(body.stage)||body.stage<0||body.stage>2)throw new HttpError(400,'Etapa inválida.');if(body.stage<2){if(typeof body.answer!=='number'||body.answer!==lesson.questions[body.stage].answer)throw new HttpError(400,'Revise sua resposta.');}else if(!Practice.valid(body.text,lesson.vocabulary,language,lesson.example.en))throw new HttpError(400,'Pratique uma frase com o vocabulário da aula.');await db.query('INSERT INTO lesson_progress(user_id,lesson_id,stage) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[id,lesson.id,body.stage]);return get(id);});}
 async function active(id,examId,restart=false){const state=await get(id);if(!A.accessExam(examId,state.journey,state.curriculum))throw new HttpError(409,'Prova bloqueada. Conclua os pré-requisitos.');let attempt=(await db.query("SELECT id,exam_id FROM exam_attempts WHERE user_id=$1 AND status='active'",[id])).rows[0];if(restart||attempt?.exam_id!==examId){await db.query("UPDATE exam_attempts SET status='abandoned' WHERE user_id=$1 AND status='active'",[id]);attempt={id:randomUUID(),exam_id:examId};await db.query("INSERT INTO exam_attempts(id,user_id,exam_id,status) VALUES($1,$2,$3,'active')",[attempt.id,id,examId]);}return{state:await get(id),attempt};}
 async function draft(id,examId,restart=false){return locked(id,async()=>{await active(id,examId,restart);return get(id);});}
 async function answer(id,body){return locked(id,async()=>{if(Object.hasOwn(body,'mark')||Object.hasOwn(body,'score'))throw new HttpError(400,'Notas são calculadas pelo servidor.');const q=A.exam(body.examId)?.questions[body.index];if(!q||q.type==='pronunciation'||!Number.isInteger(body.index)||!['string','number'].includes(typeof body.answer)||String(body.answer).length>(q.type==='essay'?2000:1000))throw new HttpError(400,'Resposta inválida.');const {state,attempt}=await active(id,body.examId);if(state.journey.draft.marks.findIndex(n=>n===null)!==body.index)throw new HttpError(409,'Responda a questão atual.');if(q.type==='essay'){if(typeof body.answer!=='string')throw new HttpError(400,'Escreva sua redação em inglês.');if(!essayEvaluator)throw new HttpError(503,'Correção de redação indisponível.');const result=await essayEvaluator(q,body.answer);if(![0,100].includes(result.mark))throw new HttpError(503,'Correção inválida.');await db.query('INSERT INTO exam_answers(attempt_id,question_index,mark,source,answer_text,feedback) VALUES($1,$2,$3,$4,$5,$6)',[attempt.id,body.index,result.mark,q.type,body.answer,JSON.stringify(result)]);return{...await get(id),essayFeedback:result};}await db.query('INSERT INTO exam_answers(attempt_id,question_index,mark,source) VALUES($1,$2,$3,$4)',[attempt.id,body.index,A.grade(q,body.answer),q.type]);return get(id);});}
 async function audioReady(id,examId,index){return locked(id,async()=>{const {state,attempt}=await active(id,examId);if(state.journey.draft.marks.findIndex(n=>n===null)!==index)throw new HttpError(409,'Responda a questão atual.');return attempt.id;});}
 async function audioMark(id,examId,index,mark,expected){return locked(id,async()=>{const {state,attempt}=await active(id,examId);if(attempt.id!==expected||state.journey.draft.marks.findIndex(n=>n===null)!==index)throw new HttpError(409,'A prova foi alterada. Recarregue antes de continuar.');await db.query("INSERT INTO exam_answers(attempt_id,question_index,mark,source) VALUES($1,$2,$3,'azure-speech')",[attempt.id,index,mark]);return get(id);});}
 async function finish(id,examId){return locked(id,async()=>{const state=await get(id);if(!A.accessExam(examId,state.journey,state.curriculum)||state.journey.draft?.id!==examId)throw new HttpError(409,'Prova bloqueada ou não iniciada.');let result;try{result=A.finish(state.journey,examId,state.journey.draft.marks);}catch{throw new HttpError(409,'Responda as dez questões antes de concluir.');}await profile(id,result.state);await db.query("UPDATE exam_attempts SET status='completed',score=$1,finished_at=now() WHERE user_id=$2 AND status='active'",[result.score,id]);return{...await get(id),score:result.score,passed:result.passed};});}
 async function report(){const users=(await db.query('SELECT id,email,name,role FROM users ORDER BY created_at')).rows;return Promise.all(users.map(async user=>{const s=await get(user.id);return{...user,level:A.currentLevel(s.journey),pending:s.journey.pending,completedLessons:Object.values(s.curriculum).filter(v=>v.length===3).length,approvedBlocks:Object.entries(s.journey.results).filter(([id,r])=>id.startsWith('block-')&&r.score>=80).length};}));}
 const get=id=>locked(id,()=>read(id));
 return{get,entry,stage,draft,answer,audioReady,audioMark,finish,report};}
