import {test} from 'node:test';import assert from 'node:assert/strict';import A from '../assessment.js';import C from '../curriculum.js';import D from '../learning-data.js';
const progress=n=>Object.fromEntries(C.lessons.filter(l=>l.level==='A1'&&l.number<=n).map(l=>[l.id,[0,1,2]]));
test('sequential lessons and checkpoint cannot be skipped, including imported completed lessons',()=>{let state=A.defaults();assert.equal(A.accessLesson('A1-001',state,{}).allowed,true);assert.equal(A.accessLesson('A1-002',state,{}).allowed,false);assert.equal(A.accessLesson('A1-002',state,progress(1)).allowed,true);assert.equal(A.accessLesson('A1-011',state,progress(150)).allowed,false);assert.equal(A.accessExam('block-A1-01',state,progress(9)),false);assert.equal(A.accessExam('block-A1-01',state,progress(10)),true);state=A.finish(state,'block-A1-01',[...Array(8).fill(100),0,0]).state;assert.equal(A.accessLesson('A1-011',state,progress(10)).allowed,true);assert.equal(A.accessLesson('A2-001',state,progress(150)).allowed,false);});
test('80 passes, 70 fails, missing audio cannot finish, retries keep best score',()=>{const marks=[...Array(7).fill(100),0,0,0];let r=A.finish(A.defaults(),'block-A1-01',marks);assert.equal(r.passed,false);assert.throws(()=>A.finish(r.state,'block-A1-01',[...Array(8).fill(100),null,null]));r=A.finish(r.state,'block-A1-01',[...Array(8).fill(100),0,0]);assert.equal(r.passed,true);r=A.finish(r.state,'block-A1-01',marks);assert.equal(r.state.results['block-A1-01'].score,80);assert.equal(r.state.results['block-A1-01'].attempts,3);});
test('all 90 block exams contain balanced questions from exactly their ten lessons',()=>{for(const level of C.levels)for(let b=1;b<=15;b++){const e=A.exam(`block-${level}-${String(b).padStart(2,'0')}`);assert.equal(e.questions.length,10);assert.deepEqual(e.questions.map(q=>q.type),['choice','choice','choice','listening','listening','listening','writing','writing','choice','choice']);assert.equal(C.get(e.lessons[0]).number,(b-1)*10+1);assert.equal(C.get(e.lessons[9]).number,b*10);for(const q of e.questions){assert.ok(e.lessons.includes(q.lessonId));if(q.type==='listening'){const l=C.get(q.lessonId);assert.equal(q.audio,l.example.en);assert.equal(q.options[q.answer],l.example.pt);}}}});
test('placement overrides declared level, descends to A1 and blocks lessons while pending',()=>{let s=A.choose(A.defaults(),'B1');assert.equal(A.currentLevel(s),null);assert.equal(A.accessLesson('A1-001',s,{}).allowed,false);s=A.finish(s,'placement-B1',Array(10).fill(0)).state;assert.equal(s.pending,'A2');s=A.finish(s,'placement-A2',Array(10).fill(0)).state;assert.equal(s.entry,'A1');s=A.choose(s,'A2');s=A.finish(s,'placement-A2',[...Array(8).fill(100),0,0]).state;assert.equal(s.entry,'A2');assert.equal(A.accessLesson('A2-001',s,{}).allowed,true);});
test('fifteen approvals promote the estimate and accuracy drives performance',()=>{let s=A.defaults();for(let b=1;b<=15;b++)s=A.finish(s,`block-A1-${String(b).padStart(2,'0')}`,[...Array(8).fill(100),0,0]).state;assert.equal(A.currentLevel(s),'A2');assert.equal(A.performance(s,'A1'),80);assert.equal(A.accessLesson('A2-001',s,{}).allowed,true);});
test('empty answers do not accidentally count as option zero and pronunciation cannot use text',()=>{assert.equal(A.grade({type:'choice',answer:0},null),0);assert.equal(A.grade({type:'choice',answer:0},''),0);assert.equal(A.grade({type:'writing',reference:'I am here.'},"I'm here"),100);assert.throws(()=>A.grade({type:'pronunciation'},'perfect'));assert.throws(()=>A.validate({...A.defaults(),entry:null}));});
test('v5 backup preserves assessment draft and scores; legacy migration grants no passes',()=>{const legacy={format:'studyia-backup',version:4,data:{curriculum:progress(150),profile:{name:'Aluno',goal:'work',dailyGoal:5},activity:{},introductions:[],numbers:[],cafe:[],listening:[],review:{pending:[],reviewed:0},vocabulary:[],appearance:'system'}};const data=D.backup(legacy);assert.deepEqual(data.journey,A.defaults());data.journey={...A.finish(A.defaults(),'block-A1-01',Array(10).fill(100)).state,draft:{id:'block-A1-02',marks:[100,...Array(9).fill(null)]}};assert.deepEqual(D.backup({...legacy,version:5,data}),data);});
