import {test} from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';import {testDatabase} from './postgres-helper.mjs';import {courses,config} from '../backend/languages.mjs';
const sdp='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n';
test('both teacher voices send the chosen speed to the provider',async()=>{
 const {db}=await testDatabase();let sent;const server=createApp({database:db,apiKey:'test',realtimeModel:'test',fetchImpl:async(_url,options)=>{sent=JSON.parse(options.body.get('session'));return{ok:true,text:async()=>sdp};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{const setup=await fetch(base+'/api/company/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company:'Speed test',name:'Admin',email:'speed@example.com',password:'test-password-1234'})});const user=await setup.json(),cookie=setup.headers.get('set-cookie').split(';')[0];
 for(const [character,speed] of [['zezinho',0.7],['mariazinha',0.85],['zezinho',1],['mariazinha',undefined]]){const result=await fetch(base+'/api/realtime/session',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':user.csrf},body:JSON.stringify({sdp,language:'en',character,speed,level:'B1',practice:'conversation'})});assert.equal(result.status,200);assert.equal(sent.audio.output.speed,speed??1);assert.equal(sent.audio.output.voice,character==='zezinho'?'cedar':'marin');}
 }finally{await new Promise(r=>server.close(r));await db.close();}
});
test('realtime requires authenticated CSRF session and server-owned language context; no secrets in response',async()=>{
 const {db}=await testDatabase();let sent,headers;const server=createApp({database:db,apiKey:'secret-test-key',realtimeModel:'test-realtime',fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/realtime/calls');headers=options.headers;sent=JSON.parse(options.body.get('session'));assert.equal(options.body.get('sdp'),sdp);return{ok:true,text:async()=>sdp};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const post=(body,extra={})=>fetch(base+'/api/realtime/session',{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(body)});
 try{
  const body={sdp,language:'en',character:'zezinho',level:'A1',practice:'conversation',lessonId:'A1-001'};assert.equal((await post(body)).status,401);
  const response=await fetch(base+'/api/company/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company:'Voice test',name:'Admin',email:'voice@example.com',password:'test-password-1234'})});const user=await response.json(),cookie=response.headers.get('set-cookie').split(';')[0],auth={Cookie:cookie,'X-CSRF-Token':user.csrf};
  assert.equal((await post(body,{Cookie:cookie})).status,403);assert.equal((await post(body,{...auth,Origin:'https://bad.example'})).status,403);
  for(const language of ['en','ja','ko','zh']){const result=await post({...body,language,character:language==='en'?'zezinho':'mariazinha'},auth);assert.equal(result.status,200);assert.deepEqual(await result.json(),{sdp});assert(sent.instructions.includes(config[language].name));assert.match(sent.instructions,/explique espontaneamente em português/);assert.match(sent.instructions,/uma vez devagar/);assert.match(sent.instructions,/depois no ritmo normal/);assert.match(sent.instructions,/áudio estiver pouco claro/);assert(sent.instructions.includes(courses[language].get('A1-001').example.en));assert.equal(sent.audio.output.voice,language==='en'?'cedar':'marin');assert.equal(sent.audio.output.speed,0.7);assert.equal(sent.audio.input.turn_detection.interrupt_response,true);assert.equal(headers.Authorization,'Bearer secret-test-key');assert.match(headers['OpenAI-Safety-Identifier'],/^[0-9a-f]{64}$/);}
  for(const change of [{language:'invalid'},{character:'custom'},{sdp:'bad'},{lessonId:'missing'},{topic:'invented'},{speed:0.2},{speed:'0.7'}])assert.equal((await post({...body,...change},auth)).status,400);
  assert.equal((await post(body,auth)).status,200);assert.equal((await post(body,auth)).status,429);
 }finally{await new Promise(r=>server.close(r));await db.close();}
});
test('realtime reports configuration honestly and serves new assets',async()=>{const server=createApp();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await(await fetch(base+'/api/realtime/session')).json()).configured,false);for(const file of ['realtime-ui.js','realtime.css'])assert.equal((await fetch(base+'/'+file)).status,200);assert.equal((await fetch(base+'/api/realtime/session',{method:'POST'})).status,503);}finally{await new Promise(r=>server.close(r));}});
